---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: &dbname freshrss
        INIT_POSTGRES_HOST: &dbhost postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: &dbuser "{{ .FRESHRSS_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: &dbpass "{{ .FRESHRSS_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: freshrss