---
apiVersion: v1
kind: Service
metadata:
  name: tailscale-internal-ingress
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx-internal
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      protocol: TCP
      appProtocol: http
      port: 80
      targetPort: http
    - name: https
      protocol: TCP
      appProtocol: https
      port: 443
      targetPort: https  
  type: LoadBalancer
  loadBalancerClass: tailscale