---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-pg16-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: postgres
        group: infrastructure
        url: tcp://postgres16-rw.database.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cnpg-immich-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: immich-db
        group: infrastructure
        url: tcp://immich-db-rw.database.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
