apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:unhWSTM=,iv:VNCg+0Lu1qDZPpC45En9J2VtffI6ZoHooMqIvj5Z7Ys=,tag:HayyaSuFArFio8/+8/Y2hA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:6ku+Ft3+D9QMCBoxETYZmJjuZYez/ankzRA=,iv:7cjMqx8yuCEieGQXABdhcWDZrIjumME3Q6WdZeTCBPI=,tag:TCHVVkmy1o51/y2J9kcyOg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:M3YOFGO5qzMzG/getlPUGGQOCWLcF0L9g43Y9gVX8BpmuDStkJfaMRYwcphakKHVbspbCtDOnURoj4NPzQm6gQAIQ9bqUxj06VIZt8bwjo2z8PEeDFLyh3EYobXAbbwQbUZ1bGnKJB+p1SzMNZMD3do=,iv:qBzeVHJGB764BR+q+jolM3cfBqA5qvW775OjHBF5iqY=,tag:9FLcHCpP08/ciGOULjtUVQ==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:paLf0OeM/WsyeWVnJk9zZFgd8jvtA3pADTwDGgBpc/5jvJdUUNBcRy0rGgQyP4C1hbuRQvdQDocHBCFBzlNWkQ==,iv:F9ZEZdo2QepO/3iqrFK+4Qvd2ZJjDq8K3R0TLw8psJU=,tag:7Awy3c2VgnyJBnGdqyuHKw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:LwFhEkZUviU=,iv:7tdQDrxvBNKQqwewt0s4e/TAIvq6q+mqGmiDl29dglc=,tag:Ws0TaW480oNwm+sYV28USg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:G7Az5Ha1ixQ7DoZOlCTUKDRoFWj/RK3495MLYAGHzH3azazl1pGLHw==,iv:GKb7L9CHTwCiZypojHxdDZdCwyUHxMSBJBerMExQ70U=,tag:ifc3GMTFfDyJKQIQI6pEFQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:tvBcq4O7ZCM=,iv:N8lo6hS8GyR198/W9HeBmkNpvyUgHhFgo/+RGzvvtHM=,tag:GmBLBWVJiIc7d0nITU/66w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:n0C3cWIjyU+LBu55xOKbnkvg8hokp2IqXSZO,iv:Lof7bO9eaLZ0hBTMxrZGbl1uIAUEVIfLLPcJQiCHIiE=,tag:aQgWtL4e7jCuH4ZUXC4beQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/aul/J+Hq2sNEF8Kx81QsQKvl6t/wyuFAvcJkw==,iv:owxqBynyuyElvdDF7XlUOeVJBR+w1DBjn3rtnGIr2Qk=,tag:uQnvjAFxiZ+VvGohu1GRfw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUUNMWUJGaUFmQU8vSTVu
            Vk5qamlOSHQ3YlBUbGVEcitRMEk5Y28xYlVRCmxURmZleThjNXBQOUlJUk1SS0Vk
            WWJxYWFWMWh0NXhSenVPREs4WU1qbGMKLS0tIGR2MWRQaTFRcC9OQm9jUmNvS1h5
            Vm53YVN5S1Q4SVFpaXZnS2UwM3R5a1UKq2iGUxwrQ5qNImYIVrpRAouixYthgpBG
            rOEYvvW4gmJy5O2jb1IuOT/bE+SZGR/HB5pQS7FJ8LsqGk/XQYcK5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T13:13:17Z"
    mac: ENC[AES256_GCM,data:DHewDREHuvfGRgr1wx9WR9hKkBb0HdFzdkkuEuHH8Aji9dNAPt+JE3GGr5MHeVHBlhSoc/EsXXTtxuwqz9RScRXjsg2vFx6f1SmDvPEKfn1999CnbcHf/5gQ75EKd4WvgRShkEqyLVRFJKKoBQraZAa1IxvxSQ8Yah354A/tpAg=,iv:lS3ZnzjshS+joiVcAlb+ew/qM+oac6oFR1NAaOMRYh0=,tag:Ep04Km2a0B8rt8NBrti8qQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
