apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:5ZHloGg=,iv:/MtKrjCEHI9WaaN+WTT5MKrZdp5u94k9Q/8Gnp2zoxs=,tag:QVIvrrira+QDwWaXeds2Cw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ENovKVWfiTBGmRBSUH4tFM33NJt2fm1bF/E=,iv:L5jRt5bHnaOm9b1huJROfd01MtZUtOk2x2jaeIaQWo0=,tag:cHLrC/OrtzOEum2rLN/01A==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:/5zez6BdH83/jEYNaE9eiW0e7Rh6d740k+0DyWg15E/15pv/wqJZY9GxEnEJX7tVMdsQnBLw+LuYAmBxwo8nqyRykNp3KrcKBxs9XBT5dg4FEoRffcRi6IfC5KX/rCN3DKW3NMEM/yEWMy2TfJDL4Uw=,iv:VcDAe9e97MNO3sJpdMyUJsKfihg7puj41k28w6oL4II=,tag:DZ0rHqYJ20wT7y1KlzXePw==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:SL3x0EBoXcHaRY8KI/Hoi7Vm/KDlSkCulle+0qlnyuzakc7Jmzzrf9HheUaON9mnOe9k09Tv24gxv7fs++iLLg==,iv:chp3PFDV6iYQFu71YqV4rRBhXzE/TPkb83zfWon4OL8=,tag:/XZXNkoue86nHWk5RMXTyw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WOBckS5EZP8=,iv:Z+tW6OPmeBgmWkBC8dBRmMqYfBt3jQuShDh9cYmUYyQ=,tag:mmC3pM4IIMMhLtGq2rMX4g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Hr/UIfq8KOyCRyH05+ZJeNQxUafpI3YfUFfNxcxFk5eXvKX0iWYy6Q==,iv:ma5pli0kx+n+ndcYIyZYfCZwT1SDZZDwatz61OPRoCE=,tag:rjXAe7xYJneg+V9zcIYqvA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:KIEupIFCRS4=,iv:Wbc9BalJzcd26hgh3vPsAg/RRlS8pJnySPFxse+Y7F8=,tag:ECNwmiRy29fA81kC/mr9mg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:SoJlPMJvC1nedc6lgxqfgKX/dQUwTe5Lcs0a,iv:7OJzKnGcduibg0c36ANCRn62SsZa4P9kNm7XUvK0/ws=,tag:/VO6g1/zPQCtm7BBZpnZZw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:DWAoCbiiB2PJmRj8oQnu4KbaqHKJxajPTgudeg==,iv:MvlKza0bpLJARE9K4wTWH5QdFNbHNAKFg9t/V0PndQQ=,tag:R92Zgw7WhrYaTiZL8XOa5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dFM0dUhyM0xtNmZsaEto
            dzJBdlJ4WmIzMHNHaVI3a0RQTlR4dWZzN2xrCnRhTThPMjRGNlVGSGg0STl6a3BH
            TFV2SHk1TU8zNmUzQ2c4Mk5iN2lMS0kKLS0tIHRoajNtV1l2WTU2VFR1ejhyWDNi
            QllKSUdObEE2Y2R2aVN3WGFYd3l6WXcKjMBLXK35LILBT4zDDkpmFgu0qkPO5NDP
            4Gu+/mcckBANUmWhnUTMAbRLeRd1i4zBw/qvGPeg5H2lpqAhOFor1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T13:08:06Z"
    mac: ENC[AES256_GCM,data:Krov+9kJ0ZTQI7EkWCmZWHFmlX/YsyJuFZDs8RnMN2kZDaF4n3Cf1Y7Ku2Tn7kmgvBUtBVlXnKcdEFcuY2ukTf37KkBVpRLZ6f5VxUhAh4JYSt/o0fPGhQUUCYMnH8q2W5ZyHK0YyhisS0G4mCyKbp+a724STG4DWCjLZrYIbYI=,iv:Cy2r64eLjaquL9MOecBLEIg4izya992aM6E1Xhnl9y8=,tag:qQ5IgJmFdEmMb0/YYbmv1w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
