apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:QzjjFS0=,iv:g9lXEgeKhrZ1JBDwZ7l6IdGWAdSIY/VEja6xevJvJUY=,tag:yy7bpomgOm6IP+28tWeY8Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:pZKfNuM92tyeHIteL+87aQwGFgWjyx1E4oE=,iv:HUk6DvJn5MyYs4+Ymkonb9vT4yGOyma6QEa6eYivj80=,tag:15eUX6kusA2JWEAto1zWIg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:JM/Hcy8gcaiUv8pKZ2DYlksWgET6Oll/bCRmpI9yRtfQxy5wf252ybWQ3rWHmyQEJ27chpNSntHGrNBq92F5AByjh/ghT54fL0YPW4Rp21/SdW41u1bHZxv1l76n0du98NU7m8Eu0iZbRC10rTxeeJ4=,iv:+2VDj7CPP7YW4SH9UoKarOm1AFFn/6LGkFa/AV0NdsI=,tag:Zx68JmBApP0Kzi7x9NzBBQ==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:NWJ0RItDQbZoN+fqs+deZInGbmQO8zZOcTzxZsgGxBYpKZ+CUTCUcGYHZbIAAqvddJ7dg8nSgpD66/+FCK3Kmw==,iv:2Fv+jZurBd3bG8lcRJBgIR5FovEwE9XVqSA/COF06tM=,tag:7VnvwUPjIfW83GlZX3JAJQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Fn08t0w2ex0=,iv:9oh+Hnh5dacnqwmpFITPCakMBWQ3le6xVpM/3TXceBQ=,tag:RUG4YPpzol40uwYvMbs8Vg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AWSKY9oVq4TjxUEEiBO/I9/rIUILvhCtJ223tgQlUj0GjwsvEmbKsg==,iv:icHT3EBIzPyHEYPoHZOjbyJJfxAZbLS8izKHy9lmeEk=,tag:wSD2mgX6tuJN57QRGlOuiQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:A/t/ADe8Fk4=,iv:oGG5cZxryKsAcKTpBUGtgdVFDCS68/caAaLRjGRBiPs=,tag:kYp4cm9bMGTOKRHQ/93tKQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:sKGeiTY+lXuh/KF0Yd0v5MAOOulqQaGcxCf4,iv:u+7M/VyAxXHVVIcwdFCWWCZ6xixdkoVCbxyvH98CcJM=,tag:9PL3rCNlsFLFUYF/FHFMTQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mBmANMWTIjd12e3icmD1RN5C+KW4IUZblJFMcQ==,iv:XKPgctqvYOzTqycEXdUTViYtMkGE90HjhMe5FHtmV9E=,tag:qrriT/mKinSYVz7leeylAg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKeGduN1pDVkMzd1lmT1hI
            amlEOCt0VmVBUVFzSkprZUNKTGRvSko0dFFNCkloN0VXTkxaTmMrUUFtWmdyTkhl
            Ynlidjl5TjNHSlZuc0tSTURsMFVYdEkKLS0tIFhlbTNsaElmMnF5OGZvSld1ZGZk
            VzMySkZqZElzTUdzMkJFRmpHcHgrc3cKqn+juVrDDFLAQRXIQyND8YREIzJaMfE3
            eaulfIWbDQL1ULFgut1zuHtK873SbMscdJV72rtPCSgjCfAG0zHTBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T12:10:56Z"
    mac: ENC[AES256_GCM,data:bbANYM3SV+3PGyc1+fJUWaPZL0Gv+GJta4GCvHfU1K4rkeg0Mgosz3xMeoIXQ+S7LyTY2lAJfvRfLs5n3IiyXJTJ4vzymwiM0D8ELIUlJEj+Ysb20Cx1C1ogjCAnIfcgvDZFvFrxFB7mPpGOgGFiG8WZTiooJXAuwOHULiGL7wg=,iv:9ybl22OSQdxpq76ZrYhXaJiSH58fqiRtUyau3Dh4ijA=,tag:6jYk/6gKUcaW/vCGS1qlqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
