---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app csi-driver-smb
  namespace: flux-system
spec:
  targetNamespace: kube-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: csi-driver-smb
    namespace: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: csi-smb-controller
  - apiVersion: storage.k8s.io/v1
    kind: CSIDriver
    name: smb.csi.k8s.io
  - apiVersion: apps/v1
    kind: DaemonSet
    name: csi-smb-node
  - apiVersion: v1
    kind: ServiceAccount
    name: csi-smb-controller-sa
  - apiVersion: v1
    kind: ServiceAccount
    name: csi-smb-node-sa
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: smb-external-provisioner-role
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: smb-csi-provisioner-binding