apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
stringData:
    server.toml: ENC[AES256_GCM,data:x159i6Kwyv+7/w9YsLl5FcdJFfGzvGC/08ebhbfHUbDMiD/Adyn86AFZYTO0v3JGA89E226hTHc2zKFvAY/82LfJb6Ux/rY+P7N4qu1xz35Om0CnBAg5Fywf6k1KTsiAROnAU5UZHmjo2cTH8n8TJ9LVTeeemRPmXCkEaaGOXFWPy7NPRMG3uqekp53EJADr77fTFekMBJ5hbCPeDjDFwdynkOSxXdjKn41uK+FrekQ1nyLru+2E6NI9BHXjoO1VNj+8/LT26XwiryMk3MjIakF8psYM,iv:NmkGBbvSYoO6Ar7p/AS/7nMFJUdqioKk/tu9xBZexEM=,tag:YeebvLWm6akqHVHoZ4z3sQ==,type:str]
    groups.toml: ENC[AES256_GCM,data:EpeltpRwFgGRLJ3WnOTeIedJ+vN/6X7YGyUfMQeUxpc9/K6kKU6078jlP4pE9OkZmVsQ5yPyiNcxIZoQUegNQw+b679yJPukH9G70Xc0IN2eODpNCWc98/MGEepaPV7gKLOmqXIaDmJQz7AIZk9wLLl7R1di4fzrEPa74KlHJ7+K7uJTMmgsjaxCiO0SqhzaQ4o=,iv:qIc9pMOOWqMBXQm+C9kbpKLuRMPWAIe2vzlPd8n3Gf0=,tag:ygVwY09UKXZTfwLacnoJ3Q==,type:str]
    users.toml: ENC[AES256_GCM,data:Wp5BIZWR2BmrX6+LzHGU7edxbevsjr65MWxXTVV9q2afaw47cvhR0+z+GR/N7ZdgVriHJf2GxCq6Hd7dQfrNDXENXFbPqVzs+ac33X9dhD7FpX8AJS5UsHIt/Wp7r4yZ9hS3ESuyT8urbRKb7RDpRuY0bivQBOOkh7nsSbUyo7LzB4aLC2+Z8PRSbbe6ZEuWx0xjKMx8ewpdzYz4ODA7vBAsT7gRgFL6xLstYHArO3Ys+FDq5wXZKLsoOo4FBfqEdpQqDaolL0TT4y+UREyMqtWjHrapFnFbFgKueid2G3Jnemd40gPGj8RVyiy0DSqIMmPxMZd/LhUcEoEZ2bB+mPXXg/pLqnC2WJwvAklHjr1MkwtRXPEt7N1nmNx61jnHldHzyPnqsPJZ+huvvpyMzucu6JJN/1lmCsb/8e6You7RHlJlph5gl80xqPbTIxVirMajW7PlCtSfOF5mvxh8v8op/pKIboXa6H6UvDvU63AHjAqB3qOfsB5JFBhz8C9dtYi6Ow+rMetsbhHZuzEF5ncdaJf+FhQyEC2dp7Ajwf1BHrsuXWCNXfEeQW10p9bDQDqrNCpAtGhzM6FgdhBevY3dV4uSF7ksC1dIOe3376qkY9LrYYDwwm+Zg9eBhPNbKdAiZCvTT2htfgKPwwgvCcME0fETiRGGgrtSdjKYjkJwZLd1vhX9vKEFxsyBXAMBStBNXyp6jcRhA3xsXUjuss+VjPQN9PrNjtiDmL41bFUmPiKLbT8qJIo=,iv:a8GzpAEdO/nr5l1lWgQxvmJf+TVkN9RtzWm8xk/tdWg=,tag:9qiKbr8ONO/LqX0Fge2Jeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aDcrdWlwRi8xcFBSZXRH
            QkZFS2VWZWtGZ0V1R3lZWnV0Ti9ITHlrdlFrCnAwMUgvSmQrall5TjVEcEJQTzJM
            dlYydmZJdERtd0RUZTNQVE1qQ3JhTW8KLS0tIG9haGxGanRGbXR1Y0RTd0N0Y1RU
            TEw3T3REOFMvRWhxc3hEVUp1ZzNFeVUKhTSurooZUf2Vb6uDUD2+V+2MWUMur7u2
            sSWAv83jwV+6iK2RU2RjViHv61/pkMPo6CaxQG5bCDR6Kxpes80d9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T12:39:43Z"
    mac: ENC[AES256_GCM,data:yKAotYWA7VyvLCSx8caXDqHgz34ddzPNQo3h1kN0T9trC5sVxoscwgQQX8Zy67z2DJt8kw8KgT+qawNSgLaMof1h7TH2m0O4QcoUwxCCs51LHryXq8rJY/lsa3GWbAMCriQyXwCfhD0bE3aAZwMpurrKw89hw290mJ/e3VveuFA=,iv:Mr0KuMQM+XxWwEcgyth/tOLvDMFKFpG9BZN9Vo8Y9uU=,tag:8pASRsIAd4z3suoQhKzgPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
