apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
stringData:
    server.toml: ENC[AES256_GCM,data:eUu6twLVr1luUqookuOtWgz04uedHgEOhm41E+mrMcOC4fMHQvCEj6cXy41SUuBXlThh7iJ6T8yy+J2lIhII4u0toyKSur9PpMl4xYdLBxsaj/5AhjtCoG9OJY2LGi2laxOkjslPHcSpfHzNgNoGUdJSsmd00DqR7hTeuzJUI5EN0xhcS8DS2a9MNEHBrzgtejEFO2mcpU4IIL6Zem8+IKMDI14WYbJuzFtOmeyiSyvNlxMmh5B4ZvRsnODD7EVOdcBw0YZFS6gFAb1EQ877DNDpNH+0,iv:C57IuxhmfPa4Io4xKRyqrmB9EbFo3ScMotnX/lCBzdc=,tag:faE9Pls5YNOyvZ8aQVAyCg==,type:str]
    groups.toml: ENC[AES256_GCM,data:XqqNeCthbQqf7GPXerEbsNtlaI2IScwJpSyokWFGGIZXbF170ptpscsGABQ5c7yXJh6ox3Cgc8k/gY+9WUcOcNfHk/CTta4g0q5IJf0MkaaQxC9QWvshYBoBKL2EJp9f1A5NDXHclu2Xat4pbOEjsooDuM0aexRoyqGNej/DYu/p09r/9VmIU2IjbTqoIt5OrCA=,iv:KiDAR621weFGUDY2ItLtOl3zPT8sTEfJu6vhZzZaBa0=,tag:SD0eCiKaP7rv8p76UOC8nA==,type:str]
    users.toml: ENC[AES256_GCM,data:zvjWJLE/Wk7UyW6D4ThatTDdPMwtiFQYy0nFKgCh7NlfzlZQX1ERCyyv1dFkTYqjQ36BOn2Z4mKYixqaXt4bQGzUkkYM3dRfhMJBhNmqUDLONp3m0khYFI9pQrMuK++f7u94Zud0DQwe+9YCq0YtcRZsEeYQ4N59zB+rg3Zz/YV+0Qsr6rBzbngPhvkgAxiONOH/fAHXo0AgnR/9yivBuhYQxhbj7l+5aFKPvZnXWeaUd6dldMwVo6HoBn0/4kH2mH/9dlOZjU5vcWstEQVd6mUwAcNXFmVa7GXaZ1Uyu2Ze5ai+As0WF1Au7PzVNJ9HeQvmQpFApkynBM3iUzSRePNVOaiFh8od7FNw/rHcme3xa1CZOCs0KIG4oOuQNefqp1rqGPO5zYq4wjsF0hZ9CFWLnVRTXxnqblxv4OpDXGNhiuyIBLesZqTnr+w40UcyfQM5WaDlIOoBJ0nsvByv8kFyuz72SBx2heYz6muSAaOslxxAJkSByyyX2ASfvMgSHVy9rEb6qgrcWp4yLv+kXOKmcAdexdV6EpJuikQ0JAmgdGL5RL8bQwv9Sxy02keT5e8XOdmweHXm1fqNypf2iZf1XIqtSeNIx5mgW/3sgT+DXuRojzX+nwKfCmqjiGom46LgCbbVXSSEmMRauJk3pH8T9Jtyyl5v4O2hmOE9C1P2k9i53X7lcKuZ5zZIgtJnKKPvvryQnZsuzJAgNhPzpc/l3VHPAD/IpKMyjVYaNsARt3Vga2HsvOo=,iv:/KM5ayc8eM12rYqoF1s1lTbgZD+4dK954/K6imWxAJo=,tag:ckFMlLkEJFZHjbH1dX1s3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdVZEV3dhUmVGMUYvS2Fj
            UXREam5tV2ZFVHFNWUtVZFozaEM2WHd0WGpZCjF6TGdhN0s3eWk1MDlsQ00zOWZS
            ZzR1dzhOTWV0SmlMcEQycU45RlFEbGsKLS0tIDJvTEF5b3RTR1VQQUNFbEpmRDZ1
            ZzB6Y05JWldCYUxMVS9UMk1tWkJyU3MKj4LWShJ24ag5z3lVWlLWraGmqEgssCKn
            GhaD5ijxbTzVCZEnXZmG7b6KhMJUVVHQ4UHT6rH13bWhaUn8TyaP6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T20:50:58Z"
    mac: ENC[AES256_GCM,data:YFWsV6UwGg+AbE5UqIT0uvyAZrxEb4J1PseXf1WJ3ldju1yj1mQmbDFiUR/Ea+2o3qoNuh2LRWHe4EDylORnAZtsPf7Em+WTOfNSXnch0LF6a5j3yVfBMSsg3Q+mjkc2/nB0KPNEWkieRSMVVTQTUlaTRhkOXo1Lsgn6lrThj8g=,iv:L1ql2ch/8iTKnOwOv0v+FwHHbN5EflS4Swmn+xIundI=,tag:HwKXGA6ZiHK1wDw0eQCjhg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
