apiVersion: v1
kind: Secret
metadata:
    name: glauth-secret
stringData:
    server.toml: ENC[AES256_GCM,data:duH8aMYL2gJI6ZSkUh0YhYc/BTiWwGTDlkb/WYVU3jFF0JS4ZA/bceYifLG1pEfdc+5ZGFG9bdFg9fLxrMh1AgFhydX0lXU2pt7kgQtQvl+3k49oW3HuFTKd98mI6AVeq8svkWWaymEjswJuqcjPPtNX80BNIMF3lIgwRfGwFf7TIIZT7VuNhmT2KkrOVP3tUOUsTyglGvVDgkUHYtXBT92ypYTlHfhKdN6vRVfRmqZqB3avf3wTdSsxo9kNue15ehJDJ5nWl+8ExgBqhSmv1CElZwTf,iv:vWhpD/akS5cx/Ho/0rQPdseBOATezjfpnl/eksDZqSI=,tag:OeolYbYLuYbmmJsN+TycXw==,type:str]
    groups.toml: ENC[AES256_GCM,data:w7E0EtmaItU4SD6Gik+CfFlBWGq9PL33wisN0PqvyqCMaqLpyp9gknpOfMyrl2/OGvnh3CkUTjvPYDlA+PAVqK1LoFZdoiwcTFjYPixoOHQ5JCPL6j7piBpLZPf7SAh2CAiKQ4NhCxg4eqxpR9dS9t1S07sLLf6ITRZ12JASP/UR4ui6Y4qd/T8uEVNJSbOR4Kk=,iv:uD/LoE0kYGn0BuG+inkttEMN/duYen4cn/UzFVNEQ1Y=,tag:Yg4YiQiPrTtdGBxNQXsXGg==,type:str]
    users.toml: ENC[AES256_GCM,data:Z8IuI816ig6qy2ZdOA60BWs5H4Fdg/opll7Qw1k2tTJi/Quj3qClxrB2hqsra/DzQbbHkHjNQF2mrFjpYL93It+3VYqPUlU4Q8mJoJik670MEPzjv8RKwAxDRY72YUCDUbj+jmIXbu0RlUvNcYavd0sasu43xbT0IHoyxCkApq5aVXXGHdMAkD89sppqS/1PHia+e0upK4yNXPXyr9SUmR8/PcGFTEHSLPhXI6lGd9EphXKZo7MYCLySxthWb0vcEtCg5waato+efOJH8cwVI8Crgmz5OPSoVAD67aOS/K7NfoMBxWVVqWiWNod+CJaI1obGv/cSfkxq6SRXBhrgdcpJfen84N9cIIrZxvrXn79zscekLIyFWuszN01rlZ5ZZNJEYshsBmo3qIHhiXhr40RgYZTl2pGOTcQLX+3uKqeKWTdPxTqwZ40ev698WmugPmNk48m+9LDCfSW8HTwmlc0YjPxgRG2Q4/NGq/+Zf2/sIqGNil0MDfmAbDcwUGpurcpWBuPMdm+KbBwuVWMZ0pBUGan4fg4VGtEi/ocVxsDQI5VWzcA9lyTHNO9y0g+yG2U+N4pwpXwY8j2J2RAEYv5nkfWIitj3E3eftqRJd8SreG9kc5DIimz+WoI14RNR2ZWtKxM1MGSuc9Bjgpdmk+Mn8PgM87aYbgU5XSKS13TW7qJc5Gb0cn5PRBCFpsR7HjoIHOZkAToAHPA6TEg7HoSuh65HrwEc91Nbog9A6OqriVPWdw56124=,iv:VAukt8PrG9JAgeLLynDlXYc390V+LUROQptnMPQ2Amk=,tag:HBvsRz/fx2fhFgCG6+bC2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbWZsbUFZL09IUVJCOUNi
            V003MndkaWZGWkI1SmM4YThHbFg2cGZ4NkdFCkFBU1V3dG9XUGFlOUJoZHhUS1BL
            S3FpV0RrNnpPNjRPcXB3clRsMzdVcEkKLS0tIG0wVHQyc1liVWY1YVRuNEJHTlVk
            NTVnM0cvRlU5OW5IV281SDgyNEs0V0kKZ40xWrq5IfZcLP9V0SnQkEhdrLtLWic5
            DVF08b8UG2L1H/JXvthi5RrAx7+mrWKv4MZ5F7+KvaAjgbVsi2mmPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T19:13:08Z"
    mac: ENC[AES256_GCM,data:Zbpkx6RyvE7R2V1q8KUm7xdHLInxg2a8pxYXTrOgpG5+1SSgOiqavlsFYlu4AWFJRvwsVJurSS4JWK8hXsNpOfpGWiR/QCSl5FMVHx1vgDXIxSHArgNCp+/oqzKKq+57D0zFYmN0L8xNdsyxnexxbeBsBVVbuyVS+Rv3/cN2ulc=,iv:Obl6iN8jZU1KxfuLuo63wFi0/HBuNzrEU7uLxRx+PXQ=,tag:egYd6VNIsUCQ0EBFmoR71A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
