apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:RIKFZWoPhgZ0giItR/TKkvmaQ3Ao4qe8CiAfvDDJh//e6mBHhQvxum443/MTwep6tMMT/vS6KijSaXbgkiKesaJh1B2V4qvC49nIghtkKskp6lOUh3UDyA+L4SlsCOlTDBBS7mB7A0UEBfx3gXaA+OJyRC9gFDzv5NCak6sAfUv23XFY00DqsGKCkjRJ8KDA5fDrU8kSYFDPn2Kh25MQ1CO7clP1wVYkrGRdqTIKWUuJcaDKir4lsS8xp6fTOy28je7COWePCYbsKIGjkTZwHb5/itLgDTO3Q9pnjNq0TroXnjfDJFD5IMoPetmg6FhfVSFiV+ZeUFNlRWS4R1HmNdNp7EvhekHTj6YkKzUVG+rZcVMT2WAbkjf5+E8+qwfynsy2FEKtDar4u0OK1u7oea0+NV5mDAJALtrYl0eenVsq/ArX79/ckI+w7sj/1QM/m5s/ABDgUmdmavx+2zO8l3agB1gWzfOaAlv7jl4/ItmQk6nLhVJIw0dmBjfaY8VOr3QGUC/hIEB8XlTSaDWEL95OdjU4g59hDhTyEl1A8Aoq15lMEhRxRPTXnvWwD3BMwmXGbc3OhYC+6hLE4Ill7TrV5g98IvkTdWYiTg==,iv:MlaZrUCt+7PPxMO44m1eSy+Vu1+clpt6ao/qQIKFvEM=,tag:JE3dqfcqYiPoP3ddqlRvgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRY0hKRXZVMU03M05WV3RE
            RUtpcVRpUGtTSHdNb09uSXJtYVJZeGI3Q2lRCkkzbHVIWTNrSUI4aXVIVFZBcTR6
            eDdsNmZSV0xlSmJNSWNCMnBaMmkvUXcKLS0tIGl5YVFYdEk1ZVhwVDZOd1JCbUtK
            RzFSc205M0RNLzNibXhaMk8zbE9XdkkKWIRG+tBULTri/qIORjISStOJ4cfIgI78
            ioXwFcSzFAfHGMJoTSSFowYD153Og9LRNl3VkkzjxmRYDPG07DBI1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T20:30:15Z"
    mac: ENC[AES256_GCM,data:uYLl6CdV7pnokv36hYHOwfNazOwm5/lGTFkoYFWOk1sYeQ/pG48/RbwvguZQnyC+PnpR4IIgb26NhALybsX+OFg1q/Dlwbq4BpLAJ/TZ7g7d7UYNWFuKP59N1+wXYqnWWGNaDFLUlOHeziF87YeCgNvLV1EaE5GusyDEkOUF/Fw=,iv:oq9g9PKcnYD6D41Zy0U+pii7gnA346F62IQ0NQGb5a4=,tag:0rlkKb0O+PbmUHoVwIVxmg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
