apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
data:
    alertmanager.yaml: ENC[AES256_GCM,data:zd1MTOAqOygZF/PeJiTUKmiuC2C3EBRim8ME6HWR/tJZlFSvLd3RfeY88HystCUxpW+zMkthhXVmuZ5se1oB6pxcJgBW1oWUGj2tSt5t+JMbcEM3gJUbhO4IVmU2POJLXTH8Zhm1GM8+RbGYZB/6h3k6KZXVXVvB1gxSTwCuLHOX/8Ilofd27Zl0pEYacQ5nMu4ZiauYOHsR4WNrtjwYUNrZE77pQ6eonRH6gMSgYJwxOmLruqtXp05E+6zGwJu6xwQBd5KMeItTMV4++zplpntXCMoh6lJzeFDkkuynhGa+IzzZofFAKnVkeOTr0PmRCR6xu/LvEGKT/ds4Kc3t3zeqnJd8A13vUV52J8LZ97IBT17KXwv5qNQdI0Fq4spKwzWUzC2QTWwn8wgN7uRrmEXbyaFLrd8dxdEqAms4WQ8j9zg93Wug11rNdfq64LgzfXf6iU4rgxBMPTlohjh0FxbqjZdK0fwoXM6SllzZamC1Ea2Av6tlCMJFm7bdyJCbJki6dbu2/zxBBO919r/v9jZUw/2sJl/PHzJRwafNOGDVfKQphLkR2cKJk89FmbugEerWseSlacHpHeOGzmlwY0HbcVAW2LdveR+rrg==,iv:JQikaUd1FFQc9RiOdaDMkfznO4gfwb382d+RpHS46U4=,tag:BDKJ8TQ7tk7FYcYCZzk4EQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlekowMDIrdnhtVWVxYUxh
            NEU3alNUY21nd3JuK1JTckd3ZVp2S0NhK1gwCnViT2VUV2lNdXNycStubVBFSzlj
            VThtYkhjYkpaeENPTVBidTNzeUxhYU0KLS0tIFFYMjVjSTloN3MrVXJIeVQ1Q09s
            TGMrNTcvZHB1dnNURjF1MGJwU1JTTGsKjJe9xmJKtXUd7comR3nqU2cPuO5UlswP
            vuqDJtAR/qA09nMrnyqB8OLjrNfb0i6ymd65xFbwQSO7sR0VsS+2qQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T20:50:58Z"
    mac: ENC[AES256_GCM,data:HHlbqYUNu0sqlc2QjrAJwVKoW3ktLqTyZ+bl3NmnKjQPVXtEzJ++Z1ynIvXaVCSq3EVxPyLu1Of4cvsEHEmutUGjR+lVvSaGmap8sKgRHLzZIWdgBsGdKSZazZQ1tlTAzEasyG1H7Apn1LUCCarzlu9Sa3sS/Ck/m5LMpmOw3V4=,iv:lwRA25UWy8RvEuxS5Vlhuy/j1vo6nULlxhQCPUuaue8=,tag:9x96h4YPu4Osfl/B5NSCSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
