apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    alertmanager.yaml: ENC[AES256_GCM,data:xyh4CK7zpApJzGaE+1MUt1K97BCUJ8gdm7fhI9xDP8jmx4bgwkXGMLUESW94leNY0u9DBvq42TmP/sbDxUXikHIfKixCDEKutApgGnrotXaf7lLYJDwuuS0R3y+Wx/+JfBAMjUZwLpkQVE7Jjdx6wVZR3C0ZdkMCP6pTxGeS8RxAIxM6hz9exsYY1Rmu7Xg6TvepM74zqff1+2MrIbeYTeApjbrkKTnIcYgggibWiBgY9wNGkO3h2zCWeGOpjgSZvOlwZFrz/vAg/8hsAC7crfNcSsbcqPtn5q/UMtW2HGHlnneA2ixHmBOFy3+6yjlZldKA8tHXIkpI9HH9z/nkddl8agsdrci+x8TVkE54qlcAO3UGj0AFeziNLvZeB3VcrLrout9M0B1NxANHA5poUIynCa1XK79VsV/MqgKjvNJbsaLYgr7gepC7SxZoj7WCuqgotGD9g0Q4JSMoEvKUF7htsXhk/NQF7QnrpqyXrUiMVfnhqCbWF8ZOtxJ9csTdTmiUROr7IHlCBiVxEr7G608kA+genYe0CN2jXrJo93+sCntLZEt89KIDXuA7GbBAs+Ppy8h1gnp7V4JRNPkp+xpLiQDT52UmbPKnSA==,iv:Rl1qsnD97skuw8LjFP5fZvmxnFtIIwPmoErDsSLV/n0=,tag:rDDYRc2hUmQ+UWsmFs86hg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcms1dGpxcUExUmx2cG1j
            cjBHZGpqUitXcTl4TUdkL0ExL0xsOGJMeERzCkFUK1dRMnpiamwyeFFXNHdmMm1B
            SlBaK3NXYVQzUGpWRWVZZkVKd3hZdk0KLS0tIFgvcXIzOFBGa0tMblpHSk9ERDZH
            a0wzbkpYUGw0ZmN1a2FYVkFPQkM0dHcKSvBpoHh1KHtwiCv6iOEi4eCT+X4MSFlD
            bnVfwFN7SyTTM8gRnh+s4haiUKQJ232UuU3zAJodCf3TBh7/+4NJtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T21:48:51Z"
    mac: ENC[AES256_GCM,data:GBBaIYvi+30nSkSfeNlWvTf/ui1C9hsHR7vujoVceYH+wTNzVTDXQgcOurZDaRDQxoCEpufYAEDEG6ZrX02USw6pefweby4QG892nx4iPRGoVZkSSEVSF3PfPbrSgTNUifWlo7gAlTFIPFX1SrqwCQi88VQgUf4S/xHJzLgKjLU=,iv:C1NrQ+w+f9ma8GtDytbR7kNk8H4OHL2jRH1vsGY0MwA=,tag:IlqcWy102Y9bofJv3Qb24w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
