---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: csi-driver-smb
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kubernetes-csi/csi-driver-smb.git
  ref:
    tag: v1.14.0
  ignore: |
    # exclude all
    /*
    # path to crds
    !/deploy/v1.14.0/