---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vpn-gateway
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vpn-gateway-secret
    template:
      engineVersion: v2
      data:
        VPN_INTERFACE: "wg0"
        FIREWALL: "off"
        DOT: "off"
        FIREWALL_VPN_INPUT_PORTS: "51820,55633"
        VPN_SERVICE_PROVIDER: "{{ .VPN_GW_VPN_SERVICE_PROVIDER }}"
        VPN_TYPE: "wireguard"
        WIREGUARD_PRIVATE_KEY: "{{ .VPN_GW_WIREGUARD_PRIVATE_KEY }}"
        WIREGUARD_ADDRESSES: "{{ .VPN_GW_WIREGUARD_ADDRESSES }}"
        SERVER_CITIES: "{{ .VPN_GW_SERVER_CITIES }}"
        VPN_ENDPOINT_PORT: "51820"
  dataFrom:
    - extract:
        key: vpn-gateway
