apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-secret
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:DhyH6GeDuA==,iv:aIfTPYHp2tX8JVgqhNIBOSSR7lHH9INkTuqw/Ux4ewA=,tag:0zD5f8X4I94xt/lcfQ21Lg==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:zPdACap0VOHGb87stJden0dbFjtRMQI=,iv:dYMByQ5xHPh13d1BotOnV2q3dA9MtIJ91L8GsVSQwP4=,tag:Ev4XN9P3BJ8Pw/U7dAtvLA==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:m/89NQ==,iv:gTJVvGlsf4EB35GylYvFP2Dh6+DivJBeDqnO4VRg1xA=,tag:2TvR1jjaEWYXgW188E/SeQ==,type:str]
    FIREWALL: ENC[AES256_GCM,data:t3hc,iv:Psav6GYKa2BlNKbLsHEpyC4/sqlyrhBR+kaZA1wtsBY=,tag:DCuU7SPHM/E0V7h+kM0JLA==,type:str]
    DOT: ENC[AES256_GCM,data:uK58,iv:e4Dp1gGT1o8q3bpJIHMeu07GXLiwqc3QY4Fvvo84jwA=,tag:QHNM4eYkWeoKOD9gwposJg==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:kZpILVTeE5DyWyU=,iv:g+AXDoTDp9zhezkwUfaDqcKJ/WwgkwxUicjlxPIWp2k=,tag:6xWAkD2Um+ARv7svRcFxCA==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:SV4C+i0oRTi2Gw==,iv:cE4VLcdhZzBlndQmZNGmLyB5f5DaxnfP2TDx2kXGjfg=,tag:tg8LWc6/GlrBClbhmqnupg==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:VAfPg1gJhGM=,iv:FI681rlE6ZMesblzbBBCHiASrhr8Qc1AanyMw2i9z6k=,tag:8Chvlw6MkGHfHUhOkNC6uA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:EpVwmuMmQ7BQ,iv:L7nt2WOSjOz7icfA7UqLfICD5r60GZd9p41JuL0ieoo=,tag:UzTtrnTMFxrm/2oAxNhB7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5akdqN29ZSXdwNVlnYmpx
            VWtCcHQ5S2RhZXA3a1A1Qks4S2VmazBiODBjCkM4dUVhOVNIbVIxTzFUMzk5T1B0
            RDBuQmJmQWYvbnF2V0dwT20rVCt6Nk0KLS0tIHpwN3A5TmsyTGpxQ3MxMVVqbUd1
            dkVwSnR2dHJZZkthTWx3SDBic25KMk0Kcr/t/7FgCW9mucckuBF1v130PrYoXiw6
            GUOdgZ5BBLnCGbjCTPLl1fUxTVYwvGbfp/q+I1cWKPOF5vBw3Uf+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T01:23:28Z"
    mac: ENC[AES256_GCM,data:lTChDYIXWfuiMQttSzMJKsMBtp/75KMsZseo13NxJYtvQhoU3f5EmreK6RkEIdSacljVc3DPPKOALX7/tEpoZLXee737Os6/2GoT65i50zo9kzAnoa1iYus+zNhhXI3H6OxcHJn5DDOHj4tQBZWGDfNIPXNkSxh0pNN/UPwwBKc=,iv:pqdBBj5DfwNqqDknnsS8E/tl1AAQggQko86A703MesE=,tag:lvV1U1UXNYRhGia2hrGKYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
