apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-secret
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:u7ncCPj1qA==,iv:5qdYBDGdAJ+QTX56Q6pLhAe3Uwj2GbPj5GzHqYLjZLQ=,tag:IL/jN/HJMRnovrAY6SV57A==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:qtXDwVzBnLJ3pIl2OVQuPcilUdXVztM=,iv:qOhc7B78Qa7ifF6HaUrwkhjri7IKUt2qL8Zkajvmubw=,tag:fYOLw7/baAtEWF5RzwFMvA==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:V51o,iv:OX1KQFxZl8kq+5+nHOxO+RNnoGXzYThw8464C92SfPo=,tag:98gAblN58q5JsxX8b1a08w==,type:str]
    FIREWALL: ENC[AES256_GCM,data:xJQd,iv:1qwPTUyU79GhliNp0X9Z/Wc9itrhCoDvxASscWGzmvc=,tag:ExAnr3xGHLzCJMgz7wjAhw==,type:str]
    DOT: ENC[AES256_GCM,data:uRuz,iv:FICjP3OvjKCouS4CHDBiRFvu1X22l2NS6hczllsSoFg=,tag:mYJskca7B8YJ6qRss12YnA==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:NFHb4GRsSoOT7iY=,iv:SpPls/QNzbptUu8pS/JwyBCX2Z2Wfe8N/+FGPwjS1wY=,tag:AfACGrIxVaqgFWP0aSiGVw==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:Z++rSGgQtoyU8w==,iv:fjyQKCPMXwaJKY+iyW23X8ZU63e6bl1kVbVD1Vhkn5k=,tag:+DOba3+euGk+TbkHbN0ggQ==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:v5jvcazGxlI=,iv:H1y3mx7lNJ6XunZSh1t0YJ29fTtZQVm5dkzf3mECxak=,tag:ZfKHEwWvRBVeNOKDe//mHA==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:6fUwX20UNQwG,iv:1Wp8MamwJkD6pnYmrArBT4OE+vPvWkGG+AdwVsM9+M8=,tag:tsKVCfrU2i+Krv7Cyd1aPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK0FBT0dkbXQ1SjRCdkpR
            UWtOczZNTjVsVGR3Lzc5OTNkWC9zSVJSQWxZClVTNzVGRU9Zd1dlbVM0elNlNWVD
            cW1wbHR0NStOK2pDME5sZWoycHlndDAKLS0tIEdDQ0lJcC95a3NYbDQ5OFpPK0wr
            aFhnUjhmOTJaL2t1OXZQVk45RVBLaUEKvTgl54ibZXEYp9qzJrrvs4NRVzDhxuYl
            HzOPWBLbr8ioqqKxRcHzZXfzGL+Z9TeIVOQJWF0EwyQDUHSF58CrLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T13:03:07Z"
    mac: ENC[AES256_GCM,data:UYYgCe2QXQ/kUftgXKMYqkYf1/XWXIlXMlNH3M2GT2UeA4/FnDqU7oXhSxAy+TTbzjf9fWQ/4WxfiJP1RMp8UErByx6a9GBfZgju8uffQIkM1Cc6qQbJM1MAsWIgYSTHdtD7Aw/iAK2L6mcagbEk/s62RtoZAv6ZKmNobM+EVTA=,iv:UldTML4A0FNIzaG8ErQsFNt3yvaPRMcihXzpJxsmokw=,tag:Ql/8WLIES4+iXSpMLQVbDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
