apiVersion: v1
kind: Secret
metadata:
    name: vpn-gateway-secret
type: Opaque
stringData:
    VPN_TYPE: ENC[AES256_GCM,data:LUgXRzq+8A==,iv:ArjS94pG1+80UCf2mXP7QHgkZpfEeQCEvwEioReF+kY=,tag:AqAu+VouuGtgWltXnRNe0w==,type:str]
    VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:N4pjmoFgOYFBvFyrlG+RYPpidxywjTo=,iv:a6cHBYT9kmcdOYyneQmJ7B0ugohqmd61zRdEnfLvjBE=,tag:K1KUNyT5ufR5wmy/5CLx/Q==,type:str]
    VPN_INTERFACE: ENC[AES256_GCM,data:XeJSLg==,iv:h8V1RTARdyOOjjggtUkcOERvEhNRxe3zp9ZpERXRFGw=,tag:tzy+hGHm2TH6AIjuDLEIkg==,type:str]
    FIREWALL: ENC[AES256_GCM,data:80Iy,iv:lYID7Sm95UkpgWAVN7qJ7iQk6qTLmtBbcBe7xY4Wvbk=,tag:fAtWfYgty/waxRsBr+amow==,type:str]
    DOT: ENC[AES256_GCM,data:yF/H,iv:cxFs/0S/mGp6MfGz8zresLTKVxQ1OXzyaxjDvtkr3c0=,tag:NlG4Cdy0QvTs+HFaCmrbew==,type:str]
    FIREWALL_VPN_INPUT_PORTS: ENC[AES256_GCM,data:eSFjQU+nkK3a8HA=,iv:PSiQf6d2ivAd/c93o25grfV40cpwa8zLzjEZzobprTY=,tag:dgyNM0G0PWa7O0VGkFjkAw==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:VmezGGWbb32FoA==,iv:z6qLTpAC3GiC9hR6aS29XikXpkt5eHx8Jr4WHGCRfkM=,tag:KEhBiLPBjLtZ/buOlxrigw==,type:str]
    OPENVPN_USER: ENC[AES256_GCM,data:Mow0hcxAsck=,iv:FdpssmzPyNcJS0zwJ/p5E5lbQs0QE4uwfM2Lalc6gS4=,tag:wgAlmBnTqFcZDFqVp0fkfQ==,type:str]
    OPENVPN_PASSWORD: ENC[AES256_GCM,data:YFi9/BnkwAzm,iv:Zd2Wb1S8LQXOWh8KKFQIYEu0C/9SmFAZ3iX2PTAL8BM=,tag:2AtwNm0WUS6QrRXValMyew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3TTA2ZE1YMHZSSGlVREE4
            bkxmRGphSi9VTC9VaG1aMUhzV1lGdXFyT0NjClZDbHBjSU45Q0RVZFJUOXVBTXV6
            RkREaVBLemVRejJieGNyVEd0a0hUaDgKLS0tIC9TcCs0VVdDR2xvMm4ycE94a0Nl
            V1g3L1U3VzhNeGY5VjlwckJGKzRBS1UKBzddvpm6Z9sZoZ4Lyv2aXWgXw6T//tF3
            5DC7fXQruueXy4HrIdKNsKCcL45HqWaIdY193fxH1ClUfwHiXDMDUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T15:15:13Z"
    mac: ENC[AES256_GCM,data:DcRf8uw8Rr/2oyJwNOQNySBN4xXNjhDirdkVL/R/SY/83Jym31oMKm2iNhm8+lbcTHWM8BTGdKn4k8nsHcpN2K/JUUAsmp7R1m7spYjTpYM0UFME5byGN1jwnd4N/pu+raQB2PSpWaTQTorrhzzWkPrERBw+JmIeClLX8luNPL4=,iv:mvygq15RAAv03PubDwgN1MUsGlvBT9gWwQKXzpAoVtA=,tag:Q1KurlpWMrmj2N5A8+ONyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
