apiVersion: v1
kind: Secret
metadata:
    name: sonarr-anime-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:gbuE40vyvi9fgwJiaE5EQo2TEGmotPD4YjJF1CadLJsLiute9KXufECKioWMXtjy5j1A0W1JaJFn/zl94N6ObQ==,iv:VkDxXHCSJE//tWcFHowTE2u5IrW1j9Cv73Gd2PAVH74=,tag:mACqeoiADcSsAg93zlbxwA==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:xiAIzv4IGo4WkiPBA6sz3W4WsS0oObRVRtywhDe3ic0DwJo3ewG+vw==,iv:TSz5JmJAqJ2nEAtXSziGY/iRg9VVhvSIHA3Z/wscAU8=,tag:r2NXHJD3Fvw70/8VgAqYpA==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:UkC2Kg==,iv:h0eYsJvyji9OMA7t3Se0n+H6gltcjlwwM/WsEgi91B4=,tag:PCg3tmGZqr/rJt8ub5I3dg==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:2uvxDkO/I5Hn29Q9,iv:28fIE1cMrqnO0XepolevKRJi7s+Lp82qYTjP0XvJzIo=,tag:N58xked7D5OELILAj+NdjA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:o4ZgD3AXT/s3CyeT5pdSUQAt+2rlts3K,iv:X+PipL7rKOHJcCDfxEvp+Ig8+y/5eM2ruj0u5yreNiI=,tag:pXRjocVyIVeDJqfO4sMK5Q==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:uN+dVrVJmPFWskhRPAempFU=,iv:iWgji68c988+meBQeh8dBh8IqfyQlh3Dm+g3rpoggOA=,tag:Tzt8q3/nfQFF7P4NMY6ECg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:YGhMi1yCPk09Tbq2IskrWic=,iv:eVLGsc/dbZ7JjTtiobeyoP4ihKNThz+EJbvOpZxb1oU=,tag:5I2+YjY6iAEpOCcwy3QDQA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:LW8OPBiKiQGF3FhKkc+8J/3hpJJeMqT6aDuiU8GImv4HIqJKdOkwog==,iv:SDjPdrB/3tbgxa/6E+W6oo79ZFkrXfVjNJxg3ZF62ZU=,tag:KK65axrolYL+ZXsti0FLMg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:h6qZLnWaALaJ+nYN,iv:dRH4yI7vdajkMTH+H7mtmRvJ5sXvFMotjBN+puNYWXY=,tag:84Cq2JbS2EDncQHgMs4+uQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0xHJ5Dk5uynuaduZ72Fc5AZ7aT9orw8N,iv:ORLsRVpKxx2Gr2bfkeUAvoaFSnqYQiRhDOiKFwco2Zs=,tag:KL7truQatQv+cJRnx1NB9w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:SGNYAUmobDx7LHFHpB0HAr455GZrnTVnJgFeAg==,iv:XGaHDjxXAr9BFruqPCbHjnbUPSfPcE504coCqXZENsg=,tag:rFZvYMU8wOiUm18lAAYhTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN3NWemtXbythSE5JZDJM
            M3ByQmthQ0VzcEphVkZMeHZ0ajQ5YmQ4Nld3Ck5XVGYxN0cwQlI3L1hRdEdjbzhY
            cnB4ZGt5UXBvMHp2dkl5ZW1uYVEwTkkKLS0tIHJRUUdzSFdocVR5YWxIRkl4K2l6
            MkVsQ2lQWk9SQXZBL0tvSVRPNWRVbkEKC2P5X3zw2V328ZDQK27uHRGuvO935vkl
            oDGlV29a+yZmdura1G5QnLUeiRX0OPOe8M5/M6PIVjEqiZoU4BqanQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T11:21:29Z"
    mac: ENC[AES256_GCM,data:sq9D45oACGnTI0Wzs1/JkZzE+eY1e8AgQQL1WKpW8mgws+HgOz/JfqzYwOghEqtbZq4kyxMO5FaL/zbL7RtI41EJVgqLAdyZjIxRPNnoF+vnJSDM/khV7BcfevQecIJQma+5lpm0E5D/RkETlnWok4Kaibh/5rXpBasAdROTjqc=,iv:CqDNA8u69gml7pIUTsrh7RMmYcti8xfacxWiOGOD2X0=,tag:K/I5FqedBk96wTZ4EI3J2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
