apiVersion: v1
kind: Secret
metadata:
    name: sonarr-anime-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:xac/IvekQD86UjQyxYLWNVugIw/rXe6apyij4+A6kll82N3SGlPm+5qZ8dnvpyH8dvE2S6eFOHeQKeQYMD1OVA==,iv:QkBu60goE6glWcmbcTyeaAquF0DXI5EajFffVwQ7MAI=,tag:LoEZMAz45U97pA6aQYC0Jg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:745Mo6/K913USrTaBU5MNBxHQUy5qLT6oz2XCGMm10MmtgvDXtO28Q==,iv:1likqXTX7GAIjKc/w+7od59e6IwwZtSNjVwYqdG+PDY=,tag:QheLVL61aqN70y4wKOpFig==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:6GLraw==,iv:x1IbEttELIFWNvIfG7rYfbdM1yYR7HZvBSxUvU0W8k8=,tag:WsGnvMvIkDcBcBpmB1+Seg==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:ntABylXNflHPyx2K,iv:6ma42IdZZutaHOcs7IgFkM1237xIa1a+JalW0RfXX5Q=,tag:487X0qGN1ZAm1lzbRwgRFA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:DNPH0EMLZKBSAPx28lw3+B5D0XMI7YgI,iv:U8fm5ni9ijJ/M+mkfWu7+FXz2TYD2gcR+qnEHeOMogw=,tag:SPtKFNXXzinE+N/75ShvIA==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:BOXl0snxBCRyM0QYYobCb6I=,iv:pHePGmCLZFaJ+RbBEJTsZIDn1GK7MS4vBQ4b+H4nyk8=,tag:W1dJ7/3coVYb/wbJwXEV4g==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:RThZW5HArJ7blOWC9dQzHMI=,iv:AZFXAYUfbuCWBg+qu8D5Er9zQcowPNd7K8B9KNMTm1s=,tag:2rjyIVGcVGl6h2krX2xx4A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:nECd6FuN5lKLzMV5ww900FkRi6/6BQtfVYBK0QfAlM+zS2BYLMOhBw==,iv:uEsrP9H/qZiwT5gkBpR87P9V0K1TccOAQq3XQ97Byxc=,tag:C828kptYixriaLLW3JXcBQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Z5PocXIYFq0j1tzv,iv:Eh2onjPdqS+n4xcATKq1JZYRxA039xR9dhT9UmECEi4=,tag:8RIEN1v+apYIdXwnUoYI4g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:C9BsvMmxOdMLxviq0sLhP4IdAKEgObyb,iv:u/QArzgTcRtrDDh4TSojSSK8dlq5SKeZil6ptpwkeVA=,tag:qV4mvJY7dB2x9bTYLKOqHw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:06lA9NUTVtLCYDZs9+zeLw4c0+iqXwd7BI4Fbg==,iv:bg6WD4QNFoWZKw9cXAFvQyd5xLOJPGnWYOjUYNaXvbs=,tag:+3S6bTfjrwep84AEIy4a3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvbHJ4YUVlQTZld3k1d1Rr
            MFNHaWtlSzFQRklBMW9LMzNXZndpaS9mem1rClpRRG1RaGdKZXd2VVh1S3dobGFY
            MzN2TFF2emVIdkpsZ2pxVHJNMzFuY3MKLS0tIEFWWUpKbXBpNDlvVDcwM2Ixc2Np
            d1EwQXYxSDhmaU9hRHVuOHJhMmhxSTgKXl41c0Yiyqao4Ln94Y8biLil8mzU9emg
            5ov7tUm/XCwKU0nPMe1Y/HdHNs5dOJaTx8WbUNT52MY/RHyHAh4HsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T11:13:26Z"
    mac: ENC[AES256_GCM,data:EOV4fe1Bvsv4Ms3ckIFqVUDpfv1VRNSrhTKIOseYJoia1Iaild47o3ZLgo1IDpJgiU3O5dIlG8+fqdU3295GGtFKto3Ar0LUVrl4HIo2MysWo2rnWNA59934xttAvT/NXiVUgWVSOADgetLZWeMb7bPU5YYJ+Iu2lF8P19YkRjI=,iv:BfxnA1Cyg2OcuL4l4JG8+gUZ8p7X13ZwDjOFFa7KKmo=,tag:By1yzKAispj/qNdkY8fZUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
