apiVersion: v1
kind: Secret
metadata:
    name: sonarr-anime-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:6myK3Gd+LULWziN0blNMxLl7WEPiKqLomqgqWCoVj2IEtaC4GdPil5MEOYGYcG4QvJlonBOa5szuIK55cXBYNw==,iv:9faZPp5C51E6QZ9KQe0HTRDhxYNl96e1ikHsjx106F8=,tag:VM9/JWgs8JNNXt6XSM4ROg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:+vD9KH2lE1VeEJeurE+UkTOiJsDG4qNSxeSi8OnDbGFvQNIGnQ+hBg==,iv:Xa+cc6p9UCfRqZYR70GgSSpi9OETCfuUW43SQEN1dBU=,tag:rqSwTRLmA7VsFSyqYUVx1w==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:v/Gehw==,iv:9blwqUXRA1jZpxrmYjReFsMSFs91AFf1R+yvgLFjTjU=,tag:bc3vX70F3Z/7ijSJlnnKEA==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:mpnYmH4u+QYWOt9B,iv:1iXjCHXJu0hYTSLpudtL8laerEo7fZgUSfcti0/Js9I=,tag:h55FVO6HTRWTEnGu/oJjsg==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:t/6oOwIGMdP/so7S5CPCfdj/n36cGwCV,iv:HV0e6MbpNhWMKYOLs6pmg1Zqk8LKa0Ivu/uXDYqd8Kw=,tag:XaxVLqJiHPhkEMCHhZPwfg==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:/ujxLjZF9GBCced6sC6ND+Q=,iv:iljXlw2Nbce80PdEumP9mu+JFhen/KbV7C6aPMUNMXg=,tag:NO9bHHyIl8L7+COTi+wNGg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:phQj3TIGsRA1Ac/tINBFEko=,iv:35nn7hsoBmaWcTQ3P7W0YGW0sVagyVe6QyKSe8WNCrw=,tag:8+GW5NMG1nM24wu9rJl77w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:JEteiIB4cmlD/KOPcjQbboI85m7HcIq3owayp4NJwge0WuXFN5vd1g==,iv:DiLM6iUKeviQFtJTW3HhQiFlBGABLu/knZ+ETbFPlJg=,tag:a67z5EYJ0QbAPHVZ3VRg1w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:qhTMy/36ogta7QnR,iv:UMtgZCIL0Au6H4i8tkEyh5mb+shh9Z1hAnOsns+XUow=,tag:p/9t/PKCOLQzBdL5HgjTJg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:kOK57CALxwYLDye3CnupONkVN/mYdJgM,iv:KxZ1ymOfVUDdFG+MRa4jKYYWDOpQp+0nBlq5seV/PVc=,tag:66rqYzWNv/GKGDKQRUjgqQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:oCe3kgzzmOfINAF8OnUV1w67+7pSID6wUf/1Mg==,iv:5cfD0F4pDSf80F/1a5Q2BlQ13iBqNmMPB74zjZuird8=,tag:WWW4+gzIu4nd7ApWR2r+4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzajRadjJMaHRxYWxMZjEw
            djJBa1FkNFRrYWtiS1FnditEVGdTK1p4d2lVCjBZeWtReVdjUHZtb3p3STE3eGx0
            SXVzZkdXMndsSXhYd1NZWFA3NTltMTgKLS0tIGVlek9KK2dkMzJyb0x5SDZUeU5n
            STJldFY0RDRqVnlnYjNwM3c4MVoxRlUKO2hYm26kC2jILV16mSUx3Ofm0ZM/BR10
            WXJTX/dBrO7ohYYcqdADzQP2pD7vTVttRkzt3m/B0QFmkqJIj/8NmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T11:17:49Z"
    mac: ENC[AES256_GCM,data:op3lBGtWaSt4UoWSngw3Hr32Vgc3eor+R+S6GOi0yHUh20gED/piiQ3vMBYPeMQHUxEe/q19vkUGSsobP6k692uLIf+IXkX2viL32e2OP9oWmmk7XR0oAvbCxaq2TeV6WRzElpqIrQm0MDglsNIt63iEdrCkoL6a1lvaGmnQeEs=,iv:q+t1OavzIE+PWPU+gIW2Vs81DgVB9ZvbCqjmIKU6Kk4=,tag:oKRraFPd+UNuP3AIALB7yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
