apiVersion: v1
kind: Secret
metadata:
    name: sabznbd-secret
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:WhVH2B0/8EcdTRFhtlUBpWXq3kZ9kCE+iT4fTN56opUOzfwn6tAQWPNUgJL3el8vJMkF0YN1FWOKiApz2xEnxA==,iv:yaN1PpGYGK2lBoCVhJFYihpkKuw09jWLiotYYSm5+1U=,tag:OvVCs+uHSmvFGIIAV2yzzg==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:+9CxdBTZmCSPmex1i2gh5Bnmjy9mgradpRcoXyuiqUb8Svcg48NjwwssMUCwP0JTFufZg5yesc8L7B0lG/pD9g==,iv:4ASr34dvtokIOGOyGRJHnhr+bjueCrR9fJ7yEXRCewU=,tag:xyNuENKZ1iPR+ogDgagHEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUUtEOXJFd1JleDNUQy9S
            MElac09NVDVnaXc4YWFDK2daUnFoemhxYmc0CnpENHhubzJvQmNoL3R2bGdUYmV2
            VEZxMU9lUHViMk5nbVZWOG01enJ6dTAKLS0tIGVQanpqSnlTWnJ0ejRLUGE1RjVI
            K0N2Tnkzd05rSmZkVEN1RnIxQW1KWHMKifCTjMJWjR2nsbbKu2qpe+TbB1DObVWI
            dj/lnrvhH2KGtgxq/BzmOM+zyNp7j8/AdhwVvqNum+TXOQ+/zrf68A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T14:38:57Z"
    mac: ENC[AES256_GCM,data:DOQc27rrQjtk0fewh7xO5vsIiHLt/BONipA//7jooOQR6ebgjRbWxj4uSMy2M0LRiE2+HE2Fw5cGDF7G53ARxTncHRTXmdt6Lfgt4Q5Bu09FM/2lJ/LsX36s3FGDLpZGq8tYxcpUXAHgyQ+86tjkOC+pSlc93JNtzDdvJmzunxs=,iv:FJ50CtOfXFDsXmsRg6EE8qyt9a9JO7JvOB1G/NaSk6c=,tag:lCEOa/wUoy39guWI5nqkkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
