apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:hbjeCCXM8Dobl2d/0+tMuZhE0BMumRKjAZvWHk6zKG8I5TeE3W0kDReksMQvDq903hLcGDLmFUMVbZEOLuqFsw==,iv:WmnMJjz8qtrcWN+3ehyrHM866P0F9sq0w5hBC2TROms=,tag:NougIuHwO3fUtWTUKAFFag==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:ee9j9jSyt1cpHM09k84ee9h+yU80xcuBco2r0Z7wtTPLRNiA6pw/zyIt9/ou3uo1wsUmH6+leYbtT2sxgkk2Fw==,iv:6aavPwAXc24EXh51YCHXOrb0WdOptRDdY+9WKFSw7tk=,tag:OAHYpCT1nrS4zICyw8X6ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETjMxTDlkRmdEc2dabUEw
            SmxpTTllVEpmeThCL1JPcFBoYy9OUUczc2lvClBLa1hSSHRuUElQNVRFK0QzUUJY
            aEljU1RvTnA1Wk02VXJrdStqalFOTTAKLS0tIHBodjBVMHBSalNpVjAxaDdlbTFO
            Q3hJSnBRb0lGK0U0WitoelllY3dUb2MKiZZVyfJ9+/R9VILVvoZFHWMvxraTMsOT
            ZK4Tui9g4Q4LPicyrtYSLF/OUrJT/aRYYtVHPh86R4F+Co13/+F2XQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T11:18:24Z"
    mac: ENC[AES256_GCM,data:k1okbb4P4wDLV8klqV8sWWmvqHxUvnOEWYlpyj0Uk2I7Qx2ChkWhsJLRYMnzFyTKhHy4jYjD+XSXqdJve/ApM1MGmmaMMx11m0s/HqFduN6EDCY3oyExikLwgP38QeIPsEVdbifHKmRPKGmtIv4O1X4WyiKIKXaaFb8ZEXtdZHU=,iv:vKt2DeNMx9TTx/z9eb0n0nen3BaNDXisMUvBU5OS3DA=,tag:8qTq03IdlzwKGgAIjo37Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
