apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-secret
type: Opaque
stringData:
    SABNZBD__API_KEY: ENC[AES256_GCM,data:BMBD5igtvTEwEndZe6LlZBeZhBIGantWMdJ9OiV3oSJI7KL4or8pxzhME6e0bHCOnRt9bnZizcuhkMcCMhN0ng==,iv:W/S7HBPD4osbp1dJ2XQrV1QJ2JnW4EiKuHjYc7JaBZ0=,tag:JcXU36m+zL+Kk78pPsfaAw==,type:str]
    SABNZBD__NZB_KEY: ENC[AES256_GCM,data:nOmfAcaPIiApPtz86Rqab0lvOlHiIG9bZnAimlCMhQeGuH7NEplnUeq9L3XZQh8VFND6mRc2pY5PiyH97RgQ3Q==,iv:c1XLMFPWKS/tIHQpkxEvQetVahCo5q690F+0LSJYyKU=,tag:xv01xUR2m7nGvc6HEF/WqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ1UwbWEvVlpOUXgxU0Zh
            K0JjNk5OS0c0UTc3dXdWYUE5NXpROUpFT0hrCmxhTTZiK05mY1plZlZTWUFGQWJ3
            SXp0dU1mZm9kNXhNZVdvemlaR1I3S1UKLS0tIHVyRldwVGIyZiszSS90aFY0cDIz
            Q1NGL2xiczl3MnlqOWdaVHJXNktiVEkKrruZK02NEQ9N+pP7EWSPlK28I9goRaB5
            R1tvezYQTGyKYIx91BDmhvkPuueifPTA/owmDKjEirmxX2k6ihj9rQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T19:13:09Z"
    mac: ENC[AES256_GCM,data:jP1Z1+oygYxnhOK+f8fli2bodkLvWN2SW5twOTvnYDPJI7LtnwsLQnyO/OugSFFTb/70aaihNNnMNWC+T84wOHhryM96OEsmBYHFYavw5O9R54nHjyEDHaRe3mI9EdaG2QHzg/FXtxVLCY6t8UEju6rv5SKYdxdMYGAs1DpxJg0=,iv:0JPUzBW6f1fiACbV2BuzePXWrgQQ2SmmMKgqp1W8JbA=,tag:MPTEQwd2A6muc8q6fE0VNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
