apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:kjavYxNfXyksPpB5rGxXCUdPo5TiY1k2BOVGo89XuJhEXZay,iv:GB+Kucxcb+zMyV+bVc80OTLH1XS1Pk/J5mhEkB2Lceo=,tag:W0WlIyCYieZKEAfxEwP84g==,type:str]
    credentials.json: ENC[AES256_GCM,data:grUt5f87QfnpGsLAQzuBi0TsKP5BDf42CGoaB5gKYDz06ZCcBxxOcExJTbKcbLcCBUaaOk06qe9NldXiE+J/zum3e5KW+Hfzb+AQIzcZ/ftNQAI6TW5DxUIpG6IoVerBzpfA/RQIdCZlUSSRUxDgDNxKLJbR/B9C3k8zmXCw2YjYCJz80odqc1yUMXjsYsmqoYEutt1eJ9G7dcngileOGOmJkcK5QZONKBirRt0GGQ==,iv:5t9eCLNWlUuv/skn+PbrZuzvqR+w5A8+3W0TcTdOJXQ=,tag:gZBATJcSHF0Z1y4XV413OA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL3NSTjJ5cW5PNEZobExE
            WUFTTC82bkUxa2NGMUptM3BPTGEycTAyakRzCmsyM09tVEVtTjFJSmNZRy90R3Uy
            Sm5lZThyRVBMUVVtbHpLb2c2MWpaaGMKLS0tIDQ3M2d0WS83YTJyZnpyOWRLYURD
            eDQyZy9NM0lLczlHdHdXTFBSNDgyVWMKkzkkaIktbdI4Q/bXHToNReLtrHvNtzva
            fiepIFnX3zgbr/xum8w2uQUInEdaAOxBYD6GSoVOUUICR9euf9zOBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T21:16:23Z"
    mac: ENC[AES256_GCM,data:8YSfh09WwaXhSuHwz0/4B4+ZLwTn1LKUo5ic4AA1j9xYcy+EgCHQ0rqa7bcUWiz3weSta1xiYMOEbNtXCnZQKKVA4IoKVMkYy90ihllRb/DeeAYMGiYPl9C2oY0DULKF9EN0a0FI0oYOhHutTGGGRbrnVoBT6iB52pYuqV+8Xig=,iv:Pdd4DAZ0UozPPsjj0JsEdR1Bvwi78IK3+AJXcyc3DA4=,tag:keJ4pq92+sYCeqn44OcwUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
