apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sk1eGX5185u1+4aTd3//4h3NlLzpIdYfqM8AQP76yyhTNKIq,iv:QtYDcAi6d6DV+tVlkx5nV+pHVa7ZB57cFts3mfdzaXw=,tag:k8CIk0Y/N0UrVs/qxJRQlQ==,type:str]
    credentials.json: ENC[AES256_GCM,data:QJYyVxqwwmpHubOZ27HCjoiPV8je8HrjK68i4WJbAY0rT11GTVBF9sabEWqMYB3FCB6VfENf1YOkoSbtBkkvbOfm/DudWuCVHNhf7Jp+dbU/w6Y6ei9wLu3UikzgkkpIiNwzubUtjUZqP6V8MOpFvW3zn+Q6SMuSF4cmBTraR2JyScrosSosWx1ZbgmaWtYUpI8Wo7KAawHJ3gxEg3d5jOaJcWDZJcdZTFwYTwJ/Pw==,iv:PFRtPWWSZPpBBepk6oqV98FnTw0SzxkSkOukcHiBpqM=,tag:NK6CRiNi8oGr4CiAVvp2nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdm5hUS90dmE5MXBheTM3
            eHpvallETUZzSlJ6VDhuSUdFY3lXeTErZVFVCjEwUjJTeE1ZUmxoK3phVUhtZFZI
            TkFJUVd5MHEvOEZpeUJ4bU13TWNjZW8KLS0tIDBtMDc1M0p3Q3NicGhOMTdhYjB6
            QTVjcEpkNDZ1UVFENUw5TXArT09ZZjQKXOHmhdXQUKfGfySsA9GENnCtTyUorRMB
            50j3ItsW4CUs4R98GbSmMtS5zA72oAWMo9Yc18+u17ETsmc6n9rnrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T12:39:42Z"
    mac: ENC[AES256_GCM,data:cmAMnj9ld2ajec8CYC3gY5rNTSmNM+uIepMGicMGP5K4PaF66PvgwDHEJWY4Pvjw8POTS8YnAa3jAdZwVQLOY143NH5aTubVy5T6wNt74SXrSiL8M+dxQegCEt9sQemildi5p2IenAHLOoBjtgt+YlxEUNR4VxnhRJHpJtc8o/Q=,iv:z3UwVzXXJT3gGRaYpVmq7TGhcGb/naPemrkxqSM86iY=,tag:wY0oIlByHG83Cysu5HKYfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
