apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:7oRrSMY186BjxAcQsMcsUOFTEKk2SjRfLHinHnrXKZlxXyVN,iv:zqHTxlURAqrNtDjf0jHfumKf9wWc+deIPF5cTgsUvfc=,tag:TGSbJmuQy5DyTBDBRs+GGg==,type:str]
    credentials.json: ENC[AES256_GCM,data:jwmXrFCMXAoVlGAgktSUrpmVWKNcD4Hl47b1P24BTuLl6Vifc9TmT6ip/YtnCcDiHH0werBGn+MEOVK927wY1WqGMEjbY5DOdPm4m9ax4ZHqOY2KPNSmL7Xb1FeXq5b8pZog8BpVi5ckvsdJdoYvJQTMpU58u8Z64LklTmw2kbUzs4kzMnJ9cPomMLbLRr6DXg8byrc+//f905D4NtooREphWiPEAR4+bdyK3sH06Q==,iv:OwWORWu+GCYoH57nC0M3UJ3zJtiClCCFB3IEwZGlU9s=,tag:R1OlWf/iJs7m5ZzYRvH0TQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fhykf9jed0ltz2fguu3l9h60xv0m35hk4faqfr4yt397cdw3p9nqeuc5t7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcmJCejJqdmxNUUlNc0hh
            VXlPc3FUOEt1R2dYazk3N3VXaWpvSjFBSmtnCjRuYnZlVElINDdwaDlkUFlRN3FH
            T1BKVGlnc0w3Umt5WUpCeWRGc3lST3MKLS0tIGszWXBtWURUVXVhVWh4dXBRWm85
            bzYzYURYRmtnbWlwWmxTb212UnFlSVUKJCUq2EaisFFMoNx4ja5kUfyZf+nr4i8U
            K3T3qH8pfga5Y6Sc7dv+YOdPYdhY+HKt9ARLTNMHqeOIU91hChvwEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-06T12:41:48Z"
    mac: ENC[AES256_GCM,data:IAiTvK9VlHodBvO7/E8FfmdBHiQQBlmP/V7ubmCsgA7z1Q0uYyi1akWAUyejlLpo8QfY3CTSQLjmWgdAjwvUIm9BV0+r8/QuR9uersh5NPnRnys4Ms5Er4jSu/vgfmk/c47omUmvU60eVcx/HMRd0nt4avYh0f+IGftdJ90SL8M=,iv:VuG8pGNswNUHRs3r8n1QskfHRVJ+ibnOe6zPbkB9PFw=,tag:XhXOoHudZgqZ5p0+16wllw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
