apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:iL0M0Oq9o1RZVyaT+Zo6UURV1R+iFN+lyE6gHmpS3LdUT9LC,iv:cKGMIGdFrt/UZVebfttVU1sRaDB88ntYfULE3gs9+Cc=,tag:4rOD+WHX76yqLy47texTJA==,type:str]
    credentials.json: ENC[AES256_GCM,data:xIKp20nLkVDWrSsXquH1c0f7rcfOKXlIARm0q8oGbraUc9qjPJBxuBtqujF1WIG+YnRmSac3FAo970pfSEoVdgyIrqzfdjsItOMxm/f/LaUbrHWHryZlIZG+GV7WvC1wXwcWPx/Xr0Px5f+t1T/Hb5Iz9OSejA6oI3F0qKDkg1MI3nlfW4RuPryMb8cLPQb8NoABDR9CzdjLao/SC+MQVSj7gliwH6bZ2eVrvEi4Kg==,iv:pgjgnjZWrUhSjfAgx3pYPLwY0m00ztTyUKq33d1Wys8=,tag:7qqdmIqEFIonXGpCCu09VQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1NEJxcGFZTTZXYW9QTDNT
            WEZYamFqeTN5WW5RajhISEl3ajlJUU53RTNJCnNVM3ZzeTNidXJmUm1wTnVTRVpT
            bVN0QU5TcndSWjZSblNlb1BaNG1YdVEKLS0tIGp0eEhTMUZnRnF5d3RGeTZoTlox
            RnZTN1Y4Z1Y4NXlNSTUxSXdJMENqN2sK4QjeyA5bF602tRDCRJ/C9JsGJs2Bh66H
            1pR3oHkmyCZdEGeLb9K1MAbvZNdOg839t4ZcQEKAawFaOjBA5Nm9qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T15:15:14Z"
    mac: ENC[AES256_GCM,data:n6br/aM/1gKLJS8Y+NQm0VVKI2ae1l86pEu9myldA1NdFaLvPNYuQpI2HkaE44dKG6HGwyl3W9GfAL0yvOkQAsEr8fJ23H5F7PdFC4GksiqFEXBWXhtivvnc2qbtMZ+I7ThvaKtDaVY904LdX65pFB55rHlaoeECxhv3vkhaUMs=,iv:lBO3xLyykCBzZoH35DJVxvs9i1M6898xDicnR2Q97uc=,tag:1+jIjfMZc6NTVzwrpJZpmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
