---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  targetNamespace: network
  path: ./kubernetes/apps/network/tailscale-operator/app
  dependsOn:
    - name: external-secrets-stores
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale-operator-config
  namespace: flux-system
spec:
  targetNamespace: network
  path: ./kubernetes/apps/network/tailscale-operator/config
  dependsOn:
    - name: external-secrets-stores
    - name: tailscale-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
