apiVersion: v1
kind: Secret
metadata:
    name: thanos-secret
data:
    BUCKET_NAME: ENC[AES256_GCM,data:EujPoamMeseFPN8jAOpG,iv:V4Ox5d4GFRLEWgxi2iSywtutQey8VO0FMTqiUW1m4Vc=,tag:ZEKKipB7lpbMuQOiKbJR/w==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:Dlv4IqL70MGrkArdIMnS8/lJ8Q==,iv:01KsDsBhCaThrISfPgCI/p0WwfFSYhd0rDx2nxgklwA=,tag:MpOmNBOZ5Krz9JQ69nUFgA==,type:str]
    BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rh6H1XrfOEZLkiQ=,iv:3zt8sIUVOI3rHusFadIGiKuhucpZTyX41KFGlwRC9F8=,tag:BpCvl96s5NIgcQyuWWPFBA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZT996Ti1NdIHlsZRHBSN0sHHZ4tBUtk=,iv:MODX8u3as8IA1hIAwDZaPqQU30QyjSRd5wGmkRDN5TA=,tag:ZhCju8bOw/mdGxC5Y3INVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTWQ4VGdyMWRXK2s5M1d6
            eWM5cVM1NlZzMzJtOXRadGhZOHAwUjdKMlRFCitHVC9tTjY0eHZvNW83a0ZKSE85
            bk5mN3JLcEI5NEEvZHZ0OXNyWVRVMkkKLS0tIFBBMnNMTzFRNnhHQUlXR29sVUNs
            cUNacVlBWjJyQk1LVU1XNWVGNlI4cjQK2aKoBRHcx5E3U4g/BRQIVVA+jREa7lkg
            1ueLOSgLOMnGXPyewfDyLvmSMuuCPXfrtmtLJ/Z5RCynIGGuyyjE4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T20:17:59Z"
    mac: ENC[AES256_GCM,data:WlqanmGlkiRjGi16T1Ym8vkdP7ldd2ITH3HFUINoCZlgSz3msnCqwLfVML3ZFtzNOVH460ru3RZkFV3cbVoMPSOutUu7f0oFXohCYUtcXcDvkK7JhGOhId9XkecWXaIsBwaYoPQUvCXYtWgU55JmYH5OFTvemqSs/ifJ2PzGLBg=,iv:lzW6C2+zNyex6PjahuBpQP4bm7KKokKG30GKtEn9xXQ=,tag:ax3PIoxe+U9yfq43ySFKhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
