apiVersion: v1
kind: Secret
metadata:
    name: thanos-secret
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:rf9qdACs1EvRVo/6mzq/,iv:n75Rs8pA1MYxOavjz4njGVFevqGIttLudcRbi/AlU9E=,tag:h+c7v6AjbbGLwUkTjbfUZg==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:ZxOCO6DUDRJRDlpd8sfArulAVg==,iv:B/xDpEYyRMCfUo2CmHya9y6w5DQ8/oMxrXldVTQxFe8=,tag:NP6K8sB8nBQkoe0FFWKK4Q==,type:str]
    BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:W1Yuf/llq45OExc=,iv:unRAKWZf5Ju9F4YUa4L0tmMJUrpiTWYFWjV4Y2p3pjI=,tag:R8kM8Z0i2O0YBSSiTbbDrQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:nnTwCMQ/wE1ZLKRWaLcsbnntiFh4Bdg=,iv:BVIzVppW9TqE5R8EVa/yyqeFirRNGo9Poh4Yl/MD9zc=,tag:obCtZjFMjQuzkT46ZNV40g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNnFmZm1iWUlEMjR1N3Fl
            b2QrZGNxOFRJdEdpdWlyc0M0Rkx4SW5Ed25FClJLZ0E0QkYyU3hab2lRZldlbE84
            Q1V2RElaMmE0enhWMW9vU0FBN1VLSncKLS0tIDVjWlcxZUxyR2lxcmo3eXprZXNJ
            VUxKdGpkenIxeDY4K3FoOElwRTdaUG8KzyDy49sZZOYTKHHw5ujGP0OYUgwG1RQe
            GhAy16mTO5i1XhJBwGJtQbMm3cEwb9Po/PHsY7d88BY7EvKqJUbBdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T12:06:14Z"
    mac: ENC[AES256_GCM,data:vlp2wYDwUANtqfjXeU4SDvXXHpqgQhVucPPebHGcOgiuuaK4P+9jnfloTQvNxu7Lmf0NB/YtivlhXR/XCDl4D0ivDY/LcUQs5AJK9tP7ChbDE+32cacpQuj3YMQWGZkRUYHhrI2kaKDjVkC2KZ/j6Tp9MMNqg3NNSXV3hwH1IJQ=,iv:f+2L2WpUrvbexAGKNveX1nn/rW7yLPF0t6t39vYO+0o=,tag:0xEBieAGOgzViBueWx7pYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
