apiVersion: v1
kind: Secret
metadata:
    name: thanos-secret
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:DP4HS9spFXwLipsEpmc3,iv:u/ZipEc/EkChCbcY/hwzL15U8wA+uh1lhQdILVSykoY=,tag:Acym5SvaZeI1cLv+1sBPGQ==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:h2s4W3wYD7y8ZBTLiNg2zNRXCw==,iv:n7A1PQjlO7SpdpIGlitOCteHAQG6+EbL3NJdBHNSZo8=,tag:VDClR7d4ej93icJxBJvr4g==,type:str]
    BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7Y0qvYucfRA+ePs=,iv:3S2l810r1WTEz728krl0IE4425TgwbYzi4MGGoLYibM=,tag:TofbuAvtP55Tu/yNWuwiMw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:T14D0/lgdo2n26jVzMjsEJAsNsdDsLA=,iv:P1/NpxnZL2naAO0Br4LhTtJ9FdfeghKMOzUo7nPzhoI=,tag:XTAmgABW3KQGb+huEqJstw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YXAvTUhLaWtJSFVuUU5s
            VzBYelNKc1c1c2FPS0VtYnJ2Q2toYXB6Q2pBCkduN2JmMlE1eHBaYVJCN0pMWkFS
            N1gxVjNkWjl3Q1ltZHk4ZHFsejkwa1UKLS0tIDdoRTE4TFhnL3owZlo2OHRnRGdt
            YkJ6ejRzS1RFU2krekhld2NLdk1TRnMKUi5pztcONVsJ32aJRf82/YAk2kdR81VW
            XIhPz/buwoh3ryvVziv/zOWxMMJ+Kkq+Xk7/eerQKDpcqXYFenKtnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T12:15:33Z"
    mac: ENC[AES256_GCM,data:++dxFnbRTldm6/JjKrFepKmYxU1smpzyOLkRdNfFhcs/neuxITS4Tn3NeRyem6jt3VUflI6dr1dK7w/z3BXF8ud/oN0EadUXM4RIFuN+z1h5ABiXp0iKJM1iRaESDUMmt8yB1R16LYjDAtUtefJWy4DNYjdFocC6lp87fdQagjo=,iv:neA3pNYFXfQvUGqIB/oGQXNwabdv7uamvk48ZpCCUqU=,tag:WKxqcntdYTYpEGWg0pdwlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
