---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app freshrss
  namespace: flux-system
spec:
  targetNamespace: default
  dependsOn:
    - name: cloudnative-pg-cluster
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/freshrss/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: /i/
      VOLSYNC_CAPACITY: 2Gi