---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/qbittorrent-beta
              tag: 4.6.5@sha256:40b6872aaa74bede32bd7e43aa7ba948e6b2d562646b6121beb7b7fdc730d660
            env:
              TZ: America/New_York
              QBITTORRENT__PORT: &port 80
              QBITTORRENT__BT_PORT: &bittorrentPort 50413
              QBT_Application__MemoryWorkingSetLimit: 6000
              QBT_Preferences__WebUI__AlternativeUIEnabled: false
              QBT_Preferences__WebUI__AuthSubnetWhitelistEnabled: true
              QBT_Preferences__WebUI__AuthSubnetWhitelist: |-
                10.0.0.0/8, 192.168.0.0/16
              QBT_Preferences__WebUI__LocalHostAuth: false
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 8Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [10000]
        seccompProfile: { type: RuntimeDefault }
      annotations:
        setGateway: "true"
    service:
      app:
        controller: qbittorrent
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 192.168.107.23
        ports:
          http:
            port: *port
          bittorrent:
            enabled: true
            port: *bittorrentPort
            protocol: TCP
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.tansanrao.net
        className: internal
        hosts:
          - host: qb.tansanrao.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: qbittorrent
      media:
        enabled: true
        existingClaim: mediastore-pvc
        globalMounts:
        - path: /mediastore