apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:h1sgtxFr7+7jwHGs4Yn4zQlLpW79vXEeabm72+eMF9KeYqU8NXTfruxvILjUzp1q4JSf2L4fMHiVyTsliRPJdg==,iv:LVOwS0GJ8MXgH6oMdwCIcuIWqblq0bPh4ryVjG+wn00=,tag:PZzj7TTgO2n8ftD3QUIWlA==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:n84TDFUDHEHnr+Jx1j75I4psuOGq5gVLqThlCrky3JIDMGPlrhSNoliy2NhHYRk9PGQVE1hGDZKnjhhqFlPqtQ==,iv:zNkynPgcaQpZWCqF3KXOuNSYU7p0mOXq7NUjI8qNO38=,tag:TzXnkLIqwePbIWOmA6QYpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDenQ5dDE4MDYrTDNWdEYx
            YWxiZWFSNmVUKzZqUHVYZlBzZEV3MS9ZdmxBCjhUZW9qZGFZRGJMdUw1aDN0THlo
            R1lqck84YW5LS3h5TllQbGtMRXRNNjQKLS0tIEh2RWlQYlFsRk54TnY5VVJVQ3FG
            M1Y2cDRGRmI3N2dqT3lyMEtaL3lqSmMKiVrhV9L7qEA/HmnkMuT4JHg02ma9hJ3Q
            mEzSApqIpKm/f9I9eIoOCkx+sj31Mt4vkvsnZWk7PUSCIWC1Wb/C3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T22:49:22Z"
    mac: ENC[AES256_GCM,data:g0HZZan622+MbBDmyQARobFerKWhEwWc2Ei7oYOoL8f8i5w0Z56YP+jFNKwEuRbcxKIgL/y53OPbxMUw2OiITEFbAAWfarxN95+UVZbBsqLikVeM5LiIdBGGwTLrdlvO07v5WK7R+3p1keTx6dQ3SSeRQV/Y3KQCi/M7M5o/eno=,iv:Tfpypiqc6kIfLM+kRPS5Yc23I/klil4QJsLIj2TlblY=,tag:JH7jGWE7bu5e6vYw1aZMBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
