apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:fuh/tomR+x5cuy9DIzAaTC3s9q5193S1Xjd83iSM1nDJyUioT2aYvKwlauOePiq2P+PXj7MUExc8bUek2MkliQ==,iv:Kkb+OPbrPwFFh7OoilMK7DDrAHWTth7c3kW/m+cGZrU=,tag:XeSMcojp8L+Fe3v9jWY8Vw==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:hE0mAHVRh550Jbv4gySR6YW37RGa0HomPonb2doALe0Egv5wtsvkFu5IG8vJvV9/f2mXRJ8vL+tXelB1/ZQazA==,iv:tq97INz4EOfh0AbpKBXxRjgZtXJHKRuP2SG/yqGB+xA=,tag:+5R/GX120gVdYxdy/MZ+QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cnRiQkxyVEM3K0ZuT1ZT
            emVWLy84dElPbmVMdFdzYzBYak51b2Z1bGpNCmxmQU1YOTNCVnI4ZlROOTdnZ0l5
            cVNWRWREWjkzR0t5TW5TYit0ak9JS3cKLS0tIHc2NzVQd0RHY2I0M0NmcFU4TFhi
            bThLQTgyOExCbmJaTFM5SkxXU2JYUnMK4gbLWeM/XPMKLnY0egfmT1dV9kewxrg7
            dCtj4nwfOo0hCJinahvAsNw87rbWW01fbku023r6QooXtidskr8ZoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T12:12:22Z"
    mac: ENC[AES256_GCM,data:5jUPYqZzIGQOqeSzXDv0gYRG/hEb1h8QUSYVye7WqpkEVu9ORic8+kXTzGySIcop+afa5Q0QTQ/PxmaS/AvBSMJxLgJpkQYqo6pSb9KdcGJu3jZtFKAk8DRB3+A6k9HjshwDI9rWcw5z96bVW1LDEwhxd+adhOqaW6meCcOW4+8=,iv:TcGO3pg0qvw/ZzlAjYm5tyCVshMYpOZNrDhgljMAY/E=,tag:0zUQlucYf1n3Z1VSndQeNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
