apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:b2ER4+wM7VzCZGc/8QXBvvXuV4NQdejstRVuj8K6RcHh7IEgKCB2ERPcHMx7zJlhBNx76TQ9C6wJqR4o2WjpjQ==,iv:X0Cz+T4ybUESGdnjvlBpSa64isQLxgDsBBh7kfuZoZ0=,tag:P7KFToLC4ds4sQn7TUkT/w==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:tQ3nhXEAGMxAU3+lIykyNMBYWGX4LujM6+Dtw7M7qF28nFeHFrAa7CJj8ANn8ZAjPqUzKvSQM9NQtarIrCvGYQ==,iv:2PvkOEb2niJqE7u7CBxqQXBsG08feqnHE/lEFGZfsbo=,tag:b/SkDtV1i6ETQYcuxOySWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMlc4TFM3TzFleTVKNGF1
            cTlxL0wram16L2ZDUTd6Y1NZU0V1NElPVEM0ClBFS2s1Q01YeGs0UUJHdnN0MExP
            RmpjNnlaKzZucGVtQW5WWUdxaktMOEkKLS0tIHNuNkx6S3N6ZHV2cVJtZ3N0K0dQ
            a0VZS1FjMEp0VXFwZmk3VEVOL28vMmcKA7Iz1HIZ6455UEXRLbLFyeHM9jBpmXTl
            FiBT7lL+ERhOoOpLw1f+vOiKsRuRxjjFHiNmBMTtWZzgh1mvj6BFeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:10:39Z"
    mac: ENC[AES256_GCM,data:QyhYGepx0CoO84hVbyTzdmIOmT2iJixOG4I3E4UVy4s+EKpdskXW+AxRBHkZPHh5hrCZK7Uv7K5iLwkCw2rv+pPNooya0LRbp+pe6YQBp55uNOwEK3s4gjZB9oyHuP5I2bTcb6l6gj/B/EX3PeQHv83GocJ7rNXkhI0HmzmPp+Y=,iv:rO5R3v69W7Ewamntt6H82u+qdVpVVtxbHx5wjZ14V0k=,tag:kwB1eu/aAxZWlYwlqpT3dg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
