apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GF_DATABASE_NAME: ENC[AES256_GCM,data:eEfoXmEsTw==,iv:ahXk/hjn4z2jc8r4rDOWisMzxVPyhpH6nkeIgusHTQw=,tag:WHzHP2hnaE17VFd/3Is/kQ==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:vqwC1Ua3nXnoveUoDnT05crD/wf9sDy/pft36Z7dAp4JoLbyFkRQIp8uiYTl,iv:0x5gizvAKnHU0mDNywCOLMHrZ9hz22a2HVXhGu7WREA=,tag:kNEOUUk4+ZQKNBLwVEdUxw==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:cEs8PvifqQ==,iv:EpNwzHAm40BeY0E7j9r6WZ6JYFFejQ5WzamhZ+sq5qs=,tag:RPqdFgrlZXNv0Pu49P6QrQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:VcVovzhAV3SDU4K3IzQ8XMbWf5N6ZTj+LT0=,iv:PJx9IYyEsIwUTak6ssFIy5qYNAbGNlT4ioVDvDCAW4o=,tag:afrYN5uu+mQqYmomGF8oWg==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:Hn/rPf6Nxg==,iv:oRP+bkA6X6nL4GaxUQhtAzYT3DUBvj3l5JsmrgdzOUM=,tag:cr/M3upQV57OPJcHCPiU5A==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:zExDxKI1jvc=,iv:NnbhYujhKR2zw7FrD3vfM8uT8FMzzwFX45Urj5+YKmM=,tag:/7FEop12wDj9nlXBBX+DKQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:kgh/UmLI5i/dsHGvPs2a/0nlJ+AA3dNESMeNIZEasuKFCI2tPCbZIqreSHN+EIPv52Nt9lazEiouy4TLtwQShg==,iv:mCGsZ2+l02s73NFT8pZDKNVZ2jUGAGT/Pp59YXD+47o=,tag:xHfToj7ADqURRrsrryzz/w==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:HSfa7uGkGg==,iv:sOnUV3wU7e9Unby2FuMqwL06vZbDW1mFTGvmobxJY4g=,tag:FPNhLZil98Agwh+cd+QaYw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Y9VuEwBfOBhajIPsurkQfMxTcuVzzusjBwmhhfxu6rD17jAp2N72PQ==,iv:B+5Fd7haRuUDmH7C+il5AcoHZKtyrmYbdbqILzSBNw4=,tag:F2Dqjy7XHIxVD/rDRlhibg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:vi1OJVMsmw==,iv:hBDcD+hd57tsiVs/slkdU3NQUUcTNqmQylxRMVRafO4=,tag:6JX66Bt5Xyux1fKJ6Q81uw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:7zCZiAXM/qXNSqh9k4TKoRD66fMHLGRywwI=,iv:BKO+8hSmuht/i7zyZtd87v9MhffcdfuaVdS95RVI5KI=,tag:MRJqGMOdUZNau+m8kJ8Eow==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:/LObgVwJbm555qLoMR2zrk3wlOIKT5abanyEpQ==,iv:1SwP99AvQAVievfUBgzPdDN5I9+ZwOMhsyzQ7aVGT3g=,tag:Wunt5mfwrfmmg4zdYbB9rQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ1EvK0tYVDdYL0NnOXVn
            S2NPalNBNGlTb012cFpiN2JYMnZGeXVHUTIwCndkU1VIMFo3cFpwR1VpaGRqVkdl
            YjFGMzlhMWpJeE04bjU1WjZjY2lxZ28KLS0tIHNhZXEvNk5hOERtU2NVZkFOUStm
            QkJneGpPamdoYmNaRUtkMDIyVzBPU2sK+VT2HMSenDMLdWckvj2/q+VyHNXlkgC4
            0Pj67MLoTIwpdsTds3MW2bNCMkjxsFxzRoaywKfqJ+LIsW7uUSXrmw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T13:16:23Z"
    mac: ENC[AES256_GCM,data:pINAb5E4gCncX6yk0DsSCGiphE1Op5Kb/1cRJ9o/rElngLsX/kFQ1YH8mfa4arGoHzjQyRHB3ldUKz5xWZiOl4+M9qVIjkPu2rSvxD97cy3Nj8cso4dRNs96eRM7JDzAq84h60NkW7PhHOGiYavNLTwtWBzkJQiwSQz6opi9cII=,iv:hSBXhyMDOmOAzEWp2rd1vpeZNUZEWvErnYuPlHGCHUM=,tag:aMBMQ+TDF/422vpdnINYwQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
