apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GF_DATABASE_NAME: ENC[AES256_GCM,data:34Y+p5QpZg==,iv:n4v4+1TX+H7GpfTE6HQqHX0+2MTyG2XBH/q/Yz6DtoA=,tag:+z2MnPh3B9NTiQcF62Islw==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:DJODTkcOwM+DngS386R5fKtTP9tRSPXDv4dOk2o1kRQhg1xGlqp8Xq1VLRVj,iv:gntIYgo3NkVM7P+5359ml1G0wkW2fbZoryQpQMFUGe4=,tag:Jf1Hc5X/mXOyP5Gid19Xgw==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:4ShEUezb4A==,iv:hCNKNqa9a8hvP29oJpY/ickigq5eMrSYkSZEjMc0ceY=,tag:EKubJLjdT1BS25CeSvsdRQ==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:BkyTUdl9N0XHKHmovQXUNUzT8wAA6hF423Q=,iv:APbFaFRyhKZMQWj5Agg0k+4Lo3NUuaZmYz4RF84nZfg=,tag:+1911pkoIP7MBgGlNjtHfw==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:5BxeyiSTvg==,iv:+ngzpLQ9yjZQvgJdtozb9sAaXou8xOs92618OoR8UUY=,tag:IlgXtYcN3sKQyws0bklyCw==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:/e2XTXSL8iI=,iv:SWNWs8Qo/VQ206pfqn8WcDt0hvhNS+AOmwPYRkH9tBU=,tag:50rZGE9qNddXIKSXdr8GVQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:8kBtXBvNDdiwuvfTk5X/HQhs2QKt24owEl5X17/C+cwY7tZmX5NOWhj5oVNqR/UjyyvN5wJ7EJcYTcStw81wRg==,iv:213m/yT0lJrVTh342gQXIBM7weYbIWEyq4vsLkErm9c=,tag:ojWZCC2zsguySH/nYygiIg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Y6H0x4E1kg==,iv:4vZaZ0c3Go/XPd/Aleh9B2qMiUCvjLT33YysaSWBmGM=,tag:1duoWGkJ/t9YqPzI1WG6/g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:mHiYqu1MZ3yEv4tm7LYSGF5bPZkDpb2Q1W9VjeoxaxMduM/d/6NS9g==,iv:hn3m1x87/SsQZzgHxeFvPjwAq0Vny5QJRzolv2qEQu0=,tag:pch/IkBluJbis4K1oZYPfQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:nVapCtJOvw==,iv:DOOe6VVI0br9h8phAtZtqFi9c1eumDGZp3LHziewx88=,tag:vZEPZQ8MQOxubVSpccndfA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:pyzsb2eyoAxTLWa0IC1dtntE46Sj7e0/avE=,iv:1mpMHJNNGzxScpNwLY5XLlt9oaPhdRJvBCC2XKR8Ujo=,tag:EqHPTBh75VZXpy5FYNwUAA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Hb6Hp2SAgV7wNUcGW0gweZqwdB78re6uDF74OA==,iv:LNPc/oj2pRmb2ag1K40dn4vwoEqkYsjxFgyhcXR/RRM=,tag:MgsUdPjG+AR0Max/OuB+EA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTDI1NUNqanl6azBNY2k3
            bW9kS0lGZnhDTkVXdE1XQVhpSU5oVzNGSWc0ClFtcGN5U05zdjMxd1dLUDBzRFNn
            d3hZampxR2dENVNsVjdtL2hCejU3NVUKLS0tIEVoaERybmE3ZFhhMTI5L3ZPWVZ0
            dTVpWHZlWVV0dWFPN0s3SEF1YVdjNXMKzcmJId5A53hKFaXLavEfc+jf6bIR3lZ/
            S5KNIOwtD2SLCrI1f/KIURMHXnbMiKD3VZM1eBxhUbue+YFfeyzHOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:10:39Z"
    mac: ENC[AES256_GCM,data:DGbn9XI6E3YShnSGTbmLFNafBYoIX8x22NpKEk1nfBD4Z+pecbHiGtb5GdGR7kBw8ASda5ujHB0sq1mTn55Mj3UPuDPIZPZvcRVGRds74IDyCK2/ZfXlCXYDF4/cnY0PEVpIyil03kV/IfY7Dv9irbKVRKlVGurelGPUFUEL3T0=,iv:YXzQ7CfI3RlWJFxvP6bJftS4fkx0XoYbAFvJCjdIxbc=,tag:b3oA9NXMhzzU/2g5whpD+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
