apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
stringData:
    GF_DATABASE_NAME: ENC[AES256_GCM,data:PsIJCPT3EQ==,iv:BcZ0nqeUXAxbOM0v/CEmUPiWnIRl5666/xGpjns8JO0=,tag:JdCAupRLigg1z0qwxNaUCA==,type:str]
    GF_DATABASE_HOST: ENC[AES256_GCM,data:EhjFbuxqrhDwlPizTnS4y1TcJ7WjiyOiFSNfz9TnS1RiH3rI+dwqXQ63qaWy,iv:8RDbnAqC/stPF0/lHqLJiZjMyZXllYWfQUQr1RS+d/E=,tag:u5kM3QuGZqhbOY5RAkZexw==,type:str]
    GF_DATABASE_USER: ENC[AES256_GCM,data:sg0MkkKDiQ==,iv:JNhhLcY1eYW7ePWwiGZN1ahM/aNG9d+y6AOwmoQ8qe4=,tag:f+5fjcg/+WChmEvj8vhZWw==,type:str]
    GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:cSn7xIh9MaSinFDVKyq3VTJpadkGP8JvSFE=,iv:QN0sjN0a6yndjKOllVeSGUJ3Kp930do6Ni4Thzgn3qs=,tag:VJd5XD7NW1V8zg44nxncCg==,type:str]
    GF_DATABASE_SSL_MODE: ENC[AES256_GCM,data:+wMltIPv1g==,iv:tw7U/yn7Un7mr0vQBUuR19pfGxOV+eLvfVAsxTTZD+I=,tag:AA7XEFicNwjUQmYB7AoOlg==,type:str]
    GF_DATABASE_TYPE: ENC[AES256_GCM,data:eNzfB19BOgA=,iv:i7nG6F6+OCl450sMHIeTyxypIwnOgEEuN6XGOebxcVg=,tag:pSCnuKX7GlSFJIXULyhO/Q==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:lZsaAcD8k8bwZPoRNGvmVAEoTCGIGU+SW5v1EZtobEDSZv+8RPH8tOaKsaPeXCtJTQ4TIbYLcA+4McfZKs3f0A==,iv:VVZXOMSMq3AxjDuPmeBtw52LX20QxbqrsAPyPwB9NlQ=,tag:5p5FrnyWNfrNXSDr+n8NJw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Xa3yKBPQYA==,iv:OIpjn9RK7co46VurRXUA8swamMKNumScDNvIxEpRSB0=,tag:BEsfrabwyrCW3P+8Xr/ziQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:TeSQDHVDDN3UQTZDLDZDiggDVCRMcQQzQhXfsjYvfALguA2S9f4HoQ==,iv:RakOZEJx8cyh7dUQjhOIfN8oTtxs9bArvER57mFG09I=,tag:HzejBqE32kiDW2HgNJEB1Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:FpS+E2vxtQ==,iv:+4Ev/wiPKdyxpPMtULMvzp7XNWx2X09WL6LOZxRTNV0=,tag:byB+Gx08hi/foZEKPoYU1w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:PaEaNm6WV6pTv9HlDFrh3u8fSQPsPLj7pkw=,iv:nOhbG03x7q2g6pB03yEzt8i+VVebCT2Y69hsazNVEOE=,tag:i+QxKXOluQU57hsRljBvEQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:irj5hbrJKox6aAJ6nG+JCN9+f+fWhjx2gxXpVg==,iv:M7fJKNwvqBgGOVUsN2oXaE33w6lx4NtobhMRHVXfQmA=,tag:qNNPik7+7I/xDGSkh7HNaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByM0gyY0JObmxFTWIvMGZk
            Ykk0MUk1VEZ1SXlkUnRDZjhMZFJzY0dXVTNzCjhhZDcvUnFkTDVzK2xnUmZaTTlz
            Z1IyTEN4cTdrNFVHaWRqUW5WeklSR0UKLS0tIE9zR2x4YlNUS2JMaDdCbU1GVkdk
            Mk9BdnBxZk4yZlZ1V3JVR1FCQU5aNVUKoHNNslKYAwwcb58s2W/O/31X5n/19GeL
            rQbwdTv31bQzmUMyXPV39oqu+onQoNAs2fA9TPK5SKvl5AH0QeBhzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T13:38:59Z"
    mac: ENC[AES256_GCM,data:6wSX8f4ynn0ba0VRIiOx58lcjXkCcKlYeGYI/CjldNDLe2PD1M7a0McEQpie0nPZaA2YxbVoTSjBm4thmDqTv+ezMzsCXp38R6K2WVbFo29S40LLjSsyUVppisgVomiYYNEmmdFj2UZNSNwK3/+Pm1sL0JGnbhjDh7UHpVEabRI=,iv:QTS1CuGLhJsaEEWxZ1BOFEs/iibCpzud9ZM/nRmf2Z4=,tag:BKc+Gf6ChL7DLpfGkZQulA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
