apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:sPSGjejtG/1a00SMsamsUM7dsvatWWrci7+ADd7uVz2eP2qbiAb/jnhbQfS6jpVjOzaOhUw/JQeqfqos2LNBIw==,iv:AXBx007E+loMnWuHQvmfi+gETuYalqC7120WM1GTjLQ=,tag:Pz4P1iKeW4YoxGaqUw0cUg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:zPaOcQsj7zp9JtPSuPUAd/kiYyTbs5z8XCf1VtwgC8lODcak+IT1Nw==,iv:mvehzzB+eH+nQdCYUtxbRSb88Y0139DNmD8I5qx9R4U=,tag:QDkWRqnvEscWk3JX7nM/0Q==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:JBiZag==,iv:WR5kIwNIYpt3d9lizwHvcN7snR9xCfj3U7ZTyLLopjU=,tag:gSlSL59xgXs+2zXIWS1h0w==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:gDM/nTJg,iv:6i2e6+/cEex3XEYQex8lNXnmnnmpRfce5r0fISahCMk=,tag:iFciWUOKpG4TYr+1Uxlj/w==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:a1M51TJ6D406+5S5NECT4LZk2Ui8+H/h,iv:jQUC2uteScMIj68GrZOqAzNN5Bkl7QbdmzuVru6p+Ic=,tag:/PUHFMED/YkuW1QO4EVayw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:vL/TBTdL/IaLy74=,iv:hvUIX0u+4+hZhfWhb+ClBdT5WeLleAwnZ1c7EKmaSag=,tag:0vFS9BEwR+d3eC7IGDys+A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:IOhor+009fyy0w0=,iv:bdT0VdgqaXJ3aXM/AVoefKxEil6viu6bmXDfcmIRtgo=,tag:MvUpJa2NpVW81Ny2eYfeUQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:dtISZBxrxWngAG8+rlcIgpifHSFG91EMryqil8ZyBatKVgqrLUAtAg==,iv:lsNogUATwaIfHUJY5Vm6jbW3mjKxGk1O6LQ3PQ2BLZ0=,tag:2pBB/F4mGX7InzOl4j4bdw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:0HHA6TKL,iv:5MkpEY9/2J+x3JhZfRh6nVBHdb0HGwqE7onExX6saDs=,tag:KClFusT9gHmXHIJUsfY2Bw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:vvweKoo4txtyEfMBJr5ENKLlOa6XEWlI,iv:7GnjDgzVQrjKg4Tw7zKmMWEvkrket/m3kf6piRWbNyM=,tag:BiCcrmgXoGXm5UJ1RUzrrg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:H68J5aRXccNM03vNEO3vXFn1kzXo2gIaxYEGRQ==,iv:NVR4covku8r+JzAuMKJ6mngiJnvrxxpktw5bgBCcmDM=,tag:W7IZVWbEdJzZQr7CWFBYZw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZzIzRjNSMFFkeTg0Y0Na
            eWRPRWprQTUwZWVyZG1nWGNmWkdrN1BnR2l3Ck1aNlhic21GSnM5RmpXbWg4WmFs
            M1R5aGtwMFpCRU1WbzgvT01tMnJDQ1EKLS0tIGNucHB4cUhzUXNJcEdiRy9YMThw
            cVhIUXFjeTRnRXlhSE5sTlNwMGlIcG8KQgb8FcwQ7zunNphZTXzeJO54BzEkPtFw
            jpGrghR8zJGuilODKQ3tR5rmbB+hGSJX6dbZlfMt4T2Jh0O+fp57ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T21:22:59Z"
    mac: ENC[AES256_GCM,data:BP1gHW6B7RzogmNiQrqZ5DVwUjSZJpDfum2PJ+Cj32Z6Z9RLuf3bA5Fy5LLrvXpJ9awZRD9l6SIJNpTmTtdaT2KtafvUufs1uS7BBZF56bQi4IU21QaUQ0QdcOJLoR4+12QgUgyMieIzwcyCW69u+imLhXXBQ8lIEnYvgEehqGM=,iv:H3KNJAJSR0p76fsFL7wQtP4OMlUFa593rB9U5zYuep0=,tag:fMoFDxouRdKPktw+pQ62Yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
