apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:KqJ5dmdKM92auYQUMj6TzblulWbl6KcIURN3EhoLYN4PTPibjTfNa82qws58KOhyvNcU+N49mt9yNj6Vva2g7w==,iv:l2FzsZKhT7mwK6aQi0VcwWQuxMWJn/ct57lnUXTMEdY=,tag:qeHrTxwS4PCcU9E0ruNAdg==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:TbmNpNWxAJGIqOmR3dnfWTQQmCthon2NJT2QTxVBjigw3aGeI33Cng==,iv:YtG59vgCFLyvyT7PDqCVY6qglxr3W4BQ76cKl0mx3Ls=,tag:nFRoQEf2aeGi8R8+AqaC9Q==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:U9iIFg==,iv:1ugqXnfP14e8QQkq5FnujUb963kIw1MfWJvBJcoV70E=,tag:1JqkxrdCeozDkcQThsVG0Q==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:b0OEHr+I,iv:dIKSJPJtVqM9fnv+LxS9POcO0jDlxOQ0ZNJKgDWaOpo=,tag:J4SHYUB5Enhsd0t6LqZkuA==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:IBF6MDB2PqDiZGCwrZvRFqH3WkUe4E5U,iv:mJf6M+BvZX0McSg8JwrC1dfOmbM9x5m/Yy9ojzwWFjg=,tag:1PT04BWIn+X+C8q0f0fvOw==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:NXpk6IIbhgGqnRE=,iv:e8j4p5+pqE9MG8CnfqHvBTQxOuPLxAOyvgMPVt8AoAs=,tag:vjow2fmyYsF/Ut+hVrPDqA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:quNU3ck0TNueCtI=,iv:3O/DlKkH9k/UpTgfNOR500TaY125+OFsrV6xn87KI6Q=,tag:tEra4qpEDMbT33oi7hRCsg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:v9UFM4WFbXzIjHQr1q8qwRwXpw4el8vECu9EELW0TelpAk/7H6itkQ==,iv:FsvVTIQ0ma7xmf0Wffk/TCkCL8BJ0eB3yQYI0d7DpHQ=,tag:oU6+S6cw9fcH9my0RHIGCg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:52bm0dE7,iv:CBmTayOwm4pk5cfP4bAqlfy4AwHS07Zmbbj6OpVqh7E=,tag:hIwMe9p/KUY34u+WUEt7ng==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:L5KNXosPqX2Jjfw7OqwNsEx4itr5UJDG,iv:ZBZISnP9+z2k9sfNcDvHaJPQWwNDpXgi6H6/QRgPxpg=,tag:oAo68RmKZAckEGRqAN8Ohg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9DIqiMFT1O5JYz9EIEgsGkM5+tJTB5GqX+20tw==,iv:6LKAlM4YNsZe58qb2AHSefa5rZaTBPJAPWC6rNoI5z4=,tag:w9oMVmnQmT5VTHEZqa3BBA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSlFXdEl0U1lub0JHQ3Fi
            eURubGxLKzlhUUJXQWRFcTd5OE9QaEVwbmpNCkhId3h3YmRkempidXhFZG1xbkgr
            M0JGRHpWcExDR0ExZWRoRStWaUtOZDQKLS0tIHc1cmkvZ2U3RGY3ZlJiSmZ4NVI2
            c2hFRjhNWEZ3MU5PV0FwREhEeTA1V28KNKNw4++3o8Wd62fnNcE57NkJv67sWemt
            yBSgJSGi/qMgitD0qBqUbjhJ9GknWpo0M9wUZa18VWI1nuJnqnBwXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:10:40Z"
    mac: ENC[AES256_GCM,data:eZWBVQuD+aJzkQdS47dFPBIgENDd1LfNdnFJbs/ZslC9dUsbhPwBGTOEEpdEt3S+zPaaCpOSS6dahZRDBiXqELBUXU/k54hro/yU8NSL6CmpmAPQ/DVA0bYv8o9l7iPuqESrSe6RHwBKn5K9sgbIQC+CEASiThXthK0Rzf8XN3c=,iv:iHZcbdCcM9OBlcCo5Tk7y0shyR6lZTFDw3yoxvfaSxs=,tag:3INiTfoah2e39JmP9iarmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
