apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
type: Opaque
stringData:
    SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:SNO7YgsYaEi9aucg3ufwTae/J/0TriRCzxWPLBOKqD1gHnV4fXmUzQOqYwCaa/TwGZVTF0TOST9+N1pQ1VpuUQ==,iv:VvEkG45FXLsoaO7uGTOeYvsZvq62J+lw8J33JcDuvxU=,tag:Hl/doizsBNT0dR7JAlw8Mw==,type:str]
    SONARR__POSTGRES__HOST: ENC[AES256_GCM,data:Z1NPPLat26PCfbDNY/NacEh1AHBWf4CWCyihd9KMkg1tMNnK7uhXxA==,iv:MfRNedkV9UaLpToBjtt0io6Q1ia+ps+h+ajipuQC25U=,tag:n0Y/49HIOx8EjTLcmTktCQ==,type:str]
    SONARR__POSTGRES__PORT: ENC[AES256_GCM,data:cOGIGg==,iv:Rrd1nNW1ztJ0GXWe+TYU2uAd+O1ZrQqyeDJLiUAPHDo=,tag:Ybl2MgfiAGuzCVNE46bIyA==,type:str]
    SONARR__POSTGRES__USER: ENC[AES256_GCM,data:UK55ScTf,iv:fy+kDNu9XxQxGA01RaXA4aNxogrj2i1UmYPtncnF/GE=,tag:BywqI7PcuLCQEK2+6vpH5Q==,type:str]
    SONARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:R+i86fFfPCUm4lBOZww/GQsFzqF2tOFJ,iv:9IDQaj0uUMsliPJYkQRrvmQ1EtiukZ269YfdG8uM9KM=,tag:Ah8iLtJPVk/XvVU08MSyWg==,type:str]
    SONARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:RLYiiRV+W2h8AhM=,iv:eStNeQWkixKKN4aY4/0TynhP5Zf6I9in+MaOXERUjmk=,tag:03SlWykKa0Si4t6AF0IXlA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Y6KunsC0Kv6WjyU=,iv:YH40YCJOZYaWBeM9M9BqyPOux6AVdmYMXzvfEw/xP/0=,tag:XGYxAqhdaOCIZcGf15VT/A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Ozh/kAjuEslPqqdxcssUaPUe23lDKWkboAPEAJq7V2gXl9x8STbAGg==,iv:6L8HAmVGxoS0unTk9VGY9cNMRicY0MZsWKxQ/7Bfz3o=,tag:JV4H6iQfTQBUlY91jOVkhQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:28WR9/j4,iv:EIufsfPeEIyAFNBJ+fT/EkQ9KQ+eEaE2otfVB+AOhFc=,tag://jG7GTFRRV3lNFv0TVSOw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:q24LFhUYw29/bSrfcldTzOBaA/JzNNQf,iv:nTDOqJ++5PKRwtUTqc2r5ovN1FTCxtscLuVmTEJQ6yI=,tag:CC2WCLuIluxtlpAz1b+deQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:hEUL6f0WgoElOc85Nwvb07q7FUO19apWaaFajA==,iv:cS2TXxtgC4B+Phs5NfjavjNLvBQ0e1w2NMFTGqT6MFg=,tag:0gs6Q2RtVeaqoQ21Go+ZLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbFpOV2JQNWtZZFR4RVVT
            cU13enJYc2sxT090eUdBb0FFcXVraG45RGw0CjE0dWtaaCt5eXV2aEtJT0pLRENF
            QjZsYmJudDJzLzdhQ0FUTG5kbXpVZlkKLS0tIFJBSkZxZnZ6MS9UVmF4M2J0KzJo
            RStzWXU3YjVjbmtRWDFpcitXSC9GdkEKHu7VJo1xKBFEe/R1/p6vQjygIRDivQ+O
            dSo7V9aBjciio9J3xVVtfY90RFGbFSIRPyIz1csWuV2BDzqR+4wveg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T11:13:26Z"
    mac: ENC[AES256_GCM,data:/voxVyIgejkeBWWRaD9p4lZ0sbZTqv4XyNmdECNb5N6iK6OAxz1zVd26wrstd8i0KzbKHnPUo3XUTLn8OrLDrxhr7EWzQ2rklM47Fx7uLOQFEVpatI4OCuP55N+ggha46Q2B4Espmlgyi0M6Jla9w8SqCwGuqnVOCCJhitT57kk=,iv:t9OgJGBN8Xjit0R3247BDKGui61J8uuXcMd8zOaP+gQ=,tag:cVPFP91JerI1dBmxKdaHtw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
