apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:U9dR86XdTxIGa49oXoJebNxrJPYIlBjT7oaUMPhkq1OxqHAq1x4hlA==,iv:zP2cJ80HOANxmZOaP0Bhav/2+5KhfjrnvhXV3IYYxTM=,tag:litaYz8vOh13w2nmPnzfyQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0M01ES3B6c0Yxb2JMbjVl
            eUxodWZoUXJzM1psQnNNYmxVanBENldOa1RvCkprcUlRYk5zSEVvNjQ4MzYvU2Vs
            MXNzL0YrbWgvZDUzVk1UMG50eUJUZncKLS0tIHFBemQzN0tuL2xRVUkrQjd2ZHpB
            eHpqSUYxY3RweTAyWWJhTmI5eEhLdnMKOTpc2wU7rRnwl/Xt9g1GNqY4cZmRkjiB
            DiqbEzyeChdIF+D9qS328xRdCnyAA2QDLKiQTLjwe7kkF02LCnZyjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T12:15:01Z"
    mac: ENC[AES256_GCM,data:TkMuMSRCef9xJXDaQD6JnmVkCw62iN2JdCOsvbXfUFbBDUOdUvvHSt9WwE+yxtDejhdpYt0462wXqEOA4IzfCZZfWArhkAhN59IVpUPdJmYUSOhatTLLEM++wVjqzpahHcYj1NQVlX3Pt9AFV73AroB1pr5ENVnVgLrxas65VZg=,iv:giA16cSI7hIFXErKWOoa97Ymc8C6/vJZwW77LndmQYI=,tag:75rpARfttIg1Osf7T6IMZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
