apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:9m7g2Rg0ETzPYyQF7sYJsZTMXVbJRTgqg0gyFLCf2vW9rGaezgfy1w==,iv:Oc59+W2aLDLlzQ4V8PoXG+RDAXO3PqX0rHijAcnPll8=,tag:HEI+Qws/EOidt4Idi8izaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMGlBY2dDai9KRTJ1dmQy
            a2s4SFkrT0RvSEo5WDZIZi9Od1ZrVFl3cURzCkF1emZPMkI1dzN0dFJWRHhxMEFw
            NWsxWlZZcU5DY2N2VE8zQ3FNRWpvdUEKLS0tIHJZT1NDYVg2bE9GVStKYm55c1lj
            VE5QSTh0WGdEUHdmNHNBMXRNKzNqcVEKRM/zBTib0346i258eDcYWjRgcgQ6OX17
            szTiJ8ceZW/Ohz0CcP2lJe8DWA7+/W+KdmlEMXnKCAQ0R3QBR2agYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T00:36:42Z"
    mac: ENC[AES256_GCM,data:rQrRZzNrkOig9Zo+VG63jQjKhN8aQNQsqZ005zyocCYKi15nFG8bvaPt729ebQoAuV53gq7rIqLNfqS3pKlULeDIMo59vdY2gm/Hil9PJBs4aGX/JwIlX/L5FE9ivpaSNiE5FZBoyO39gI1Aifpb1voJJ4n9ovCWIgAMNIJz0oM=,iv:fXFL2v8QFJVlChQDhsUvCP83hXSW+aYwb+rJgrquN3A=,tag:Fufo8N5xtyCOvmisih9ZtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
