apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:U3QvLgVjewZy27xRBw4MoLRT9iglc+jjwtzoTneCUPtEJjWRsH8Udg==,iv:06HxBv06vwLDUNV0l8KHHMCiT4YrwH/UfNucM1IabP4=,tag:5MrsriA5t7Zsoc/RZ37X1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeGxoYUxQSXRDZS8rbmdT
            aS90TFR4bVI0L3R2YUFFVlpOc0xITW01UWdzCm0ySUIrcjN6dGxxTW5MZExyRGxo
            SlhoZHpFVWdGeWR3bWtMRkVqRVBWUzgKLS0tIDlPV2pnLzIrRUxvbGJhYVIxeVdi
            SEpMOWpsd0IrWDZScC9USy9tVEk0Mk0KUV10ZNboC6XddpnbqdifxKi4a7HIfBip
            pQe6RB/bi+EhVC3ILOPVwHnjIbymaruxiiypb0jUI3Wa/1ccA053PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T01:10:10Z"
    mac: ENC[AES256_GCM,data:Ol6tx6uHpJYxgpOfhk1RxXva8wVzL9im7ZpPOjiZ5dM9Dp8TQsIKC75bMcfwZhtC3qiKxYwVyytByuWfhmeF2cUZqizOjlQKo0qG8vDDtyOL99u/ODRYuqN3dyxcXRzNEM2Utc5bLNn29eLJe8Vt6+OoWUYwnaP/LKS3yL5FmJQ=,iv:WU+pdfHtFO3uh7fcSXR/MEgoDHNrptuevp5OoDo2jLs=,tag:0PK+qZiLDYRtIzu6l8doVg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
