# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:y3V9Jcz2F1ovlTA99NTu2nZO6oVbEPoR,iv:8I2r/VDDyjGp5Dgz3P0I0g85FbWvKEbl/GBexwyikXU=,tag:ZT+5yE3lkMD3yRVOY+YCKA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:RLxeQZu6rvs3B5zlxpkOwA==,iv:jkqYrQ3HFr9eB6Hw2EnJknO6DeaVt8L+GAVSZarbJtE=,tag:f27AF9JMOV0EyWRjLjZzrQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:8a07d9bPvmsS9UcIKflQf0TIlH9NZ2djjT3e,iv:yD2UAZuvuRAgOM24HIgmWDqEwm8N7uCwQu24/xs3AII=,tag:KQhz2g69Rwtr8MlUxDjccw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:0163GyliFHvjcoo5zXo85jXqUgT43wTgEZqdKZfDW17gvqrg4z5KEBPn6IXmCmS5gb8=,iv:/edcrN0DjhMqa9HwsBqKCl5y+cdzXSB094VIOFH4ZJ8=,tag:FhZ4XBKtMZRfcy4dsvg2Ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVDkrZ1F0Z1pEWE56eE5V
            SkhEZE12MnFOdFBWbDhzSFJHT3RVNWtlYUZ3CjYwaTdibjJzSExrU1R2Z3RVZElU
            bVVsUURvK1laZ25TMlFYbGpvYjh0WWcKLS0tIFRHd2hvaGs4QVV6UkpNZ05XVzYx
            WHpWUXFqU0YxalY2ajZlWWtVb3l1TzAKrTz0zNwf8ZGXrtE2EIcUoEijz8jsuYte
            kK1viAWWFfY6RbT5m7KK6Z9h+9gnaKSUkvw8u2j5/YgBeNXg820dbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T12:39:43Z"
    mac: ENC[AES256_GCM,data:ERAGlJ1XHelRk+EkVE4o4oLKLix2yu5QDAMVXENd7ABq8EZMbzehznyVAIn/WQfE30uZVM1tDPmS8JXRly+1zwHrdS5GZDr0ToWA6frGSWS9gWyhAXfS6UaBkrKdccUx7iwFCtl42vnf7PsPfoU+0QMkdrcz4qcWyWLroepmVBk=,iv:aGZCG+0wwz97q3n2d3BljC74xaxC114TRAOV9HDE3bk=,tag:/Y07U7XC3qSwhNZ96ofeJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
