# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:PDReZhf/piYhNjV3aK84BECYIKSdmmzi,iv:VHLC9WucEFEdGFg+aBdGy5b6UErW6FSWsqAy2AMXB+o=,tag:EuWfaP09V/xBy4G68qoflg==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:WqfM3a/snVlgkEWR++8O7w==,iv:ykIW8CWYEUSkjfPu54v+IV6Atazi1UhwCAw6AuaMNAg=,tag:5WAot85z/caqtA2wjMm3YQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:fj799CW9hUKLIydNcGOqEbxtKYv/v7ZXfbbF,iv:y0VI78/Muoh7WxiYhbyFYXAUvusFKOMdK5dkRcD+7MM=,tag:Gw63WgyAvgATVz+Fpzmkgw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:g7dh/SjWdIQkMWDFSVOAayH5PGmFlU8Y48Ok7l70wipjvaQ2jkFWs8Fx6cm7RKXiAZI=,iv:E9peIBU0zsjPdFK5HUbnWav8eDqKUiNTlO46tbvhYk8=,tag:KyOxNBKhAIRYYaLFZxmPoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxazE5M3JKUktXWVZvWExM
            ODMwRCswaUovV3FPelVKSlUxM0ljVmQ2Vm1zCndtZ3N6Njh4ZHBHd0JUZUxNT1ZD
            Y2d6eVA2V0NHV25iYjN0Umc0UFR0TE0KLS0tIEJmaVZHQlZWYmxZbUZOQ0dEZTFj
            SjdsL1RPcHdrNWhIMlhhcDNqUEtZWTQKYX1L1gg2Qx+xZHVrmTSRlYfZ1rroby3j
            FUugj0ubf7ZraOWIQXfsbHEKTHX7mAnRJwBVQLcJyCM+493+TG3AMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T13:07:47Z"
    mac: ENC[AES256_GCM,data:X5BcvT6tZXAo2N9AUvTBNH33Z1armAzDNOIGmNs2Ukq+/gQkylAp03Chfill3x/u7rzu583KStz7kDY4i/9q9GFNO87dRsHSr2FiQrLQ9r4Cu+ooKItTRdRC2LgkPW1/yTQqoPw47lGFoNXV6Q6hdV6MKHxVPBZrLPNeqEOv/80=,iv:W7onTP1+XNPesFTM9WgKqpAhR1crdOJXuPnEcqMt/mM=,tag:LUvpew3HYi0/7/GYi1jXPA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
