# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:yZhedR+rnpbXx+BFZyZwt17wJgDJhZrO,iv:/u3d2s5RJRpaa/EYMgA0vx8Wc7wOf32GZ6OgDhTy+D8=,tag:O9FvB1NLi+Y+vCumW5NOuw==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:8Hc/FQSSGnMSqA2A8njoEQ==,iv:8CK1XvHvKqPjnuMU2DWzXPSJSraAtco5PDZLJXyFpC0=,tag:KoDgrAtgBa7nWS877i9img==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:Yo04ikes/l2WdbDsT6f3M/hFs6NZEA6+i5oR,iv:kNFb9WreqDoObvh89q7fhPDo15/POfQ8Z5O07Rz9jqk=,tag:0LPxJDemGBf7SCalnd4kZg==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:9a93qO1rTBfXi2UPhSr00vpje2mfuUL0dHrRY01hWB5aUBlWj9AJRUNspWaLqcRn3bM=,iv:TWMHEmPd9XN+qMY5USeU1/lEo072QPFe+3/cG91j4TA=,tag:qX7+lE7yBPaEkuiHqhDV5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRXRMajVyVkpORjNBWEt1
            YmtkYUlJVCtBZi96dWJLRlJIREYxMmwwdmlzCi9UVzVIUGxlYTRQbXorLzFubC9P
            RG9NcGcrNWZPMjM2YUlPWUMvT1QvVmMKLS0tIGFCeUR6UjNDVTgvUVhSOCt2U0NR
            UFFBTTdpSGVDZlBzSCtBNmlTWGY2OFUK/rDjnxO5urkFtJWi7q41Rm8pJ6fiMjhA
            qNnh81gtHgSv7UiwhXNJa8vA5NEk4F14cI9FKziXM8CAU2n8rk2lew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T21:48:50Z"
    mac: ENC[AES256_GCM,data:vgKYWOZL5mQZdDK4R3XCLzfqqsV2VTxIm64zLbOgdnRZqLQOS9JP/IMFamxEbZGeQQX3iliD6KJ6geSDS7/mqa/eG6YR6t3Ur4a6fMTLAwelLj/IQhOP/+EeTWg44mJuetfQPFT7Upd4AxvvPexV1mTSJEcs7wvgXvNJtiM1o2I=,iv:qP78CodpBEofTMxUsrNCRr5m7BLveM5r9nVkXxLuapU=,tag:VcVj4nb4k7/i6/L7qzFTBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
