---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "tanuj-blog-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "Tansanrao's Blog"
        group: external
        url: "https://tansanrao.com/
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
        alerts:
          - type: pushover