apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:fFB8v4uKT48sWz2ASFpYWwlIp+hf6LzaYj/HvxXITOLxiCqSXl3Qmtk0jqjsQ5eqq3OIZsNUdXiv/C6vFdhE9Q==,iv:hWWIokPsXSEsEXFsyNKSz2Wr89mDS7r25I3PCD8kE9Y=,tag:431dPx1j3mAMm+VfGg7D9Q==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:kIwyfzG2nJ0DazhTAAwAtX8jtNnAAzcuntzgIKkLwNXrYMlgDkJAEQ==,iv:ZPAw/ZV/oDXYwfpCKfTOsbFgvdnu6Hcicj4aiq6rVxw=,tag:xyq/BY1EmD3IIzhYAgg8ww==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:zgk6RQ==,iv:48HspV33cmA4UuGoPHAWbWK927ZuD9fGo9Jdl2M62WI=,tag:YwLDW0jTj7JsDAyg2htQCA==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:zZthyk/zbk0=,iv:wqVU+l02dd8wQY6v3KJhsIBsDSUtEA8GdUagofZXleA=,tag:W7eTX6tpfHlBio5bhT/uEw==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:96PjIz9uKPwlPwU/mQghXmEfvQadNbGQ,iv:9pU4x6BbCMZtX1u9Xj3DjfS/UU2QCM82N3Dk7frsh6U=,tag:UJ9OB3gKGmYY0CiNpM5SpA==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:tzQo4MON199s3/chMQ==,iv:szNiczHCrU6DRcuNEYdcKXvoW1NJw19uS7sD9B9t/uw=,tag:L/ZtgnXZPCQSaz/XsGxcXQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zq1sTPw5B2VOj6XViQ==,iv:BTtGRep3icBlexrDbcFThT0GkR+8pSmMDoM68eilBkI=,tag:C8m06WI1iZ3R+ylsnxkDgw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gc90Uyu1tWeFzNJ/pQt9fKbRpbc3i+iaU8QnUgairnPSY2CMEmSvww==,iv:GYy77W0hYR1mEpc5ZUIUgkQjhg6LtWk1g0zR61WbUBc=,tag:rSnKyi0e7eILtK+cLUGB3g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Htq7CCmrGOo=,iv:R2WBtac66fBnITEYrHMU9rP3eldNob5N/pvQ9ncy2OQ=,tag:tNTXItFoZDNKeXRSdAeJEg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GAQmvuByDo2I5y4z6XwA12AzplthR6je,iv:I1lZmmFKJXYspZXHSyjnRhmLbgD4jsGckwfAXeMCuas=,tag:dP3yM8pDO7bcnQRQKc2rhA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:5pdL6sMTk1vgW5tLvQvubhilMhuO+iTpvfdYUA==,iv:/6gBL0nR8pJA1aNlOSsk9RiYd62kH4bRKte7GXkwnFY=,tag:JVb8PSbAff56N7+3oYlEcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d0ZYancrd0FsaVB3aDg0
            UDdtNHkzWHRNZDNUOUY5bTBYQW9vdWhpQzA0CkZjNUJKQWsyV3FWSjliTzZqZ2Nx
            ZDBWcE9pblc4b3l2THpGUlNYNE9vdHcKLS0tIGlnT3I4TGFuV2NwcjRQRXFTUFJ0
            T0Y1M0dkalc4d1g2blFJNkZGRS8xaHMKpOqhDt48RpBUsa6QR+fAay7wh18BJqVK
            5MwZg9zS890JloZjvzD/o+4JdhaQCVGFygWbekBe+2Ob6MSFaOBx/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T22:49:21Z"
    mac: ENC[AES256_GCM,data:Bua2eRh/PfP2Qy2Cq1fKMH2Gb/m0hCGPmmsM797arXbkeF0a9Wu+CRiMx5zOB6XGqM7YGQcXhRfdJ48tkwdDA90iH13n04re/icMJG+M80zk9v8pFHB+lAVG5bH4EnIRvrz3McJiaAPH2gQVqpqCL/UZWXvU2F8x1VaQguYeRaQ=,iv:udN2bT9WvvHyopuBekQ6wXtXe0r18U+Lhj5tpi17KrY=,tag:HmrOkYdGuaHnscH0MLo+Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
