apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:EXZZB+xuMcUs86OlrobtE8PIJaOdbi2CE+WhYbpJ2UJ+fI0jBkiBQFnr3yCoVe5srUXpuw+PWnDrCu2CvLd+lA==,iv:KFfV7CmnsRqA7iBttgQiGnR5QlX/76KKkN7FSjOnS8I=,tag:PhtnxGvJz9RgRUBR/CwskA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:yB4u7z3d5dZnahbp6+g75F8ZxqDB2hy0b9GJ2ky/Wwdav7chggpzSg==,iv:wnMQapgxmANTEAvJq5mpY67QXF3wAh7bdw7iZ4hH3Ok=,tag:5UmmMc5aP16oMaOyvP7cHg==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:mTWxZg==,iv:RUkxCfN1A36wqwglYsolaHKuq2sBCrgBD0MjrQXYY5g=,tag:/a72WBR5vXiecP3N0ggCuw==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:LTFlXy5tS9g=,iv:m/AqYlpdv2KckVVSlqvcvWmELy7ne+ACpSmpcliqdpQ=,tag:uYrdHKwGy+lnjk/na65RJg==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:LliuvPyD6jv/6Oj0xh9b1wjeQpAvIzwP,iv:NyjpsjNjJ8GPf0M57BylSS82GegfE3TIDwQFOVvuA1Y=,tag:ulAotKY80imcRd/1iIIH5w==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:JCik8lN7xl4HT0T1/Q==,iv:bxNKgngqTOUyI9c51WLJfgfRMPjnzIuEFZwFHcIWM8g=,tag:W2foKowE8OKNlTfrz8QvYQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:QCN5ot1Eh6tE2e7Pow==,iv:vDyYKYhfCV+PzvXwOvzkhUU2uBX4CqIYoOQgkYywb9w=,tag:DLLDvg2PCaTo5VGHteefkw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:t+XnOPbWkXzYqKn/mKiaTJXKrBkgKGW0qfuu1JV4v4l9s4Lr6LkjmQ==,iv:kfdXnvarv0GNztc/JweU+t1+GWcGajYqpqW32TVFCO4=,tag:QIzrsZu6G2Njd8xTeC8WNA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:1JW/WLlpCZU=,iv:UEIYipOIWXAr9EdWKoTDxpw2WwdXNKyBqp9h84SWj50=,tag:dRGz4NYZq0uDX7FGen7vWw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qdt0XwrsFqyzZk+ZxqW9lHctHfyLfc8v,iv:2SSEq0gzCvmptvKQuZ78bNjN5N8ac/Ysit9xO5w7pwQ=,tag:bLzpRhf3+G/pIUsI2dtT8A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xcD+VrKiV6/QJYFUwQ6WFjrktVXHCzpzi1vSVg==,iv:Ktlt74UbOpKX6U2ckk+2zNFJ0HfsY8QtBa6QubuDB28=,tag:FM72/f4vmfMBVrXtJvRehg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWnZVSk5zTFBBSGdGbzBT
            ZjF2c0FFd2pmaU15S1NOZU9TRVI1Ni9Ka1R3CkhZdGRhZ0d1cnJpU3VxWXBzME52
            THI3ZnJ0WEErNytBcjUzelJyMU5FVVEKLS0tIEd2MFd5K3FJWkduM1E5T3pIb1hl
            VUZSeFlQaE9FS1Vyc2hTNjlTZ0NNdmcK0lZw19WoOLxfORNvCDO/oE1Rrh23x/Gf
            3v8So+dPPOE4exau1guDOgKMThVTj1wK17APkyluqZW2Uopst1eK4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:10:39Z"
    mac: ENC[AES256_GCM,data:nMyuTLtVldd/KxxOCC8R0PesdzKg4BvrzQkyIF/fu9PAaEFoFTgANH7/Obc9lS13Vg+LSJw8bEsmsv0Beqy7obL36897DOVpK1U84pdiFav/psy9lY2RxPzMpGcBCr+OQGOvKeoMq5cBjVxQrGGwpCZ5Jdp8iuMlu1GynMCiVzk=,iv:XtEaAjBsQIPWyDw+2i/r/SA/02hY2eyJoET0OO8T4Pk=,tag:23KeWC0QGqlRLTk6cIDEVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
