apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-secret
type: Opaque
stringData:
    PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:f2nbSxcTXyJrL0hqWwn5Im8aUuHAdREqrEaou9fozPHn6JY4YtaoaElXi7y00HR6ZmFgov3ODzWdVA5cwEBkKw==,iv:rQ7u+QBqo6kvVY/afy5h6GChBSG6WcDYn2Vsc/sLTOQ=,tag:Z3egVwgbphFTuQStE2SWKA==,type:str]
    PROWLARR__POSTGRES__HOST: ENC[AES256_GCM,data:mSwdt/DB4482V2xCE9AAn7crAgSTaKv+ZDxFaNOYp8W8qB1S2NPmqA==,iv:KeWlHmg7u1CA7jnU1jbr3idR+9eefwG9g+1tFly5t2Y=,tag:8aNwZ2GmyG/z9kod6dRWlg==,type:str]
    PROWLARR__POSTGRES__PORT: ENC[AES256_GCM,data:FQtYsA==,iv:ZisiGdx+k/NwhfTKcp94SOVGAiE/2oMV0g4vuYZMbMo=,tag:deYNoYjdVSorzQxxe1NxYw==,type:str]
    PROWLARR__POSTGRES__USER: ENC[AES256_GCM,data:QzxibbdLzAY=,iv:fvbt3+Vb6RDj/oL98u1Lj32D3iIywe+HoZWxBEL+FLQ=,tag:NROgFFyUOcRhfuL/EgpPKg==,type:str]
    PROWLARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:f1Ql6nXqyzuoy5WY1biRXOOo+GEfMANo,iv:UjQKd+7mwyu3JMD0QMtuOmf+17Gf5Ct3JUsrA9T+sJc=,tag:u6nG52Xxvmd5l6BQBrSGQw==,type:str]
    PROWLARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:Xc6iGy06anNAJNLkmA==,iv:QYUcsiKy54ZJ/Pv39zOGvqi3ndp8kAltrftGYa+axYM=,tag:ZDNbG0TFKC33LwIA2TWJtg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:uweDAP7zn5MB7oGClw==,iv:JXSAW5ZfWxRsqHsUvYsX3bXm9xKEfk01Aa9l3Pn9Iyc=,tag:eXOTnL6LG3vCih40gtSN1g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:C/C8MgJTQs4z2OoYWFPCleGRKjL6hhc64brCCKNklBb9e/NTKrY+Hw==,iv:8+zHLFwNFxYIXLex39dIMOhbU7T0lBRZPgBxxt2gNhE=,tag:C6+yqE0Gr2vOZsva8sJ2tg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:De+K0mkhpMc=,iv:BuXcwmlJZ7mJYrxnSvKTpxkKbBokqkdf6nVQPgjYCj4=,tag:3Y6GEdP0/cfKcN9faqpwmg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:CJSQY0DeW59aP0bdkpj9uTYZt2SIIRBh,iv:kAt66WOiRAaNhXA1+K8zjPgxFKqzgZHOgDoH3YsogJM=,tag:rEyEg4SKQPcXDIbBB0O3qA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Xh3bcX/QKdrbVKdI/TViKJRKLkUrE1gtDTcl2g==,iv:epft6Yc3knSHVYVkF2Pr3hkpFUacHHQF4Glk+IH5FUk=,tag:s2V8UGCd8b7pZ3DhhGvxkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNE1YOWxxdnBWRFpvM25w
            QnV6SFdOVHF4VGE5WGNsODFLcHZQMEprNFVnClVxaHRkOEhtdzIzN05yVFltYjc2
            L0hMVUxyeVo3VzJmaFpLdUIwUENUcEUKLS0tIDcrblVaNlk2cjZvY0ZDMU5EUG1H
            WFU5Y1J2Qm96YzBCMlpXbXZTamhta1kKX3IF8DpBlcfyxX0LiRRh8WpCUPugCs8H
            FQ5c7+Ccr9o25JDGHw3cBfGbd4SQADS/a4OWwZOWIBVoNSXsxHyyKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T16:57:49Z"
    mac: ENC[AES256_GCM,data:uzg1iJCYdF5q6EKuggnrwVHgbYwjCcCX53mYFb0ks/95rZ4J+wVcERa8XUL91/wawLEAk7JNyJns/7yiHr4j71xuIBfVZ6yzOOxkR9WBillWUBHNaeOB8pAO0xeARh+pl3nYLO/dGc1PqiPKEEtFRR35DmGs3oHrBqv/F9YHuY0=,iv:OGVz4DJbL5kJDnKZRYMSjzQHQiPkQfrFO9Ux/7suvUc=,tag:SMsLaAZVW57joW2hxEj9eQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
