apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tun-access
spec:
  statefulSet:
    pod:
      labels:
        pod-security.kubernetes.io/enforce: privileged
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
            add:
              - NET_ADMIN