---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: seafile
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: seafile-secret
    template:
      engineVersion: v2
      data:
        DB_ROOT_PASSWD: "{{ .MARIADB_ROOT_PASSWORD }}"
        SEAFILE_ADMIN_EMAIL: "{{ .SEAFILE_ADMIN_EMAIL }}"
        SEAFILE_ADMIN_PASSWORD: "{{ .SEAFILE_ADMIN_PASSWORD }}"
  dataFrom:
    - extract:
        key: mariadb
    - extract:
        key: seafile
