---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seafile
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      seafile:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: seafileltd/seafile-mc
              tag: &tag 11.0-latest
            envFrom: &envFrom
              - secretRef:
                  name: seafile-secret
              - configMapRef:
                  name: seafile-configmap
            resources: &resources
              requests: &requests
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4Gi

      memcached:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image: 
              repository: memcached
              tag: 1.6.18
            args: ["-m", "256"]
            envFrom: *envFrom
            resources:
              requests: *requests
              limits:
                memory: 300Mi

    service:
      seafile:
        controller: seafile
        ports:
          http:
            port: 80
      memcached:
        controller: memcached
        ports:
          http:
            port: 11211

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.tansanrao.net
        hosts:
          - host: &host files.tansanrao.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: seafile
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: seafile-data
        globalMounts:
          - path: /shared