apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:cn3UoNJIqIMcNHnOSQhSZ/m3x/KCFR3tG0s/+KACFWhH+bvm9Jf+1JUTlNR2kIlxZt9NYasMX8Tha7nJIAf7gA==,iv:fLI4WMi6reFaJBIdleQOudsw50kwbtHU6inO78lg2cY=,tag:FuaNY4vx1XjbOIuX6FEqcQ==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:0VRK6oy8A2aBQ9HAmrqIvOouGURtcy75TCrYun9LdqU1Q35feYWvyA==,iv:cJop9j+qEqEHrbUynWk38kfT+gtja0YYaMofaS9GxVk=,tag:IcuLpbbUBdtTZcojbxlfxA==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:mZUvBQ==,iv:MtGCfvej5mOKcseBV1jm275RTiGJT3HDliYNSW1JLjM=,tag:XsUCi7E7GFIFO4labZNfXA==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:0gvIkAk3,iv:YS3IYqYWQP5fsJligTFhO4BXwgheDqtU170bv0EWciM=,tag:DAmKXZ5V3CK/jnLU9DDwWA==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:+CUtBK5CZ/bmRKqsqJihmv76N5xVUpi4,iv:0z77UwWkc/kWU9iDvEiQSF4YkJYYOD434vJeTNteOD4=,tag:PS9frONXhG7XGrAyrd2n2g==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:Ur451YPvLCj97hw=,iv:mFWe0S0y0UVfhcjsxae0dl+bRa6+gVn046EEbO1Sf0g=,tag:UGt+fjMWWTHXVLBhwan9Fg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ocCLlYN1jFD5KJY=,iv:W/sov0RcFazhaVHCXlQ/muWdOe8TxafBwf5DT+OOWPY=,tag:LIXEyGWFYRSMwMSOYa3E5g==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:n5DvC3NlIK1/eKmV9nelzNKVhtu0+IfmIOjF4kr2yU0oIUN6yjyAmg==,iv:PbS5s9AUU6t2JpoSTqHLb2CiHADzhF5p3dzOVrRge54=,tag:49Y9TKXSKRlkTgGTV1Bz0w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:/brNGzWt,iv:nXqe7E6BX0GEAwy/FzXZnVjJXL6bhiRnwt4BPHejWJQ=,tag:1B3Rt91OQWubEzoynSudig==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:xJ4Nd6NFJHRs9Zvc2HoC9tZQ1sgUNoiT,iv:zzXs67DcweACBLg+lCOxmmx5eQz9ZxSO7BEsRU4WeYA=,tag:u2A6qjcAeCybf8BzFVnzmQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:M1j5u/UbsLIpZObrrqx7JjjArzW1at1Ns+AIkw==,iv:abCv+lJpinYjOArzCKTnmOVDMXphjBFY6Sj0U6RuYqk=,tag:vFQ3pjPWYcWWOw2V3A6dcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOFNwZ29hOCtFdXdTWmJo
            ZU9wVGlsYXZ5cGxOVUcxeXFMTTg0WTFoaVdZCk5CcEpGVXFIZzZOWUVOOXU1TEJh
            Uy9jSy96VldvUUZ4bWVreXZWdDVhTFUKLS0tIDBtZk9CYkVUZXRpSlo3eWpzVlJS
            V1RLVzFYYWh1eko3cGMwbFRrTkNpa28KikGHjRm9lFYXzFVeTlvaQ/E5yUDFN0Mb
            dfL0kkqcQW5hvaGE/u3G/QKzD7oiy4CUlA7gfaRtU7yQsbfd9dbZ/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T12:12:22Z"
    mac: ENC[AES256_GCM,data:/ledgxMAxT9JdVx2jNLI7Xrqdz9YW7XqJEgqxOFPAc91MVFjQUNDop3mj1iImlZZWuVEfB3N6niyzV0WAXp2f2cGcuZusBV+mgIXw7IDgLhZ/70Su5wgUv8pQ9ix7oELTs3zw2qddoTMdP8yWxPlpjSw+gJT3SmeUdG/+5/9Iw4=,iv:LbA9/YT7tVYvKaAPN91MB9jbjk8wNTl7M885GI7kMBw=,tag:a5pZ7P8aNljCPnKWJIgXDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
