apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:XOYOeX+W+ZNRUWIWTCcipWaZExmWRVnwv0cfMRkba1tK73k2FX8LWU0cQJmK2HiNNtMwJ1x6VnFFsd09bWos7g==,iv:9HZHbTPsFK4+Rv+Mg8k5F1K/pSNFZCQWp2WblJ3cZVQ=,tag:sgs1fLyPO5nmUiaxhIXuqw==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:GPg+o6Xlqn2S5LVKQKS7wX9nk9dXq86cHpYuxS0hn/FQfCTu9ftwOg==,iv:x/3Vc4UReINn3rDR8QFijtYmaBYIT4j0Qo8GSOwoRP0=,tag:BW2ElSqN5ma04o9GjpQa4Q==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:24rX9w==,iv:Qfqvnfr2lFhv67Mi/bTy2xZ8eShuzNgKMxDD/pHAnIg=,tag:1cMlVI5VisMAkAeCaDiIBQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:A1o40FBt,iv:3bascD8WmuKKeEY+El475Am61TnoSPeAePYmTk1wKFM=,tag:UOFIrkb1JCChr5d+oMitgw==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:Gf4dOsuh/n/WT/FRW6FoAbn5cSbO+hvG,iv:8XOw5qcJIcEDIyE0DcdBCDJ+Lx+9aSCDTdVzpSbgUkY=,tag:WO1z73ecHxiM2l7/QpCE+A==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:OUNtMGBHTStc7FM=,iv:QXijgDx+wMtloJXoWZn6kaT1pZ8WySoU0sWxODS3buQ=,tag:OqWxcbe52++lRc/mxCdjCQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:1S+lrW9Dk3dCgLk=,iv:3EV73uAUbCUfxBX7WmbxkQt9GSTyfRfHHrpCNnK1v04=,tag:fskpvKSoYKmlWJkF0IkP6w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:E5BzNPL/bDBw5+lvh4LdvB/Qa0dk2aNhpoP20pt9jMWz9aBYmaECmQ==,iv:liPLt9E9M0XtEREe/MldxZzD2A2g8CsysiJEluCx6Oc=,tag:74GdcXvKegsMQXwGhLe0eA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ws+uHsY9,iv:SYHfkG57K2fs8owhrtCH53pJsNr6sLSQ03ZuiAjW+Lw=,tag:BaPuZEzwHlKuYvg57T3HJw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:erbvQxMr6h4Az9KXJzhIMmBLXgotUUzu,iv:Qxy8K1G40aOECJ9RLwst9/Ya7ifuDMu7DWcJkt67mh0=,tag:W/afc1QLezo23jXMN6s59Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:b1fEHvEE7rsmX5p9lvebNOFooFnUjnOrrxiO4Q==,iv:P+DkTjsVOUY4SbE5WqwBIa2qBU/t+r2fS0Bz41qDhDA=,tag:qaixQlOiJr98JLNxR6Q+XA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2NvTzRNQWgyQ2VUV0VR
            K1lTOCsvOXZiK2J2TWdzS0J1WlZRZWRPemdnCmRsSnJyejQ5L0YvWEpaRGtUbHVM
            MlVwT1o5UEdTQUllSG82VWJKQzJsd0UKLS0tIEhMRFFialY4czhEVDZRZzcrMTZI
            NzFLZStHY2JxeGk0VU9FVXNnNkwzVFEKwKs1RwV74TU9EvmvvNU4k7//oWCSzQIm
            OnBM232jmsgoZ2yT9b94T/bM/BA+5Z4GjKDFfJZSQgdYWcevDVujbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:10:39Z"
    mac: ENC[AES256_GCM,data:pW4oz9uUkVaKiCVUaCs3UdmwHU+Ac0Iy/b/cO7zvYjon5UHIqClNJZkTFiKX5JL3sQyvGLOLCJMmkeLLpCcJjWIwZUWxf81gXhnSNEvabxsaN1+5cHlZFRJEF8yQOOP82QrnMUObFlRl5zd28CScRBlv7y3bqbzugNAMH3cb33w=,iv:yn2eqHxf3G0jO52sNa0ilvHY2DCX9yMjbitRyjktt9E=,tag:wA4GXNy5xS+slrWSVsBKyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
