apiVersion: v1
kind: Secret
metadata:
    name: radarr-secret
type: Opaque
stringData:
    RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:hsvbsrVy1ZoWKcc1Nq4VcMXr/REEXmy2h4bzRfgz7Srdhvcq37dZpFSvXCUdsXyyip8b5NJjSt0t1+yjaKydDQ==,iv:go0noNau/o2QPWi4n6A1DA3F60ULAOV71MuH22HFOq8=,tag:/2tk3IA/7EB814ZEoS1HAg==,type:str]
    RADARR__POSTGRES__HOST: ENC[AES256_GCM,data:UNze7wSIkgGA5CDAOK8zMsNhV3tLbTFut+K1etDwb3yS13CWf6+AYw==,iv:ya2M1nenNJrDuOjcF7/dh0rvsoEpn6ogslRLS9e0aoI=,tag:HOE1H1rcHL+J9EiGlWuJmQ==,type:str]
    RADARR__POSTGRES__PORT: ENC[AES256_GCM,data:Fl9lRg==,iv:V5F/oMKBREoUX86wEpmCOUvhpjIeMrmVxNWCz4BxlWE=,tag:RSmMah0PemNhFDeTGQ5rrQ==,type:str]
    RADARR__POSTGRES__USER: ENC[AES256_GCM,data:O8jUR1Ng,iv:QofMK6qaecssJ7zGRiwRZxsw9YdRsb/Z8zs9old/ckI=,tag:zGwiF60FdHJTCweNzL6myg==,type:str]
    RADARR__POSTGRES__PASSWORD: ENC[AES256_GCM,data:IOyn2NWUwG6C3DShRZXDqmr7AvJXQE0P,iv:icfQefliWE2YRpNFlLqojThnkuxasE1f+Bso679JLxk=,tag:ZSEQtcJPNuFE+TBhUdEsmw==,type:str]
    RADARR__POSTGRES__MAINDB: ENC[AES256_GCM,data:ca1AXIbKIi//9DU=,iv:t3CGBLP/EcSmtN18+E0hdpFlm0aagfkaxXZoXExnAEE=,tag:StoUKl+gIJIHpW2H/eC9Rg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8yBt9xtY4MnXkBM=,iv:5NUd+2k6LPLKVIujtrTCrSQ1+FhIFqe2UNOaEFlZB5o=,tag:Jd1A60vaEdt862x3zF99cQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:9gKlQUqEJ7hv374GAIWXTP5mQvQNOj+BouhBxwGYN3lRp866/0dC2Q==,iv:VhUmwS0afyjgp0OrtNz8SKdr5IdKpfpmFP+Dk0Gl1kY=,tag:gqqF98U9LFq7kuv09PbddQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:mHyil174,iv:2kvI6ExhGG+8YRz6x60Pcan2jrNyR3sJHatq5TapyBQ=,tag:5eyKbxnVFDB3ABCfY+3ZuA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:gIDiDLexR8CXh0CBE4uuQXDWy0ri7FBB,iv:YbuaZPhf+qCCgbA9A/do877DQmkbaE26rixsnJejxNc=,tag:5FHWtmJoOIfM/QhqUo6XIA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:eZDzoW3UMLmBfp0k01PYlwQVON0zxwAHyMRKSw==,iv:PB/DDMsm7yT/fMuzwmQ7E59rzX7c6nzBwwDw9eIvbEo=,tag:9EbUVwgEG0WAiG3JlPIBKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRkV5aHREVmpqNzlXM1Rv
            d1h1U1oxMTgzNWNvMXhIanFXWnY4MGFucXdRCk5BNmdKNnArbjl1WmFYZ3ZrempD
            S2dMNHZvTjlUZ2VaaXNTOWVGdWcrZUUKLS0tIGpUTzlFSW9yVzVpb01ONkJjWjBn
            V1lOTERaejNXaDV3WG9PY0Q4WnlINGcKBWGqLRa2EJbwjOLmzXCuadWBVIm0miPy
            INUdsmMxlzSNQdrrDl2ppHKgv8j+27NDMBiaTNaAVmZF/cfoNRa7Qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T21:22:59Z"
    mac: ENC[AES256_GCM,data:we4w76kCcDeTZbjG3kGxFcD6ooXoD1G9tV3sRKQgG11CWy0hg8j8gw2lmra9RxVtwgRQxadv6WSzOs7vSP4N0VtK6hXhrj+vBCDmNcyjEtF4eWSvCLIj0bUPrfo3NRXxHStgeB4x3k7zdJnsrfy0i8SMjdPkx7dbX4tF7DIMR4g=,iv:5gyP+Li7AMYSlFRTrToxnWLgQQunwmyCW7lDfHHA5fU=,tag:cOP+IWw/3Z0aXzGs73IsKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
