apiVersion: v1
kind: Secret
metadata:
    name: loki-secret
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:qxzekpi0m31fBvAlWA==,iv:q6ltsVFugdcc0YtA/W8J5lXO0sgQG2VtEgVJDhptOFs=,tag:vFtRKOuceGJvIGK3BQ1SbA==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:zXwErGf6hjX129bh3aSaJuMDNQ==,iv:PnCJiZemiWVc1Kr7nKUAnITOgkWg2H+0vuXsMBYmTm8=,tag:Iz+dZhLbNn1SVX426aonCA==,type:str]
    BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:RnlbdrlTuLHP,iv:A3uDC0Q0FCAnnSqqBNfI4DUnzHkvcOzjq210ipBRdIQ=,tag:WjJi5pJFY7x2QMZj/WCc8A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:MMcBnhUxpcD9V2RJBtXl5gxmTuzN66k=,iv:L5nWRaQw61lYvNh8NEdxS2a/T7sOPaXbjLL8m/ppSEM=,tag:mT1ZiH3jMP15IYIgZmCM7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaXRRRTVCRzZnWXpHT2w2
            M3NjcnlzSG9kaml1K1d2akZkZ2lhc1lDcG5FCjFjblErRVBxRFh1L3JUWTNzYjFm
            Q2RDYW1mVjFsSlRuaGtOd1BFNmdDY1kKLS0tIHFJWStUWGQrSksvZ3lOTGNWQUFu
            OXlaNGhFcm92blVkWlBidHhBUk9RSm8KGIiMRD9IjY9IpoDvobu6dy9WU2NjO8z/
            i9wBrpp3FwSaqctNIn1BKixu+R1OGwbMgLda+8Ko3sswKCyW3w0cFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T12:08:22Z"
    mac: ENC[AES256_GCM,data:MN5+89JHd/N+M7pDD0pbcnmc7UAYf92RlqqyLjDI5qltMCgZgEelFOKx5txIB5reAXNFJo1TSXyE7FzcXyjCSu4s7cK3U23K2UpSLWNq/QSUlA20olURxUMoVW6RuuguXIDJbXuTGwzehrfJRRRuGDoUfjTCXrCP3H+1u0OGQi0=,iv:loyoCqSwetkVNo3qDegAQpOaODPIsW8aZzu9MfpenJw=,tag:3boEO+Po+TP05HjygpOAcQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
