apiVersion: v1
kind: Secret
metadata:
    name: loki-secret
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:EU1Mzedx2Br8tsp59Q==,iv:rimSin/OisH1kjcW64UbUSFpLZ8i2/6tcNAvICroNpM=,tag:qCBoI4F4Fs/tCvLQZWYIHA==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:0F80npUtlEO/ZsxdNsBdOoRD+w==,iv:KQl4ENzxMzUZE8JT9OfBnIIQ8tfAQp7lXBbxSibSYUQ=,tag:en5TVweHXJwTQz8thL1uBg==,type:str]
    BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:j4jxuoNYF6s5,iv:Ru2Kst3ELYGLekMRelf7WjkdulDH3sm6YgVTWQLNnWk=,tag:jqQC1zitY2YrevLNJNUuHg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:8HAnvj6+mS7d0vOlkIDISqOtb+JTqZY=,iv:4riP6ak8IGdaXEoWjVgp6L/KbAkIIyiVnXZFtNdVGTo=,tag:JX2ybgZG0hMjwNzVrttgog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwM1NiVWtmVHplckM3b1Fa
            eEtkdENURERDS1NZRkpBNEJid0Zlc2kvNDNVCktRQ2xCZVNNRU9hc0FNamd0OUI0
            bkh4U1poZC9sK094TkhWR3FwWmpFVkEKLS0tIHBNL3FNb2RxM3BScUNtSTJDSWJL
            THFoU1Vaa0lZS294Ui9SV2haLzJndFkK4IQaV93SOVykffdoyywNPW5/1NKf7o3H
            wGOTAHIdcVtcgeyRtUmGSgPKF9jqtU8IeOpQRX+V6ZJzFsHYBKPSuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-24T11:21:28Z"
    mac: ENC[AES256_GCM,data:Rg9UGD/5EzigXT98RmnmLbjum8vKfdOuEq604o75jpd1NoM3oiIsQyzOm6y7647+pFKavcorZWtlybIEDaO6HBWk0CxNKTvbJ+lzqrLaubhuyT9LqaNi0kXKgq0+EuK7X9n/VOyR83OIzsRUbUkt8WHE9KsmrlZXY0yfIPGFE4A=,iv:PnO3N9HUQm2ZG+Vy/x3vgfOmSSSdzv57/IHhinyNF4c=,tag:rRsVtEdKFfJMStyd61plsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
