apiVersion: v1
kind: Secret
metadata:
    name: loki-secret
stringData:
    BUCKET_NAME: ENC[AES256_GCM,data:klQdOlZeZRD9wfqwjQ==,iv:Eb5z8rEtgsQtdNu/VFoqg/BiQ4ODM0vw6TTG/lzmXsY=,tag:NH84g+l3xlRL2nl4Wa9IMw==,type:str]
    BUCKET_HOST: ENC[AES256_GCM,data:DNSgnwalqVjRHo1tUBsHzXliPA==,iv:1VdMq1BdS9TWGXL/pQJW+tMrvl/xtGjbBMGS8ANmH0A=,tag:LtnFt70V7eJux0ber+eaEg==,type:str]
    BUCKET_REGION: ""
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:NtpZFxctYzWy,iv:19+F6/uA9QFUXm11+4LqDjqYCEXzT17u3QXMsmQm8Po=,tag:qd3fp3XVVKn2leNJ73W1vA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:sW4oCxLb2pynyLwCIbuLJTNiFZ/LrPI=,iv:YyUrKawh5z5ZzT02Wn0LyHDtrgYcede4asyoFwQqKso=,tag:KfgV35ZlqHqYJLIXN3BTcA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZGQwbU54ZkJtTGUzc212
            WDZBek55M1Z1aHdNaWhCU3FrTDE1MzJ2UGlFCm0yb2lZbGd0Q2VqUXpIZzRjQU4z
            QzR6aldMZTFkUzJuMnZNOTU5cW43OWcKLS0tIEVxdGdOWDJHN1dRK3hReEhBUmJG
            Y05yamY2ZVNRdXcwZy9BY0tXYkUxVUkKZevj3B5U2ttSS+DHp8z5S13mp9rkfESW
            bSJPMF1gXbNjvnp+VSw39Rz2pjcsO5x/RGRGxlhhmYq/FTwwOa01Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T16:52:02Z"
    mac: ENC[AES256_GCM,data:CKaqNK/R7ZTYba2MtbaM+8N02mz2JLW+tf9BWvX0pa2WQ9EFCB/r38BQcbOO0UyALsL6K2BuK9AUDxnzs2lWJK7gAx4wEkTagbslZOLFvyB9g/DdQCHFFNQc+12Ruf0nprlxP/BXlYJfbtxKZBUuVoGFpkUD+zbtdnvgPhSVJjs=,iv:NtVG95/zAPaEfCZlIWQjRI+OmfgjNl3a0YEwNCvmcBY=,tag:f9JzZSAckqmmbbaTAihgvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
