---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pmpl-website-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "Prithvimetals Website"
        group: external
        url: "https://beta.prithvimetals.com/"
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == ${GATUS_STATUS:-200}"
        alerts:
          - type: pushover