---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mariadb
  namespace: database
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mariadb-secret
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        password: "{{ .MARIADB_ROOT_PASSWORD }}"
        maxscale_password: "{{ .MARIADB_MAXSCALE_PASSWORD }}"
  dataFrom:
    - extract:
        key: mariadb