apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:l/CicMKGNSILsuvY0w==,iv:e+1vlM/wjDu2dRpmnEVo99QmO6OlMcYpg3DZyCk9bRg=,tag:OrNbLd1Ftw/IoW6Bryrysg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:r1y1J9sZs9tCeWOhNpDadFlHJH4=,iv:xJJJk/CWEOIUDliRuBbtSGQl/b4jwmSnodkaaNNxq7w=,tag:ZasTBxfSUkniNl+CCEHeng==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:gWaEaLCQj5TWpQxWy4PsQaKI4wyeKMwBx6GklUL0Sa1EiU8T,iv:EGDzR5+GZPkzY1aG4KTl33e6Q4fuUjdWeyA59U08vd8=,tag:LTzDlFxXhYPBlW1zzbCU4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRjl4OWEwdy9HTnVHSkJw
            Ujl3TDFOMFNjN3ppWDRLYzNEUUQ1UTFOYnowCm5FRGZxaFpCeDVpekFOcS83S25x
            V2FsSTVCWHlLZVB2WGloUWxFNUxudFUKLS0tIGk5TDhyd0tSME5kbmw2c3QzRW5Q
            eVdGajN4UDhGb1FsSlg5Qm84Q2tLdUEKu/VbLgrD7kh5z696rOoqZUi3vQoM6GgS
            KVwDT1/224Se0mzfzgBJj/4Kpq/1ZbOthjHrwca31dhgNJ18r2afsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T14:10:37Z"
    mac: ENC[AES256_GCM,data:VgbyGCnm7ZBdzMK40S6eK9Aqz+1x3M+QfSMTje/Y7I1t4hAPildumD7sfA2n6uZowM+R5zxX3f3XJG+igOK9SXg/Era2ofjuoVDs7e/pED42uScOE16SDD3tR2q7XSysAyj0+dj38qiZBCd0Q1vOjqufOKcJ9aEId9au2fViB+g=,iv:T37LfljHnseABOMzz9FMYGkv8PiATWfWyoIieW/zPco=,tag:295Q9yCiSdonOnrjVZAkxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
