apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WN5fMkAdOWd+Tuzz0w==,iv:dcLVzuqTagzxxK9kjTzOYMhpIeHMzsvbbRekXN+qpsw=,tag:1Ehnalm7NlA3pEWWXKL+ew==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZRUFEneftlXw3I3yvrXeg3QWD2w=,iv:uc+pAfkfGDsxNFJ8oQc61igFAozgOY9+8D3/Qt5PgUY=,tag:GnMZKkB0kXyNs0ry1jI2ig==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:/x0rP+93VQQLonLVqPcO60Oylw50jc+3aBu+zXEi/kggMEVF,iv:Aody+GHAqB1fhXl/BsStOk+SbvTqPd5H0t5KpEJnDak=,tag:42hfYeSOdzN6Q+a4Z5Qifg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYlN4WnZDQkgzdjdndmhw
            OHFMWXRxZFV6dHIvQkd1bU52Zmo4S1VZSkZzCnRFR3pOMllRVDZSQ0h6Y1FkaVNN
            dUVTYnoxY2J4Um1YdXFpR0Rkd2RpMWsKLS0tIFZ2TGtrR1ZPUFdLanlnQ0pHVUx2
            Q0Faa3F1aUlRWXVDQmRsMzhraXorZDAKp2XAJ6Pq1EiZLCYNPGaG656quOwLxRDy
            9gFUGKUtVyjGrosXLv60QrKMv0xoBLQZBMkDD4l3Hs2AKV1FFW54Pg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T16:54:53Z"
    mac: ENC[AES256_GCM,data:un2PUbISOKTRiZX4chFesPCfVIS2qi7Wl4xJxZOiNV+5ExsSh/8HuH/7p5U3QZLBAzD0a3ckqNrkQZLXaut30+WaqlHjnJkEvdrFUqdETa/BZwUjgvgHS9jlFL+bJd/JjpaUSd6r80YzE+ci3kH0T8GLl75iFqyDoBYBkbDHLIk=,iv:D2V14H5IS0S23PQvclSZfIQlO2hUmxOoYZ04LoGz8+w=,tag:WFR5bP6OXMlp+OXcj3y9iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
