apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:5/JZMLnkakYhpkrkWA==,iv:RFEz2o3uCw3NSGmSFUEJ7bnnCyP+Q/9tS7vU8Ez+qcw=,tag:GmpZ3ZFZsBmZisdbS9r8/Q==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:e7CWIcZP8OTPHbd4zFPFaD9jVps=,iv:Fz3GzsMvhi83rNOr404mHGoI0bM0Ur3xwHDPc65c+d4=,tag:/Z0rSHIkxITG4VKnL8akkA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:N49t+EYr08lE8g2B41YIz6nJ1iW+9Fdnd5SEuMUcsNAj/cMp,iv:ImPg6i3CX6f1/HkGk6qNHhBvN8eUsPHZCUjPBoQfLmY=,tag:jnO1bsFfUFfNRqhTsDMz4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TENFRVN3d0MwbVplU3cx
            LzFWNUhEV0c0dmJzR2QzRHhnWEkweE04U3dZCjA2QTI5M3V6ZEVScHRzNHJkZ3ZB
            M2RLa1NjanVsRDV6OWppS0kxa25COFUKLS0tIHRlWTc4RERSTzhkeGxTUTFVeTVR
            aFJIMk1RaHpKa3kzYzhMQlUwdS9NdGcKrGV6Do3V31vWazpcFvX/kLS6Qkq/cLXH
            4oWAVg9wnxg9vUaPWqdNd3vYevYnJAxHQoJoStVwvtLioJPi+n8NtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T13:58:41Z"
    mac: ENC[AES256_GCM,data:0Bh2O6G39xa33EKWMCtyRz72nDPk0rQxJu+0JLNtl0VgS2vVOvQpVOStCETWPt/rFAsUMdPw94L9tWHV+yHvHTwO0sM1UaIXRDlIxx1rwzlQXNhpGz9Rt5Cc1wPa4ED/Eq7FsiN/uLQ8cJWM03IF5QV3AqwxSnDf1POhUAM2L7U=,iv:JPAiSKt1JECuPIToEw3cOVa0VZ87MvKvdzZnCLfy6Bc=,tag:juoH1DvPlxF59xskRGwISg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
