---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghost-mysql
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ghost-mysql-secret
    template:
      engineVersion: v2
      data:
        rootUser: "{{ .GHOST_DB_USER }}"
        rootPassword: "{{ .GHOST_DB_PASSWORD }}"
  dataFrom:
    - extract:
        key: ghost-mysql