---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-mysql-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: ghost-mysql
        group: infrastructure
        url: tcp://ghost-mysql.database.svc.cluster.local:3306
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover