---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost-mysql
spec:
  interval: 5m
  chart:
    spec:
      reconcileStrategy: Revision
      chart: mysql-innodbcluster
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: mysql-charts
        namespace: flux-system

  install:
    remediation:
      retries: 4
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true

  values:
    serverVersion: "8.4.1"
    serverInstances: 1
    routerInstances: 1
    tls:
      useSelfSigned: true
    datadirVolumeClaimTemplate:
      storageClassName: ceph-block
      accessModes: ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

    backupProfiles:
      - name: ghost-mysql-backup-pvc # Embedded backup profile
        dumpInstance: # MySQL Shell Dump
          # dumpOptions:
          #   excludeTables: "[world.country]" # Example to exclude one table
          storage:
            persistentVolumeClaim:
              claimName: ghost-mysql
    backupSchedules:
      - name: daily-midnight
        schedule: "0 0 * * *" # Daily, at midnight
        backupProfileName: ghost-mysql-backup-pvc # reference the desired backupProfiles's name
        enabled: true # backup schedules can be temporarily disabled

    router:
      resources:
        requests:
          cpu: 48m
          memory: 64M

    podSpec:
      resources:
        requests:
          cpu: 50m
          memory: 512Mi
        limits:
          cpu: 300m
          memory: 1024Mi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 95
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - mysql-innodbcluster-mysql-server
                topologyKey: kubernetes.io/hostname
  valuesFrom:
    - targetPath: credentials.root.user
      kind: Secret
      name: ghost-mysql-secret
      valuesKey: rootUser
    - targetPath: credentials.root.password
      kind: Secret
      name: ghost-mysql-secret
      valuesKey: rootPassword