apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
data:
    username: ENC[AES256_GCM,data:IqqcFfi2hnPC,iv:EP+Q9bWOsjiB3Jkuo2KsIqIS3vAFalaYbjR9tqgglVY=,tag:C5Y8uyFmNBKtBlyz23LfNg==,type:str]
    password: ENC[AES256_GCM,data:YJatCbtL3ASmDydo9JAwL3eP00nE1CqXTVtWqw==,iv:2dMjjTAJgLTC6suctZmj2NmYRZOUtgyIsBIxTWQcLs0=,tag:xT7qtf7G1eDMgFYGIfESsw==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:DIs/9izLUqTC1z1Upw0=,iv:rNfstGbQA8190CJ0Oi7x0gfglNu7tk/KbF7DZ9kHFzE=,tag:QT6Uh8oH8Xj+p9yJEZ2w/Q==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:VvffiBimNI4lxmjMOhr7Sx2sH9ELMmfcxWrA1/rkF6OU3RgEFeYHOw==,iv:kHdi04A7o+Czz6fMMWbA9WWgzLIGGhnbY+EBrStd93Y=,tag:eBgykaz2yLIWgLwuOQTKvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrbGpZRDRXc3IzR2liYnBo
            WTcycFM3TDRsRjVic0JpcnpOZjJtQkNQRERzCkJDKzBuSXFPc29kUjdhUWs5NGhB
            U2xPRUcvVy8yaDdRSTJJMmhaOURwelkKLS0tIHlSWHdKRWtDcnEwR01OeFRJb3E3
            NzBmZTNIeVp2Q1pVVHJQUVZJY2tnYmcKPWhNpTLVQE+UrDdGVrSD1OJZ5rTJxFTE
            HTAYyGp6d0qnOAAqhv9rYxLLMhmpGU22oxNgAPiGzah41EisIBNSyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T17:23:49Z"
    mac: ENC[AES256_GCM,data:3A4XDZu+v97TdD39g13866RbJvU6WnHnL6XVvGpP2sxEXdR8deJPgRyxjyJYF6mCTHq2A9PwWyxF29Csieg0BJcXlfcE5vYxan8jzlv8HAwCIlUmcbsgCaH/6QHXVUIZKC1c7bgLB/e1XeXHRWllU6DBfz0mcAuyuyJZjrWEIKQ=,iv:8EXUMis7qUChlDk0GV4jJ4B85EJO+mNPwBIkwVR9piM=,tag:rzC1SCSc70VBHV/oWiqp3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
