apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
type: Opaque
data:
    username: ENC[AES256_GCM,data:6F/iTJ3SPivGODlv,iv:lyohS2ytqlVtRAS/jJFifHW+NPCNaMFVydB7eOgSrl0=,tag:DMizDH2Ckx4WzmWbMr6SNg==,type:str]
    password: ENC[AES256_GCM,data:Fz5xH0xB1gQMDySgRMOJQuYGCKajRiDXRtEiMcsruhiIiXkqVgJsDA==,iv:wH74gJYIQgAEnmJ5d8QdvGpkD160g0VxjAaoTQBS5dI=,tag:gL1HyoySNJV4+eMoQmzx6g==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:3RuxYZwnxWXyLX/XFBTX8WBJsiU=,iv:iV493oIjrgpfORfycOpACROQkWLdvLQ4tyHiZjJiwQk=,tag:qaG/dF2oBNfJGnenLjWrMg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:NnAxKMHy3XJF7/nr/K8UTtGDasKnx1y5HQcpXJvPAg7Tv0CYBcWMdgWYrayXtFwhStK/HeHwiLQ=,iv:KLtZ/S6wuWQ7ISVm3BRHqj9pZS3K8UM7AxHI626QvfI=,tag:NkoBLTrpaBavYbptxtq/Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSUtJNHpJSVJoQmR6VzVs
            NEpnNDdnU0ZoTGdxWWVJbjMxN1I4ckxJaWdBCkppRjFQVmt4OStuN0NibXZxejds
            TE95VTd2dTBrcFh5VnNaTGU4YVkvYlkKLS0tIEtGSnhoalVUbXB4RnduY05vTmdB
            Sjd0V2pDWlZCNi9mWmhER2d2R3Y2bmMKQGW2MRcO0av+0DwID7S5cjunVPveuGto
            2A93kt/NRYjbPRcPdtkN0wLXAYjOytvIbjUNjtnqD+z2kimpiioIog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-12T17:46:32Z"
    mac: ENC[AES256_GCM,data:HfUOUslMOjKN0XbtqXxuaMQMzkbg2Vzsw3Fsm84Xyqqk+Izy0V2RSIPk5DPFQoNYbxAq1RcN0RNat6yTFHNRrLt49AncdtL02U3B8/5bfh3ZcBisrEGz11WRDYY3M3Jv/D/4bvbkpffYP/epjPBu0PBUDtXxwf23qg4HO+0Z12E=,iv:NKVFnwdsFOMOsMFxerwFDWf60ESHa/AirvwVBl+/n2s=,tag:aMQ8rZUcy7QtkcOS6ucxDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
