apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
type: Opaque
data:
    username: ENC[AES256_GCM,data:nL/ibb/uF/WkLoUH,iv:nzyLsPtPP0yxs2mRwRO89il8MEg4S0ozS3mxg6e/y54=,tag:DoIAqR7vuVVl/nC0pBatGQ==,type:str]
    password: ENC[AES256_GCM,data:pa9Pc3rALL6tWOG5NnNH8yNREc44qGW6dKWF2yHynTNiq1sNRWl+Ww==,iv:G5AxroWHtHpn8EuveqxH4vq1uwnHF4UxWh9V7vKFZPk=,tag:yyDZPE8GDi3ZKmnDfe9tFw==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:qGEl0xIalP2ez39vk0waGRSCLdk=,iv:zhjkgS8LIWs3MjffoVE082cqj7R86bEuKeSsMzT7jUQ=,tag:MLhRsQiwivJ7LFeGT2xjyg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:wuYW+Xrvn5Ft6qbgPGTiHB2iEn2p/qoN8vG7v9GKjVUgDkl637lcmIOHGBUTYfeX2bQ0P4RL6rc=,iv:E5dymh/RgF/bAkTSFUfHrWxzuS+CoyouHy44dnGxpqc=,tag:cjZN+00ntzy2PX5F31330Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTXlNUzc0bFJjNXhrdkRm
            QWRzSW8reE5Pb1JWR0Z1cmRDWWF1N0FLZlVNClg2VytPcDcwSnpjL3UyVUJQNzJp
            WjNzeUswSmlZQS9SZ0luZjhzaGVqL0EKLS0tIEZna2o3YXdwdnUxNzNCSXVuWEFX
            cm5hWW56cTRMYmpwdE1ZdDhnNzBJUEkK4k6XDXe6ZzjXoFCxj/a6vgayyjvX+g3s
            c/8sG+il1nBDdcKbyuwQnoo+47o8BSKwII7WDsGMd91QcuGcA3xsDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-20T01:23:28Z"
    mac: ENC[AES256_GCM,data:UsvAVSy7A5hnkSf0eEjCcpgWqM+E4yOaTb8QbU2w/0lz4pMoImWH9PLTWI8oX7W7+M2C+tUlY71RSMspA9pkEQRbpQx6IC4SGePMgFCkNpWjo3Q1q/Oq5fEkcI9Wy1lWVU+cjH83/dhy4qqBjH5ZMXCAsUNaAlPcq2LraHkGsD8=,iv:jx3wf+rDp6/MhnDqNE848THEtmeKLs1ga1iMwCEPNFE=,tag:iw3VuKRQcr+aTsaMsVXULA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
