---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      paperless:
        annotations:
          reloader.stakater.com/auto: "true"
        
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16.3"
            envFrom:
              - secretRef:
                  name: paperless-secret

        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.11.1
            envFrom:
              - secretRef:
                  name: paperless-secret
              - configMapRef:
                  name: paperless-configmap
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 2Gi
              limits:
                memory: 4Gi

      redis:
        containers:
          redis:
            image:
              repository: docker.io/valkey/valkey
              tag: 7.2.5
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8000
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.tansanrao.net
        hosts:
          - host: paperless.tansanrao.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      app-ts:
        className: "tailscale"
        hosts:
          - host: paperless
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        existingClaim: paperless
        advancedMounts:
          paperless:
            app:
              - path: /data/local
      nas:
        existingClaim: paperless-nas
        advancedMounts:
          paperless:
            app:
              - path: /data/nas