---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: operator-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: operator-oauth
    template:
      engineVersion: v2
  data:
    - secretKey: client_id
      remoteRef:
        key: tailscale-operator
        property: TS_OP_CLIENT_ID
    - secretKey: client_secret
      remoteRef:
        key: tailscale-operator
        property: TS_OP_CLIENT_SECRET