apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: tun-access
spec:
  statefulSet:
    pod:
      tailscaleContainer:
        resources:
          limits:
            squat.ai/tun: "1"
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW