apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:rq/xn++rtvbseIEfrrOW2s0=,iv:HXm0fRUoU9KbAUeraP4SVG4OhiwIWngwGQ/WjA6pZxU=,tag:fEnVCfJkna8arC+Jmah7Cg==,type:str]
    client_secret: ENC[AES256_GCM,data:mlTQjerhS9dlF+Tu1bjZSs6SERjcpmYH4TJKE6iEWQZLP9cmIhnsIaDcc9K8a5/sqoMY8vBGG9tIHl4FurcO,iv:WtjQUA7ydUOQVqz8MEwTuH22t/FyCjHWFE3opnA3EMA=,tag:YN1rCMTKX49yAfG+VMsDZQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWHc5eVRyTDFRWmJRZHVp
            RjhZZnQvVURSdUNVTXBPdnIxRWFGcHhUbUdBClhkL1RYTHowMXpqY3o0Y0NLM1dl
            V0tpdEZPdXBrUUhFaFd0KzNtTWxrcVkKLS0tIFNzaTJ3MHRZR1RJVWVrM0c2bXBQ
            dkc4aUZjUzBtbm5sdjVnaTRxa1oxczQK4OqaDO/r0mlXSeaMXLyDMsYgKhGfmqfU
            RoGlHURTTtpHQ0v4ta4BqhATmhy01tiVG3iXi3Mjk4XdBJPwAh2LpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T22:49:20Z"
    mac: ENC[AES256_GCM,data:qSsLl1sSJ95knl1dnPQvY//hTEbOpD6jqENYbAAet4PKEVHmt93xHUhLfNNn/6DY8jaDfbwp+B5RRWkROnqNcvv9ailHzTCHO4GGwS3yInTQmLRJYnR7/aVuaZwJBdGLV5RjmRUaiS7rYf2Cu5m9h7MSPgPv/z4Fy6mvEavJBhY=,iv:pyUOzehc3L2ctT/D8shC0UrXEBTgg1O26svGwD3r91c=,tag:/B0DaygMCVK/rz01mNVu5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
