apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:O4haHNcEPzcXZrj9iLgsQr4=,iv:1d6wWEtWmS0fk7lj0D0sETH8x1nZbSYRzOU4k9cT+Dw=,tag:AN/vxiPxL9AD7AxYMcbYwA==,type:str]
    client_secret: ENC[AES256_GCM,data:xU1qpqU7I9PSgn1eMRvHBUcqdlhXhW4itispgjfQY0MJkPWrkXxDUjJ+spNyB4gk5C/VDzuIRIVxtGbRQTgO,iv:0aYwri9MdaFsvsGBGL3klmDToETwErGvzkVJ8O/BbZo=,tag:4gloZ56eMQDoDYvDV+sNgw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6R2RxWVF3OWxZeWhLMytZ
            bTNwUE1GSDB3alpJUFBLK1dTaFhOZjYrMlVVCnYrMVYxYW92aUVNRFcxVkc5UEZO
            SWxoNSt6R3M3S3Q2eTA0Nmd3bUViY00KLS0tIHh1UU9CMk1PUlYzYzczSnJoNTFF
            QVcvdDdVSmZ3blVsOTl2bjZzblBzUjAKY+CPrEOono96WtYN9S6PfJ84XZmD3+hy
            H+IN0KtPH396q51jOYxPQ3ldRonwXqAGTMvYIPD0xTPkfsSN9RXIeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T16:37:22Z"
    mac: ENC[AES256_GCM,data:t4S8ks2Kjisw5aTz40b3fXIVFZuUjQtwMN503JMi2ih6TzDB2rfKInV3v3V5VDJlbMedLwMexbwtSKu+fm5axMd/cIETyGvP3YmF/4Im2Gzh9dV+KjbYUMxftlQ4oMW/lHBBe/8TkL7IF/naCEFafHaEOfXHDJqATp83Pz8+SzU=,iv:bt8YG35JyeBc9olZmH0DzVVQs9svYsEScF3I7GFPG/g=,tag:MVUOti/an7Xht9iwSZnN6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
