apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:I0mCpXUBE4md3lAJ75n1vHY=,iv:A5qd1xbAv2k2Lwy3CrYsxlibUh/rodpUXfSAkEyOfLc=,tag:WaVrzQ5LAZTeVTUmJbutyg==,type:str]
    client_secret: ENC[AES256_GCM,data:+L2f5Z8IVIqeddijNT8Jt/ecE0kAusn4oLl8PXp9OCNy8EDN49mOh/2Uf/7XQRPnZzKqGgFVJUhrJKBH43wI,iv:6G6PJTsaDKsGE41lIt9CchT4t19wmTv27VYQymOSFqA=,tag:PnvhQg2EzS6PvGoX6lfXxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZVozbFYzdnRabUxpMWcy
            MXVQS3BRWS95bFhLVGdnaUlNeHZaVnVVa1FVCnI0ZXZPVkQxZ1FiNEJPVS8yUVcw
            b0ZUaUJUdE9tSVc0akc1ejFUaTVESUEKLS0tIDE0c2FXZlRxSVZyd3pDSlZpS2FL
            T1lZTE5zQkkwYWYzR3F0SGhxR0RieUEKsn8DOduhBMtTvc/1tEv5UvXortLI+u6J
            n2nZJ2LofqnksK1pn96OUOCrIASIgC4p6VlQ5EatDhDHps2pJrPirw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T15:31:54Z"
    mac: ENC[AES256_GCM,data:k/AXwsFySXuqZ/gKeA537OzHNKFi851uEOEmNJNVLyRDbu/iwZx3whmPMnqKsVprcHv/EmExyRAczhFj2AI55cPVIRl1zAhm7QhxB6GCx2/onww9szSMVejAfefv3FQv+WR6RWR580dBF8qi47TzNgFZtN/Okg2dyevzHc3ywo0=,iv:l3slEelZFgTHzdsqLeJxtmy+bxfuRGjamGFVLmWW2mY=,tag:vA8kAhe5F7Z1r5FpgjiOpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
