apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:5wr8B7oRW8eKdW81ZYcTV5rTlFBjq17sF7OT0TiVPoU=,iv:Ibo9ToQPqnxf2nQpwGuJNZWw8x+7P23eWG3zdp+GRcE=,tag:7a4aFF7G6tfIVqL3zWRIQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSCtZLzVBRjVuTm9lZTN3
            aG14UHhkaHhqUnlaM3BseUJ4eHRscDhlempBCnArSnVWSlE3SG1kV0RmbDRLMUh3
            NWh1Z1dmZVZodWVycm54NkxQOC9IbE0KLS0tIGdYRjJtZEpFZ3hETm9xL0hERUxM
            WUR0bzJuWkpVZlNoWHcwZXBGcmFKdncKjtEr+eKCcg7yGX5gkVngs3CVx9iSAlls
            C7jYB8ARwWJzWS+O2HksfDDffyqXE5YucmTYZPfpk8tJWn7WUYRMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-11T00:29:24Z"
    mac: ENC[AES256_GCM,data:9A+zWkUmHVHcbLjR13HUXgVXfEUFpMzPST4uyYWdCuqER5lR7x8Eb78xWv7d4g8aiSP3wF6gBbRAVAx+iVjaPCWL3eGH7CzOfz2oWYjw1O4U1QdZmDQMwERYkqe5VWXbgX7A9xhA0iWsY9t5kkkYOy7jMG80C0j3RgIUE9yIBVo=,iv:9sbYrP1cnmhZzvm7SAW4LgLGYtUDYUMotpw50BQ8bjQ=,tag:gkgqZNMeRgjn571C9Mzbcw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
