apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:9H2Btd1MUNT8SzCkvAvVZ0cVgkmlM+TejTctvNcuG5k=,iv:7j1fXyirFAJowx7fzJvsNT2FK1dSGjI6KohXlg23nOU=,tag:6BsZL5DlnX6LsAaHiGdBjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXb0hlYVNyRVpLM1YzOEQ0
            WktOZUFjbjRBWDlXMUxPRWx3Z2M5MTVuWmxnCk5wWlZjWnpHV0YvQ3dwK3dEbG1P
            Z1NCR3FaSElmbk1DdHk0cW9vQ055bFEKLS0tIGlCcU5pOU14b3NwWEpqNHNjaVZo
            ZS9ISTVQMkJSNXlKMVNnZjJ1bGhhbzAKtFJyV5XCGxM2H/JUhvdGiCSNyEXhZkkl
            NelckjezOkwj15OPbv7vO8jliDiHk38UQgELhdaU8Sg8P2OGHXCIFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T13:03:07Z"
    mac: ENC[AES256_GCM,data:bxNQ26PKB6cyzpZiB0kGGm/43HmN0NxhlSPphXPwYizsh32cM3mD1JE/LuI4MaCjzReEFMW9g0XzbAskJyZgT2IhSsnm78A/Q4Bdk8r6bZF8M+RxjBmM1FS+M93LaanhRxvgmaTwTtj59IZ8IqkYEdhUZGcEjxEOeNr7SlvCyDc=,iv:x3rq+8XWnRh8Lvc+j6ifVxcDnzChr5URJACxyDtjIi4=,tag:GfRXsZPhEiBlRpPfU8XdaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
