apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ERi+RCCreQQdyq+XtckjlUoWjrHNDfuDkz5KK8JVIG0=,iv:2NUg4LcNwfBkFOzrx9vclZlCP3b0ghBp7LFZwPppX5I=,tag:Pg/LfxoUA6ZTZclypX1pLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMnRGZzFQUUV1SlFWN1hP
            dUkyNldXVWpkdTV2ZGF1SE10QmVjSTVORHprCjFxdkluRlJrNWxPR1p0aTVyTnZT
            N0x0SzE0Z1RwOXN0dGZwUXVKTDZaSWsKLS0tIDJndDRrTC8wSG8vK0cyM2VtelZk
            Qlk0cDh5Y1BzUHZDUzNvNzNrRWlJOW8KBUFqzYRnaRYjLsm+IY3+wFQqwEaJEJ7A
            xw0SU3Zm0ascNMin5VzG3lBXZ0cXQ0WZVqzamSMFaIkZ53GN2lvMDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T12:12:20Z"
    mac: ENC[AES256_GCM,data:aLxyBTaxdQAFfSpw7yFsoDUXbH1G5GGTA4xyci4fstvYfSB3jB1ZH//KaOPeTjXSwfPwbaeQ3TwHNq6BeAo4DWXSPxamQ/BV2L5CWhRnYEtmbBKAfGW12fC2ZeT1zG6ucudDrDJZJfiYsLmdHu0w4dzb/DwKtYpvlWnfTgKcWoc=,iv:zFhde++qmecFH+Nn4py4JNYZXEByI1VdVx/325saBhc=,tag:QKG2w3UKxp4C7ioDr2Q8qQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
