---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &app mealie
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *app
    template:
      engineVersion: v2
      data:
        POSTGRES_USER: "{{ .MEALIE_POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .MEALIE_POSTGRES_PASS }}"
        POSTGRES_SERVER: "postgres16-rw.database.svc.cluster.local"
        POSTGRES_PORT: "5432"
        POSTGRES_DB: "mealie"
        DB_ENGINE: "postgres"
        INIT_POSTGRES_DBNAME: "mealie"
        INIT_POSTGRES_HOST: "postgres16-rw.database.svc.cluster.local"
        INIT_POSTGRES_USER: "{{ .MEALIE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .MEALIE_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Base Values
        BASE_URL: https://mealie.tansanrao.net
        ALLOW_SIGNUP: "false"
        AUTO_BACKUP_ENABLED: "true"
        API_DOCS: "false"
        TZ: America/New_York
        WORKERS_PER_CORE: "1"
        MAX_WORKERS: "1"
        WEB_CONCURRENCY: "1"
        SMTP_HOST: smtp-relay.default.svc.cluster.local
        SMTP_PORT: 25
        SMTP_FROM_NAME: Mealie
        SMTP_FROM_EMAIL: "noreply@tansanrao.com"
        SMTP_AUTH_STRATEGY: NONE
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: immich