---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mealie
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      mealie:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: *app

        containers:
          app:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v2.4.2
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 256Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 9000
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.tansanrao.net"
        hosts:
          - host: "mealie.tansanrao.net"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      tmp:
        type: emptyDir