---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false

    controllers:
      immich:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: "16.3"
            envFrom:
              - secretRef:
                  name: immich-secret

        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: &tag v1.115.0
            envFrom: &envFrom
              - secretRef:
                  name: immich-secret
              - configMapRef:
                  name: immich-configmap
            resources: &resources
              requests: &requests
                cpu: 100m
                memory: 250Mi
              limits:
                memory: 4Gi
            securityContext: &securityContext
              fsGroup: 65539
              fsGroupChangePolicy: OnRootMismatch
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL

      machine-learning:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: *tag
            envFrom: *envFrom
            resources:
              requests: *requests
              limits:
                memory: 8Gi
            securityContext: *securityContext

      redis:
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.0@sha256:6725a7dc7a44a6486b9d0a5172b10ccaf0c2ea600df87c0b93450d0e7769297f

    service:
      immich:
        controller: immich
        ports:
          http:
            port: 3001
      machine-learning:
        controller: machine-learning
        ports:
          http:
            port: 3003
      redis:
        controller: redis
        ports:
          http:
            port: 6379

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.tansanrao.net
        hosts:
          - host: &host photos.tansanrao.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: immich
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: immich-upload
        globalMounts:
          - path: /usr/src/app/upload