apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:cU0u2GSXKt4=,iv:LAAnkyi7u0rEguNyp2phZRk32p2rz8MZaXytkBOJfQk=,tag:mf9HqJ6uYl0FJa0gER0VCQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:GfgLQ8PLj+nBNsNF/BujGz3OQ9pyaimCh5+XtA==,iv:gTBOzXRMz0zj1VUV3OWhOq+XmFQASqwvuWarPi5wAuc=,tag:NJ0glJOsfV3WzZW7NS1aYg==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:GK10+4b0F21PFD6wcaenKodXovlXoKythjpQJSP1tI2fVDCSfwCljU5FTaL86mdw2Y27JHkMZbxbwqRGtQpiJQ==,iv:p69S3RrrKL07eYN3iYjsVeynAQcgwDf3Gmd6+7NtY2A=,tag:bU8ed7LGNIjDb/XZ6qfkrg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:yUROwssR3Tk7or8656s5Qj/L/tIfFGUiSsZcBZxjSrg8dEYfpk4jICn2a7+jFJiLhCMlsM9wJv8yjeIp9e4trw==,iv:ThyrBuLA9OLLfhaualOpLZ0DQHv2lEJuwxGk82mR05Y=,tag:ZlySrlaQ3BGV4c316DZILw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:hZcIKM/y,iv:YXV74F7SJv93jljzDoVFDgCeXWf9iIdR0UzaRL/8Qn0=,tag:Fl2NcMuTQELOSCbyUwLZHA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:KQrk2XjDqrs/SENvPT9t9LA1j0T8Fm/kXeEx5uak8pHR1ypCk6Ck,iv:QoJw3f37HDN4q61A2k9WmN36MDcgV9Adg9M4Txm/CQk=,tag:VavLABnRZCK0bwEsaKtCbQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:4HGa2Cfb,iv:mP3EDZ2p075eUvbxwxlId62B7ixbXNzF0i5Ao5r+cmo=,tag:M2TkHFxPVGtxB30UcJCh2Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:+oV5aVrwORQVdzaVqMoir1ot1+qx,iv:1IYMTVOKvFPHqxk0rByyezrZi9n3q9buRid+2wOrnKA=,tag:cecBqV6CdiCCjGIrsC/TOQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ryKRJuyQR3clYq91YmlFs27cQny9+zB4YZCw/w==,iv:HlGkkVjDTM6gKneyJubZpnuYXXTxiSfSYo5ozxJiiLE=,tag:bLzJl/Y01Zje5Ivy4pMqPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraVEzL2NEaC9MenZCZTUz
            bFQvZlNnazloK0Jyc29pdktnMlZmdW1BWm5RCk5RcW5JUWRkOHlMRHl1ZFl0RVA5
            YXJZbFJCOXRUdldRbjV1NTIzTkFYZDAKLS0tIGdYUTcxWGM3UE5pN0FWTVRORity
            Y0dLTjNEdmNXVms2RDJtdXR1UDIyYUkKJDVKMWubR1zEgjRd2RJtpz+Z4/ijCczO
            jTkOfcZrs2BKVDSNm6T7N/JhyQHOzTSxHnphHYP/mFnz+NrLiu8Mzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T16:37:23Z"
    mac: ENC[AES256_GCM,data:MJYHbnNXS56m0ynWXh3rfiPHVEcm16sEr60IC+R3Gb3HwGgsmEtmRndlG/snnNZ0+JaCQ4W6hn/MusaW789wDa/CpEwiMqjEOEEQ2EJZdW2b2YYDxA+cBNSS/I2Y5tNxaOo6VrShnOhQ1tlCnUDklEwxt8UDx8qdSO9zFVr+0EM=,iv:0Hs9Yoi9YmPjoL4kD6XjinapHRe6+IASHkg25wonUyE=,tag:zytzLK3227xCh7QsGGyAjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
