apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:JICt8dK9,iv:4qdqf5m8cJtqgVXp4XbVbHSSwtWhKF0Il4mnj1XZYGA=,tag:kZUqnTZDjRR17iwEQNZWwg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:BzsYKL0uzyPp3QfddiyYc5SDoPPk4y0+m2k=,iv:b86OmmYNhocrD4HMGOoLUkHJslGVpVk+mdQ6YC2+SfY=,tag:Eptn26KMkULRj5AhtnHtmw==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:0sqAT5LsWYPqpiOwdKFJGshmlUjR5RxbWII8rsuojBwboFWs+f24kIlVRi2dWDbMiEZiOjexmIGBZyOa72yzJQ==,iv:Tls3rm4LoDlZFZCEB6cpMv4Sr3YvkEZptc4YCK0KOOE=,tag:CIvaeV/ozdj4sV7oOZ6uDA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:ytllS6qNs4Ke6v2g+WNM4gKnNY7Fo+iawVZMgwkDk2RTxW2lFz/3mXCapgH/WtxhHCuS7x0Q5HFUcvf4OzeJBg==,iv:yEiQ75Ai+hQ+ESJj684QsL8D0xZ+DGJzfACw1wJx40Q=,tag:ELHo2OKrRBZXmCJ7GPw+BQ==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:GAfdZYrk,iv:LlPF+6eWJD5MVZj0NrwXPCpoCu9rqvxBUzooG3k1R4Y=,tag:ROg7z9WPvk+OeGEMvCDWcg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:f0RRERKPSTYYhH/c/R7FZyD+TKjI8GokPjiSo2AaBrUMD4R1ejs=,iv:9sj6BOQc2R14w6Eu5aEkdWJKcVp114PPWDDVvdCZ8QA=,tag:6hTFYyLa7uGSr6rwtW3eyg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:RUe1TgKb,iv:Rw9DOJOMx1krXmTvT5fKatWiAT/eKw6hS5y6K+Twm1w=,tag:B4ul6TirP5h1k8vYLKEZJw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:R9vYxMu+M7g5O6O632pAEYvrR6Nx,iv:C8CchMo7q/RYVQp2dKpOCsleiuehHqbl+FwpbPUV8e4=,tag:if5WhAedIszfVWxSL4fkag==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:p6nL+W5YlnzTbe0nxWljwZ2Rzp9yrOrVeW5k8A==,iv:Z/DFXh8HmnFbbuGwVkG26dn41u9wNTSk1k5D/sxDnk8=,tag:ZFvo64/kkxRhnDGaxv/iBg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2enlPUmdTNEpDeng3bE05
            bFo3a1JpQ29aK3BsYWcvWnJIWnFOYkFaOHpVCllkcy92cW5VdnNscG9YS1hlQnRx
            b0RTeFVCR3d4ZjRFRkVKdE5jRlJ5Rm8KLS0tIDNxRmZENEpnT0dKRUpsTWo1UDZ1
            RGlIYTVZSDZWWkQ0UXA5SVNCYlMrU3MKsD5NEV9EuHgt743YsOXswew1MQLc4sBT
            osQqXH2V7zJCrUYhkkoFI1RCb1vTPJSkOwyf4PIeKHHnANM4fPCBSg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-16T20:42:06Z"
    mac: ENC[AES256_GCM,data:39fawZIYDzKgWUDa1VglEnn+ItXzCQZttwahrHOPz6LftjaQMZaTziNL/+pmWnJJsq0GssYOlRn3teO/5WtF3Upfkv1MWwI1j8AEFTAf0FM3cgOO+inGSqs29Z23XOOviOTCqZtB9xbRQ0ESHzy1l1cpsbm0y2owU6KJ6+43i84=,iv:kKi9ZA8Cw85EzMmM1gMZ9ArobhY8h5VhSWuUBtfg8oY=,tag:n1JABx74MByAnGPp/Go17g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
