apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:0tpgRLMaie8=,iv:4BqF1fIJv5BW87TaZ5atZ07aTVlkv+uUeTwjJSZZP/I=,tag:rMdDa6Eoy5vJ/h+sLkYfmw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:yV3uTjCtcC6Lf1viS2RwjqVdQJNS4EmeFxVYKA==,iv:9eyIewhnNXl8qLJR5wO7VVfweWRFcOqqeuPJnKdmkdw=,tag:WjdGNnk0YSqFsL9DxvCSLA==,type:str]
    OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:7Fgk1QAiyeb/D22dpvCOw6C8ILn07g4vIKFQq/cUireTZLD6q+QFSR+66AfdmoQMJW49LQBe5N4K3epdA2nfCA==,iv:faaEcguKQAGJRxX0ZCSlgHHFRLYBKi4nUw30nXoGJSc=,tag:GdQtaQohDhe4irUvRutNrA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:yxCQXDfmR8TOZlCye4u782Quzoa3OHtDK7ebBWXuqghS4Y2T9XqnLm43JRzH368oi72wq1g7UBtLSQWoGmF8OQ==,iv:Q84Ls57KKXkdRo3/rgfhusc82qhaqxFEzio0ORkvu1U=,tag:vrYkWYQqeO0vz5Bnq6mdzA==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FbeG2jkQ,iv:cLnJRl5DZ0t1dDizCh87x4OL6V2lLmn26Y+UlkBfvzo=,tag:h1uFKdr9B5Mr19mqicLpnQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:CdNpnCHZrZikApWuUQ/toZlvBIi3CCpJGyPIG4XWh8ub2yuZZaom,iv:ShH1QnrZ7GyeEvIYoMB/nFE5hLSLW7ObbrRwyktHkso=,tag:ZhIIPC4Ku60ryYssLMjbUA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:4+THgfqo,iv:Kyo+GPmeEkkgozWhxjA90oYP4NcKHZfRMWex7qG4BQM=,tag:bWIFtwVvIuBtr8lTADPRMQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:p+GPDKo+WtKE38j1GSEiKoYEYExg,iv:wGe/MfXgDSLmx6YLsXySydIVHi4BBU1Q1+ZWGGYevNY=,tag:vVDObKl0nfRUfp9j67O34A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:erKzYJDrFTHtfpYe5FVoDg9+0UvG9RrCCKpSCA==,iv:l1msS4VZCYkOdWSy98/u97FtAkpSzn3yM/IPfbBf1jA=,tag:uCrxr5FDDjVjBzs1xW9+gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzF3UG5wY1NZajV3aVc0
            TUZsdVV4c2I3MmltSFpPM0RLVTdXQnZqM21BCkV2Vk5UU2RPVkVjV3dmOE1zZXhi
            YkZ6ZWxSZmhFc1lxTlBVY3V6VVRrTGcKLS0tIHR3bExaREVQamhRQktLU2NyeE5q
            dXpRQ1pKbENQN1g1TE9pTThVZHBmZXMKbG7C/IdM995DtFd6HNLY/bb1pkVnuUsc
            l063DlV74LDJigO6ICbHdrHUMXJOqtjja7k+GFMOdaZ2A7s759G+/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T13:18:42Z"
    mac: ENC[AES256_GCM,data:i2TIxuL0pjwDqXWVlhNEMf4DLmr6U07cvcypMICr7s0Jev2ZQ34AcD8DHd4X5wb5CmqXMNFjjKwBKbY/eREg9le/tBi3AUCU4tRWb8s1lclRbVo51Ffq+pnf3ANGkaDj6DPz91BTI5ldMS0nOb6mHXOFHvyauNhzaK0PvhLnSZ0=,iv:D7xq+BFxKSi1LumiRAS9aRU6sS8a+lcU5lz2oF4Oh8c=,tag:ibyvDsAFpVLKLNDyhl2kuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
