---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app seafile
  namespace: flux-system
spec:
  targetNamespace: default
  dependsOn:
    - name: seafile-mariadb
    - name: external-secrets-stores
  path: ./kubernetes/apps/default/seafile/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  wait: false
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: files
      GATUS_PATH: /