apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:O5RRQlriYWi3BUTlyzmclTCtvtF0f2qbcu9aaz/PP61lyHlmEYomLQ==,iv:/jvDtvR4un2gqO2GtJn6Rt38h6Nn1V/3lzZR7Uh/pNI=,tag:HIJfphpH1K24b3UHfyOzag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISnlIMkMwK2N5a2oybHJW
            ZnJ4aXVpeWxYbmZoTFhveXFkNHZIZmt6WG1FCmZSeUVoakl4dHR2RzJucEl2WHNx
            ZnlTRVM3a0E2cWVuVWVvbzhRWmo3K00KLS0tIDdPSExUaUVBU2RPc2k0SHllVEVt
            OHdXdG1aWXhEUDAyaDVuVUpYY1p3a3MKVBsyaqntU5wVjmAwABHV1x6fGIGk7cMa
            iNnywhGzS43FhLbnyoaGM0HmH6B3B/4q2updQaBE2zIVTj734HtMkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-21T15:57:52Z"
    mac: ENC[AES256_GCM,data:yLRIIngyt8hr/W5ck9O9Yi3tKTFZlCMzuG2LPmmTJHaL5PlJLwtts+WxbUZsEvxQrOFcgFDXIJr64WWyAuFP44cdwvwaJvzHJ8RsyTDVufOr9JiT/znMGiJ5I8hnJzJVNblX+M95Wx1tQy/bBqzFU+hdV0GMmsCjWe8h6HCYDWM=,iv:cziUFNN4sqOj3sFQMxSRHhNqL2BwFxyKnrngQsA81vE=,tag:p/qXnzoqhj8WLIPNMVhqQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
