apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:E93ynB2RwDlwEjKhbizdEn15kpATR7jSjeFNEy9RYXM/5HSM9XrZ7Q==,iv:3zLATzRRuIH8HrfsjQ/s4e+bQYoVvXaNvRtlcLU5io4=,tag:aTWr1UTC7APeOCe3eNW9Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeDgwaWRmQ2pMeVA0Y0M5
            Y1RFcUprY2l5ZmZhR0JmUWZQL0VSOUVSNGc0Cldvb3pOanc5M3RlUnhZYlpZNm9w
            c0tiRERBYXRsMXlObkxmOTJKZjA2aDQKLS0tIFlkMjdMUDd3dW9CRU1BQ0pMczB6
            S0VLSTRPcjRoTTVGNU1vZnBGVVNRcnMK5XOsyotATs0ztEITIhWwsaJMzW6PxhR9
            P1YcGzjbVsbe4XWnAH+upqj8tpozZTAQJRoOVrdYeP3Ajduou3WQzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-22T12:08:21Z"
    mac: ENC[AES256_GCM,data:/9l/cnta0k67wWdNXLrtR6Sjx/fPQ12jSa5yWhHSVa/xDiuavh7oZ6sIrWzngU52QG+lZUgWeKHVXDJ4jbH39LcwvJQ4foSStAWMZqokjBCCC/rUgQ1TvM+5Vy+wbKNDWGucz9txyIJrA6jbbVgxOazMClmkIsT/TqLmbyOMa50=,iv:fSzyP/92KIyeGsGyCcMEOCNHR3+ePC/rodKX/ANP8eU=,tag:69IhF0tKKgD4iY9/qOgd4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
