apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:h3TKqfGe+XnBNMBCOrK3uqpMnmSjbI+s3ePN0ayNKdKka/JLj4DnCA==,iv:LfHqpUWwClm2+eI6YlbpGhY8g5nUxQQsA1f72qWI1cA=,tag:toYW92d1rXdnp1pWVAKqyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pc8vkadvcyahyvjjpr77fxcex562gja336dmkly5ea9j72c6jeaq6e7frr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucGhFS3U1ODMwcFhienJk
            S1J4aXVMU0grNmtla2ZwaktDdzNod2EvZUhNCnFDNEpQSHVhM0hyZDlOSWxpVE9F
            UDg5M1Z3cXBoY3ZmSzF0ejBHcHFhMXMKLS0tIDd2VmdlbHBGZkQ5V0tHdTVZNG44
            QS9pTDdEdXNKMmRTdzJHemdjaUtvTWMK6a/ZO1M5f661l4nIBnZ77B3isjgc2Gs+
            eRlR1RTMBkGOeLRLUbE0Yq1suCedsnUPNQTO63lYZPOcTK8Q7s5wpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-18T22:05:21Z"
    mac: ENC[AES256_GCM,data:NMQwEiWruCyKP1NPFwTarmtArMcT4+h7ywseQs9u/ENI0GsrikEmV5R8cEDd/6004gDffEDDntfOD46SwyQ3c4A/7wVmToGN58il7iazZ5tgvm/JP6EysHA7dQczJtE0LxEw/ceI/0gfdOWcJ/+w5QjYjyQE9eyXaZHfO15e4RM=,iv:ueJgsJNYr5xxA2p4p+ItYM12jsapDVrGehlssSMaGGw=,tag:1YRFAg+218gN1qoemRT9yw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
