apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:4qKSYiPI3fq65eOoVYYP67cAyjOsc0JoWG1Sd4eJz+kIYHEONb1ubA==,iv:w3s7YAXvYglvPmY37zRa9rdntpf1TDvtk9vb/Gm2Geo=,tag:U+anIpGfec1GOFfsZYFylg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fhykf9jed0ltz2fguu3l9h60xv0m35hk4faqfr4yt397cdw3p9nqeuc5t7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Mkl3eTh4WDJaeFVYNXEx
            T1ZNRnpDbTNqM2h2Tit6Qnh1SFV6dnRoeTBNCnAwS1J2QlQvaGtwT0NyTFAvMnNL
            OFVtMzJaa2JWK1NFb05uL0pIbVo2YW8KLS0tIHdrVnZFUVZ0bU51Z3c4QmpFczdj
            Sm9maTdpNE5aUDBzQWY5TGgyKzJsRnMKVWP8FnDF0WEapV8UTVaXx8eP5IqhzEn0
            aUvIyy31C6HFaq8e7WxfxqPjdDaCUH0nsY6b4abrvSxp0k9Uy8rpQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-06T12:41:48Z"
    mac: ENC[AES256_GCM,data:SZevtjXmSc2LJpKXKu7DbCldDW9c2F7NRrKWUUmTKdWHHaEXOOnH0EmL8ls9eSLncWAA3RtAfocsK4hDEkt0GzLZZdmhM7qTFIMdLsl+91tWbKel8QYRdtnvZNvnEAbPKY9aIwIhgU4lSHsg9ylzA1tbHqTJs+jSMLe8Tz96JZc=,iv:XCwp/zvw0wZl6xd1PwhEu5QqzpPekscdg0FR/6u4hMs=,tag:slooXAPkCB3TlfjoRNa+rA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
