---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: mediastore-pv-smb
spec:
  capacity:
    storage: 10000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: 192.168.101.10/mediastore
    volumeAttributes:
      source: //192.168.101.10/mediastore
    nodeStageSecretRef:
      name: smbcreds
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediastore-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  volumeName: mediastore-pv-smb
  storageClassName: ""