---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ocis-secret
    template:
      engineVersion: v2
      data:
        OCIS_JWT_SECRET: "{{ .OCIS_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: ocis
