---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ocis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      ocis:
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-config:
            image:
              repository: docker.io/owncloud/ocis
              tag: 5.0.9
            command:
              - /bin/sh
              - -c
            args:
              - |
                if [ ! -f /etc/ocis/ocis.yaml ]; then ocis init; else exit 0; fi
            env:
              OCIS_INSECURE: true
            securityContext: &securityContext
              fsGroup: 65539
              fsGroupChangePolicy: OnRootMismatch
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL

        containers:
          ocis:
            image:
              repository: docker.io/owncloud/ocis
              tag: 5.0.9
            env:
              DEMO_USERS: false
              OCIS_LOG_COLOR: true
              OCIS_LOG_LEVEL: info
              OCIS_LOG_PRETTY: true
              OCIS_URL: https://files.tansanrao.net
              PROXY_TLS: false
            envFrom:
              - secretRef:
                  name: ocis-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 2Gi
            securityContext: &securityContext
              fsGroup: 65539
              fsGroupChangePolicy: OnRootMismatch
              allowPrivilegeEscalation: false
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: ocis
        ports:
          http:
            port: 9200

    ingress:
      app:
        className: "external"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.tansanrao.net
        hosts:
          - host: files.tansanrao.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      config:
        type: configMap
        name: ocis-configmap
        globalMounts:
          - path: /etc/ocis/web.yaml
            subPath: web.yaml
            readOnly: true
      data:
        existingClaim: ocis-data
        globalMounts:
          - path: /var/lib/ocis
            subPath: data
          - path: /etc/ocis
            subPath: config
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
            subPath: tmp